#!/usr/bin/env python3
"""Generate reproducible, entirely fictional Wolf procurement fixtures. Python standard library only."""
import json, random, csv, statistics
from datetime import date
from pathlib import Path
from collections import defaultdict
ROOT=Path(__file__).resolve().parents[2]; DATA=ROOT/'kit/dataset'; UI=ROOT/'frontend/src/data'; PUBLIC=ROOT/'frontend/public/data'; T=Path(__file__).parent/'templates'
for p in (DATA,UI,PUBLIC): p.mkdir(parents=True,exist_ok=True)
r=random.Random(9182029)
def money(v): return round(v+1e-9,2)
def total(xs,key): return money(sum(x[key] for x in xs))
def dump(path,x): path.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
schema=json.loads((T/'exports.json').read_text()); modules={}
def emit(file,values,code=''):
 modules[file]=values
 out='// Synthetic Wolf Materials Lab data. Generated by kit/scripts/generate.py. No real commercial records.\n'+(T/file).read_text()+'\n'
 for k,v in values.items():
  typ=schema[file].get(k); out+=f'export const {k}'+(f': {typ}' if typ else '')+' = '+json.dumps(v,ensure_ascii=False,indent=2)+';\n'
 (UI/file).write_text(out+'\n'+code+'\n')
geo=json.loads((T/'geography.json').read_text())
geo.append(dict(iso='XK',name='Kosovo',region='Central and Eastern Europe',lat=42.6,lon=20.9,language='Albanian'))
# Geography is public context; every network attribute below is newly generated.
cluster_names=[('lack','Paint application and mixing'),('schleif','Sanding'),('kleb','Masking and covering'),('polier','Polishing and finishing'),('kabine','Spray booth and cleaning'),('psa','Personal protective equipment'),('werkstatt','Workshop equipment')]
supplier_defs=[('aster','3M'),('velora','Glasurit (BASF)'),('lumen','Finixa'),('novex','Mirka'),('arcus','SATA'),('cobalt','tesa'),('solis','PPG / Nexa'),('orbit','Würth'),('helio','Kovax'),('vanta','Starcke')]
products=[]
catalog=json.loads((T/'product-catalog.json').read_text())
dump(DATA/'product-reference-catalog.json',catalog)
selected=[([x for x in catalog if x['cluster']==cid][i//7]) for i,(cid,_) in enumerate(cluster_names*3)]
for i,ref in enumerate(selected):
 cid,cname=cluster_names[i%7]; products.append(dict(code=f'WLF-{1001+i}',name=ref['name'],cluster=cid,category=ref['category'],unit='piece',referenceId=ref['referenceId'],referenceSpecification=ref['specification'],referenceUnit=ref['referenceUnit'],basePriceEUR=money(r.uniform(2.8,72)),gtin=f'200000{100001+i:06d}'))
suppliers=[]
for i,(slug,name) in enumerate(supplier_defs):
 suppliers.append(dict(id='sup-'+slug,name=name,type='Distributor' if slug=='orbit' else 'Manufacturer',countries=[c['iso'] for j,c in enumerate(geo) if (i+j)%7!=0],clusters=[cid for j,(cid,_) in enumerate(cluster_names) if (i+j)%3!=0],offers=0,matchScore=r.randint(63,97),priceDeltaPct=-money(r.uniform(3,24)),logisticsSavingEUR=r.randint(8,52)*1000,status=['shortlist','under review','submitted'][i%3]))
# Canonical clean transactions, complete January-August coverage, varying prices and quantities.
lines=[]; prices={}; fx={'EUR':1,'SEK':11.4,'HUF':394,'PLN':4.32,'CZK':24.8,'RON':5.08}; currency_by={'SE':'SEK','HU':'HUF','PL':'PLN','CZ':'CZK','RO':'RON'}
for ci,c in enumerate(geo):
 for pi,p in enumerate(products):
  price=money(p['basePriceEUR']*r.uniform(.64,1.69)); prices[c['iso'],p['code']]=price
  s=suppliers[(pi+ci)%len(suppliers)]; cur=currency_by.get(c['iso'],'EUR')
  for month in range(1,9):
   qty=r.randint(24,330); eur=money(qty*price); n=len(lines)+1
   lines.append(dict(id=f'TXN-{n:06d}',iso=c['iso'],month=f'2026-{month:02d}',date=f'2026-{month:02d}-{r.randint(1,28):02d}',productCode=p['code'],supplierId=s['id'],brand=s['name'],description=p['name'],cluster=p['cluster'],qty=qty,unit='piece',unitPriceEUR=price,valueEUR=eur,currency=cur,valueLocal=money(eur*fx[cur]),source=f'synthetic-spend-{c["iso"]}.csv',matched=pi<16,route='direct' if (pi+ci)%3 else 'indirect'))
bycountry={c['iso']:[x for x in lines if x['iso']==c['iso']] for c in geo}
offers=[]
for si,s in enumerate(suppliers):
 for pi,p in enumerate(products):
  if p['cluster'] not in s['clusters']:continue
  for version in (1,2,3):
   offers.append(dict(id=f'OFR-{si+1:02d}-{pi+1:03d}-V{version}',supplierId=s['id'],productCode=p['code'],version=version,validFrom=f'2026-0{5+version}-01',priceEUR=money(p['basePriceEUR']*(1.03-si*.023)*(1.08-version*.045)),unit='piece',packQuantity=[1,10,25][pi%3],status='agreed' if version==3 else 'superseded',source='offer-versions.json'))
for s in suppliers:s['offers']=len([o for o in offers if o['supplierId']==s['id'] and o['version']==3])
countries=[]
for c in geo:
 shops=r.randint(7,39); n=r.randint(0,shops); countries.append(dict(c,dealers=shops+r.randint(3,27),bodyShops=shops,entryYear=r.randint(1982,2023),revenueEUR=total(bycountry[c['iso']],'valueEUR'),submissions=n,submissionTarget=shops,maturity=r.randint(1,5),intakeStatus='live' if n==shops else ('pending' if n==0 else 'in progress'),topDemands=[x[0] for x in r.sample(cluster_names,3)],supplyDependency=['Direct manufacturer supply','Distributor (two-tier)','Import via northern central warehouse'][len(countries)%3]))
clusters=[dict(id=cid,name=name,description=f'Synthetic material category: {name}',positions=sum(p['cluster']==cid for p in products),spendEUR=total([l for l in lines if l['cluster']==cid],'valueEUR'),savingPotentialPct=money(r.uniform(6,22)),exampleItems=[p['name'] for p in products if p['cluster']==cid]) for cid,name in cluster_names]
standard=[dict(nr=i+1,cluster=p['cluster'],kategorie=p['category'],artikel=p['name'],spezifikation=p['referenceSpecification'],einheit=p['unit'],prioritaet=3 if i<16 else 2,marken=', '.join(s['name'] for s in suppliers if p['cluster'] in s['clusters']),anmerkung='Synthetic dataset') for i,p in enumerate(products)]
dump(UI/'standardsortiment.json',standard)
dims=[dict(id=id,name=name,description='Synthetic learning and quality dimension') for id,name in [('material','Material expertise'),('prozess','Process quality'),('daten','Data maturity'),('digital','Digital adoption'),('nachhaltig','Resource efficiency')]]
training_defs=[('t-basis','Select materials for a repair','material','lack'),('t-prozess','Document the process sequence','prozess','kabine'),('t-daten','Check invoices against price agreements','daten','werkstatt'),('t-voc','Reduce material consumption','nachhaltig','lack'),('t-psa','Select protective equipment','prozess','psa'),('t-digital','Digital demand submission','digital','werkstatt')]
trainings=[dict(id=id,title=title,format=['Video','Roleplay','Video + Roleplay'][i%3],duration=f'{15+i*5} min',cluster=cl,dimension=dim,languages=['EN'],description='Exercise using fictional records and documented human review.',completions=r.randint(24,176),avgScore=r.randint(65,96),autoGenerated=i%2==0) for i,(id,title,dim,cl) in enumerate(training_defs)]
profiles=[dict(iso=c['iso'],scores={d['id']:round(r.uniform(1,5),1) for d in dims},gaps=['t-daten','t-digital'] if c['maturity']<3 else []) for c in countries]
contracts=[]
for i,slug in enumerate(['velora','aster','cobalt','novex']):
 s=next(s for s in suppliers if s['id']=='sup-'+slug); cs=s['countries'][:8]
 contracts.append(dict(id='ctr-'+slug,supplierId=s['id'],title=f'Framework agreement: {s["name"]}',clusters=s['clusters'],countries=cs,volumeEUR=total([l for l in lines if l['supplierId']==s['id'] and l['iso'] in cs],'valueEUR'),termYears=2+i%2,stage=['Negotiate','Build','Negotiate','Agree'][i],progressPct=[55,30,68,96][i],negotiatedSavingPct=money(r.uniform(7,19)),openPoints=['Confirm invoice reconciliation in the pilot'] if i<3 else [],trainingCommitments=[dict(trainingId='t-daten',scope='Fictional pilot: invoice review across all sites')],maturityGate=dict(dimension='daten',target=3,note='Demo assumption: documented review step'),nextMilestone='2026-09-25: review the synthetic pilot case'))
intakes=[]
for i,c in enumerate(countries[:5]):
 p=products[i];intakes.append(dict(id=f'sub-wolf-{i+1:03d}',iso=c['iso'],site=f'Wolf Atelier {c["name"]} {i+1:02d}',channel=['Voice','Photo','Delivery note','Voice + Photo'][i%4],language=c['language'],timestamp=f'2026-09-18T{8+i:02d}:20:00Z',items=[dict(cluster=p['cluster'],item=p['name'],qtyPerMonth=f'{r.randint(15,90)} piece')],painPoints=['Invoice pack unit missing' if i%2 else 'Price agreement requires review'],status='structured' if i%2 else 'processing'))
company=dict(claim='Precision in every material step.',vision='Fictional luxury car manufacturer for the Wolf Challenge.',standorte=sum(c['dealers'] for c in countries),laender=len(countries),mitarbeiter=18740,umsatzMrdEUR=18.6,neuwagen2025=284700,gebrauchtwagen2025=68400,informatik=dict(loesungen=84,laender=len(countries)))
emit('platform.ts',dict(countries=countries,company=company,standardsortiment=standard,clusters=clusters,suppliers=suppliers,maturityDimensions=dims,maturityProfiles=profiles,trainings=trainings,roleplayScenarios=[dict(id=id,trainingId=tid,title=title,persona='Fictional Wolf training assistant',goal='Document record review with a clear audit trail',phases=['Read the record','Check the match','Confirm the decision'],language='EN') for id,tid,title in [('rp-bedarf','t-daten','Capture structured demand'),('rp-reklamation','t-basis','Resolve a price variance'),('rp-unterweisung','t-psa','Practise safety instruction')]],intakeSubmissions=intakes,totals=dict(spendEUR=total(lines,'valueEUR'),positions=len(products),sortimentArtikel=len(products),submissions=sum(c['submissions'] for c in countries),submissionTarget=sum(c['submissionTarget'] for c in countries),offers=sum(s['offers'] for s in suppliers),priceSavingEUR=money(sum(c['spendEUR']*c['savingPotentialPct']/100 for c in clusters)),logisticsSavingEUR=sum(s['logisticsSavingEUR'] for s in suppliers),avgMaturity=sum(sum(p['scores'].values())/5 for p in profiles)/len(profiles)),contracts=contracts,contractStages=['Build','Negotiate','Agree']),'''
export const fmtEUR = (v: number) => v >= 1000000 ? `${(v/1000000).toLocaleString('en-GB',{maximumFractionDigits:1})} million EUR` : `${(v/1000).toLocaleString('en-GB',{maximumFractionDigits:0})} thousand EUR`;
export const clusterById=(id:string)=>clusters.find(c=>c.id===id);
export const countryByIso=(iso:string)=>countries.find(c=>c.iso===iso);
export const trainingById=(id:string)=>trainings.find(t=>t.id===id);
export const maturityByIso=(iso:string)=>maturityProfiles.find(m=>m.iso===iso);
export const supplierById=(id:string)=>suppliers.find(s=>s.id===id);
export const contractById=(id:string)=>contracts.find(c=>c.id===id);
''')
# Product and country summaries all derive from the canonical transactions.
specs=[]
for p in products:
 demand=[dict(iso=c['iso'],qty=sum(l['qty'] for l in bycountry[c['iso']] if l['productCode']==p['code']),valueEUR=total([l for l in bycountry[c['iso']] if l['productCode']==p['code']],'valueEUR')) for c in countries]
 eq=[]
 for s in suppliers:
  offer=next((o for o in offers if o['supplierId']==s['id'] and o['productCode']==p['code'] and o['version']==3),None)
  eq.append(dict(supplier=s['name'],product=f'{s["name"]} {p["name"]}' if offer else 'No offer',pricePerPiece=offer['priceEUR'] if offer else None,basis='Synthetic net price per piece' if offer else 'Not offered',filled=bool(offer)))
 filled=[e for e in eq if e['filled']]
 specs.append(dict(code=p['code'],neutral=p['name'],kategorie=p['category'],chips=[p['referenceSpecification'],'Synthetic purchasing unit: piece'],brandName=f'Wolf reference {p["code"]}',demand=demand,totalQty=sum(d['qty'] for d in demand),totalEUR=total(demand,'valueEUR'),nCountries=len(demand),nEquivalents=len(filled),bestPiece=min(filled,key=lambda e:e['pricePerPiece']) if filled else None,equivalents=eq))
emit('produkte.ts',dict(produktSpecs=specs,kategorien=[dict(name=name,specs=[p['code'] for p in specs if p['kategorie']==name],totalQty=sum(p['totalQty'] for p in specs if p['kategorie']==name),totalEUR=total([p for p in specs if p['kategorie']==name],'totalEUR')) for _,name in cluster_names]))
ncountries=[];public={};monthly=[]
for c in countries:
 ls=bycountry[c['iso']]; brands=[];public[c['iso']]={}
 for s in suppliers:
  sl=[l for l in ls if l['supplierId']==s['id']]; val=total(sl,'valueEUR')
  brands.append(dict(name=s['name'],valueEUR=val));public[c['iso']][s['name']]=dict(totalEUR=val,count=len(sl),lines=[dict(code=l['productCode'],desc=l['description'],supplier=s['name'],qty=l['qty'],unit=l['unit'],eur=l['valueEUR'],local=l['valueLocal'],cur=l['currency'],note='Synthetic purchase record') for l in sl])
 ncountries.append(dict(iso=c['iso'],name=c['name'],directVendors=[s['name'] for s in suppliers if any(l['supplierId']==s['id'] and l['route']=='direct' for l in ls)],brandsBought=brands,totalEUR=total(ls,'valueEUR'),rows=len(ls),files=1,currency=ls[0]['currency'],language=c['language'],granularity='Line item with month and normalized unit',quality=['clean','raw','poor','clean'][len(ncountries)%4],topBrands=sorted(brands,key=lambda b:-b['valueEUR'])[:5],caveats=['Synthetic exercise; raw-record defects listed separately in quality-issues.json.']))
 for mo in range(1,9):monthly.append(dict(month=f'2026-{mo:02d}',iso=c['iso'],valueEUR=total([l for l in ls if l['month']==f'2026-{mo:02d}'],'valueEUR')))
refs=[dict(code=p['code'],name=p['name'],points=[dict(iso=c['iso'],priceEUR=prices[c['iso'],p['code']],basis='Synthetic net price per piece') for c in countries]) for p in products[:12]]
rfi=[]
for i,s in enumerate(suppliers):
 gtm=[dict(iso=c['iso'],market=c['name'],current='Direct' if (i+j)%3 else 'Distributor',possible='direct supply' if c['iso'] in s['countries'] else 'not offered') for j,c in enumerate(countries)]
 rfi.append(dict(name=s['name'],legalName=s['name']+' Demo Ltd.',hq='Fictional location: '+countries[i]['name'],categories=s['clusters'],directPossible=s['countries'],gtm=gtm))
deltas=[]
for p in refs:
 lo=min(p['points'],key=lambda x:x['priceEUR']);hi=max(p['points'],key=lambda x:x['priceEUR']);qty=next(s['totalQty'] for s in specs if s['code']==p['code'])
 deltas.append(dict(label=p['name'],code=p['code'],qtyYear=qty,worstEUR=hi['priceEUR'],worstIso=hi['iso'],bestEUR=lo['priceEUR'],bestIso=lo['iso'],potentialEUR=money((hi['priceEUR']-lo['priceEUR'])*qty),note='January-August 2026 scenario: observed period quantity at the lowest synthetic unit price; no annual extrapolation or savings promise.'))
bonus=[dict(iso=c['iso'],name=c['name'],ratePct=rate,spendEUR=c['totalEUR'],bonusEUR=money(c['totalEUR']*rate/100)) for c in ncountries for rate in [r.choice([1.2,1.8,2.4,3.1])]]
insights=[dict(de='Invoice lines require matching to the effective price version and pack unit.',en='Invoice lines require matching to the effective price version and pack unit.',kind='finding'),dict(de='Missing article codes remain in the human review queue.',en='Missing article codes remain in the human review queue.',kind='gap'),dict(de='All commercial data is synthetic and is not evidence of real supplier performance.',en='All business data is synthetic and is not evidence of real supplier performance.',kind='risk')]
colors=['#fbc343','#05b0b1','#dc91b3','#7659a1','#302d2d','#666666']
emit('nullmessung.ts',dict(nullmessungMeta=dict(files=len(countries),countries=len(countries),rows=len(lines),languages=sorted(set(c['language'] for c in countries)),currencies=sorted(set(l['currency'] for l in lines)),totalEUR=total(lines,'valueEUR'),fxNote='Synthetic fixed model exchange rates; see dataset/fx-rates.json',generated='18 September 2026'),rawSamples=[dict(iso=l['iso'],raw=f'{l["productCode"]} | {l["description"]} | {l["brand"]}',brand=l['brand'],readAs=l['description'],valueEUR=l['valueEUR'],currency=l['currency'],valueLocal=l['valueLocal']) for l in [lines[0],lines[336],lines[1008],lines[2016]]],monthlyVolumes=monthly,monthlyCoverage=[dict(iso=c['iso'],name=c['name'],mode='monthly',note='Complete synthetic period: January-August 2026.') for c in countries],nullmessungCountries=ncountries,refProducts=refs,rfiSuppliers=rfi,nullmessungInsights=insights,agentFeed=[dict(ts=f'2026-09-18T{9+i:02d}:15:00Z',channel=['email','dashboard','teams'][i],kind=['new-data','anomaly','quality'][i],de=x['de'],en=x['en'],action='Review synthetic record') for i,x in enumerate(insights)],deltaRows=deltas,priceIndex=[dict(iso=c['iso'],name=c['name'],factor=round(statistics.mean(prices[c['iso'],p['code']]/min(prices[g['iso'],p['code']] for g in countries) for p in products[:12]),2),articles=12) for c in countries],priceBenchmark=dict(iso='AT',name='Austria',wins=sum(min(p['points'],key=lambda x:x['priceEUR'])['iso']=='AT' for p in refs),articles=len(refs)),priceStatements=[dict(de='Synthetic prices are normalized net values per piece.',en='Synthetic prices are normalized net values per piece.')],priceIndexNote='Fictional comparison within the same unit; no market-price research.',deltaSummary=dict(totalEUR=total(deltas,'potentialEUR'),note='Illustrative upper-bound scenario, not realized savings.'),bonusRows=bonus,bonusTotalEUR=total(bonus,'bonusEUR'),bonusNote='Synthetic bonus assumptions by market.',BRAND_COLORS={s['name']:colors[i%len(colors)] for i,s in enumerate(suppliers)},SUPPLIER_PALETTE=colors,OTHER_COLOR='#666666'),'''export const brandColor=(brand:string):string=>BRAND_COLORS[brand]??OTHER_COLOR;
export const fmtEURk=(v:number):string=>v>=1000000?`${(v/1000000).toLocaleString('en-GB',{maximumFractionDigits:2})} million EUR`:`${(v/1000).toLocaleString('en-GB',{maximumFractionDigits:1})} thousand EUR`;''')
# Supplier matrix and scores derived from the same synthetic RFI offers.
matrix=[dict(iso=c['iso'],name=c['name'],cells=[dict(supplier=s['name'],route='direct' if c['iso'] in s['countries'] else 'indirect',verbatim='Synthetic RFI response: direct model offered' if c['iso'] in s['countries'] else 'Synthetic RFI response: distributor required',current=next(x['current'] for x in rfi[i]['gtm'] if x['iso']==c['iso'])) for i,s in enumerate(suppliers)]) for c in countries]
scores=[]
for s in suppliers:
 n=len(s['countries']);p=s['offers'];cat=len(s['clusters']);pc=round(100*p/len(products));cc=round(100*cat/len(clusters));dc=round(100*n/len(countries))
 scores.append(dict(name=s['name'],legalName=s['name']+' Demo Ltd.',warehouses='Fictional lab distribution',categoriesPct=cc,categoriesN=cat,coveragePct=100,coverageN=len(countries),directPct=dc,directN=n,pricePct=pc,priceN=p,priceTotal=len(products),avgPct=round((cc+100+dc+pc)/4),caveatsN=1,plus=['Synthetic offer includes versioned prices'],minus=['Performance not validated in real operations']))
emit('bewertung.ts',dict(bewertungMeta=dict(suppliers=[s['name'] for s in suppliers],nMarkets=len(countries),nCategories=len(clusters),nRefPrices=len(products)),matrixRows=matrix,matrixSums={s['name']:len(s['countries']) for s in suppliers},scoreRows=sorted(scores,key=lambda x:-x['avgPct'])))
baskets=[];pareto=[];routes=[];months=[]
for c in countries:
 ls=bycountry[c['iso']];v=total(ls,'valueEUR');ms=[l for l in ls if l['matched']];mv=total(ms,'valueEUR')
 baskets.append(dict(iso=c['iso'],name=c['name'],totalEUR=v,matchedEUR=mv,matchedLines=len(ms),sharePct=round(mv/v*100,1)))
 vs=sorted([total([l for l in ls if l['productCode']==p['code']],'valueEUR') for p in products],reverse=True);cum=0;n80=0
 for x in vs:
  cum+=x;n80+=1
  if cum>=v*.8:break
 pareto.append(dict(iso=c['iso'],name=c['name'],nCodes=len(products),n80=n80,top10Pct=round(sum(vs[:10])/v*100,1)))
 direct=total([l for l in ls if l['route']=='direct'],'valueEUR');routes.append(dict(iso=c['iso'],name=c['name'],totalEUR=v,directEUR=direct,directPct=round(direct/v*100,1),directBrands=sorted(set(l['brand'] for l in ls if l['route']=='direct')),topDistributors=[dict(name='Würth',valueEUR=money(v-direct))]))
 points=[dict(month=m['month'],valueEUR=m['valueEUR']) for m in monthly if m['iso']==c['iso']];median=statistics.median(p['valueEUR'] for p in points);peak=max(points,key=lambda p:p['valueEUR']);months.append(dict(iso=c['iso'],name=c['name'],points=points,medianEUR=median,peakMonth=peak['month'],peakFactor=round(peak['valueEUR']/median,2)))
matched=total([l for l in lines if l['matched']],'valueEUR')
emit('tiefenanalyse.ts',dict(taMeta=dict(stand='18 September 2026',basis=f'Synthetic data: {len(lines)} lines, {len(products)} items, {len(suppliers)} suppliers',totalEUR=total(lines,'valueEUR'),matchedEUR=matched,matchedSharePct=round(matched/total(lines,'valueEUR')*100,1),gtinFilled=len(products),offerArticles=len(products)),kernzahlen=[dict(value=str(len(lines)),label='Synthetic purchase lines',note='Entirely generated from the documented random seed.'),dict(value=f'{round(matched/total(lines,"valueEUR")*100)} %',label='Matched basket',note='Matched using the synthetic product key.'),dict(value=str(len(offers)),label='Offer versions',note='Three successive versions per offered item.')],basketRows=baskets,paretoRows=pareto,routeRows=routes,monthRows=months,monthCoverageNotes={c['iso']:'January-August 2026, entirely synthetic.' for c in countries},regeln=[dict(wenn='Invoice price differs from the effective agreement',dann='Check price version and pack unit; document the decision.',kind='lever'),dict(wenn='Item code or agreed price missing',dann='Request human review; do not report savings.',kind='gap')],monitorRows=[dict(alarm='Price variance',metrik='Net price per normalized piece',quelle='synthetic-invoices.json / offer-versions.json',sofort=True),dict(alarm='Record quality',metrik='Missing or conflicting fields',quelle='quality-issues.json',sofort=False)],sichtRows=[dict(iso=c['iso'],name=c['name'],suppliersVisible=len(set(l['supplierId'] for l in bycountry[c['iso']])),files=1) for c in countries],grenzen=['Commercial values, supplier relationships and records are synthetic; supplier names are real references.','No real supplier assessment or price recommendation.','Raw-record defects must be checked before aggregation.']))
hubs=[dict(id='HUB-N',name='Wolf northern logistics hub',country='AT',countryName='Austria',deliversTo=['AT','CZ','SK','SI','HR'],surchargeByTarget={'AT':.026,'CZ':.073,'SK':.061,'SI':.082,'HR':.095,'HUB-S':.057},source='synthetic_email',note='Synthetic network model; surcharges are exercise parameters.'),dict(id='HUB-S',name='Wolf southern logistics hub',country='HU',countryName='Hungary',deliversTo=['HU','RO','BG','RS','AL','ME'],surchargeByTarget={},surchargeFlat=.067,source='synthetic_email',note='Synthetic network model with a flat surcharge.')]
emit('lieferlinie.ts',dict(COUNTRY_NAMES={c['iso']:c['name'] for c in countries},domesticWarehouses=[dict(country=c['iso'],countryName=c['name'],domesticOnly=True,source='synthetic_email',note='Fictional domestic warehouse; check capacity in the pilot.') for c in countries if c['iso'] in ['IT','PT','SE','FR']],hubs=hubs,inCountryParams=dict(logistikpauschale=dict(min=.015,max=.065,default=.038,rangeSource='synthetic_email',defaultSource='annahme',label='Logistics fee',note='Synthetic scenario assumption.'),grosshandelsmarge=dict(min=.07,max=.21,default=.14,rangeSource='synthetic_email',defaultSource='annahme',label='Distribution margin',note='Synthetic scenario assumption.')),supplierG2M=[dict(supplier=s['name'],date='2026-09-10',directMarkets=s['countries'],viaWarehouse=[c['iso'] for c in countries if c['iso'] not in s['countries']][:3],viaDistributor=[c['iso'] for c in countries if c['iso'] not in s['countries']][3:],logisticsContractOption='Fictional option: document material and logistics prices separately.',source='rfi_protokoll',notes='Synthetic RFI response; no actual manufacturer commitment.') for s in suppliers],referenceArticles=[dict(code=p['code'],name=p['name'],unit='piece',prices={x['iso']:x['priceEUR'] for x in p['points']},bestSourceCountry=min(p['points'],key=lambda x:x['priceEUR'])['iso'],priceSource='nullmessung') for p in refs],painPointHighlights=[dict(title='Record has no price version',detail='Reconciliation remains open without an effective date.',source='Synthetic invoice case INV-WLF-0006'),dict(title='Pack unit conflicts with the item master',detail='Normalize the unit before comparing prices.',source='Synthetic invoice case INV-WLF-0005')]),'''export const countryName=(iso:Iso2):string=>COUNTRY_NAMES[iso]??iso;
export const hubSurcharge=(hub:Hub,target:Iso2):number|undefined=>hub.surchargeByTarget[target]??hub.surchargeFlat;''')
repairs=[]
for ri,(id,title) in enumerate([('ktl','Prepare a new part'),('fueller','Sand a primed surface'),('finish','Refinish a surface')]):
 systems=[]
 for si,s in enumerate(suppliers[:5]):
  steps=[]
  for pi in range(3):
   p=products[(ri+pi*7)%len(products)];steps.append(dict(grit=['P180','P400','P800'][pi],product=p['name'],articleNo=p['code'],consumption=round(r.uniform(.2,1.3),2),unit='piece',priceEUR={iso:prices[iso,p['code']] for iso in ['AT','PT']},priceSource={'AT':'nullmessung','PT':'nullmessung'},timeMin=round(r.uniform(2,7),1)))
  systems.append(dict(supplier=s['name'],systemName=f'{s["name"]} demo process {ri+1}',chainSource='annahme',prozessQuelle='Synthetic process draft from Wolf Lab',setupMin=r.randint(2,6),status=dict(anleitung=['received','promised','requested'][si%3],produkte='promised',test='Synthetic pilot 09/2026'),steps=steps,note='Not a manufacturer instruction. Technically validate before real use.'))
 repairs.append(dict(id=id,title=title,subtitle='Synthetic standardized repair scenario',defaultVolume=24000+ri*7000,volumeMax=120000,volumeNote='Fictional annual volume for scenario comparison.',systems=systems))
emit('systemvergleich.ts',dict(DEFAULT_HOURLY_RATE=74,repairCases=repairs,SOURCE_LABEL=dict(nullmessung='Synthetic procurement',listenpreis_web='Synthetic reference price',hersteller_sop='Synthetic process draft',annahme='Demo assumption')),'''export function systemCosts(system:SupplierSystem,basis:PriceBasis,hourlyRate:number):SystemCosts {
const materialEUR=system.steps.reduce((s,st)=>s+st.consumption*st.priceEUR[basis],0);
const timeMin=system.steps.reduce((s,st)=>s+st.timeMin,0);const laborEUR=timeMin/60*hourlyRate;
return {materialEUR,timeMin,laborEUR,totalEUR:materialEUR+laborEUR};}''')
emit('produkte-recherche.ts',dict(dossiers=[dict(code=p['code'],title=p['neutral'],intro='Fictional offer characteristics for a technical review. No manufacturer research.',introEn='Fictional offer characteristics for a technical review. No manufacturer research.',entries=[dict(supplier=e['supplier'],product=e['product'],facts=[dict(text='Synthetic RFI statement: sample testing required.',source='rfi'),dict(text='Confirm pack unit and approval for use before awarding the contract.',source='rfi')]) for e in p['equivalents'] if e['filled']]) for p in specs[:3]],rechercheHinweis='All statements are synthetic RFI scenarios, not web research.'))
emit('live-intake.ts',dict(liveIntakeQueue=[dict(id=f'live-wolf-{i+1:03d}',iso=c['iso'],site=f'Wolf Atelier {c["name"]} {i+1:02d}',channel=['Voice','Photo','Delivery note','Voice + Photo'][i%4],language=c['language'],items=[dict(cluster=products[i]['cluster'],item=products[i]['name'],qty=f'{r.randint(18,96)} piece')],delayMs=7000+i*900) for i,c in enumerate(countries[:14])]))
emit('company-kennzahlen.ts',dict(companyKennzahlenQuelle='Synthetic Wolf company metrics, 18 September 2026'),'''import { company } from './platform';

export const companyKennzahlen:CompanyKennzahl[]=[
{id:'umsatz',label:'Revenue (fictional)',prev:16.3,curr:company.umsatzMrdEUR,fmt:v=>`${v.toLocaleString('en-GB')} billion EUR`},
{id:'neuwagen',label:'New vehicles (fictional)',prev:261400,curr:company.neuwagen2025,fmt:v=>v.toLocaleString('en-GB')},
{id:'standorte',label:'Sites (fictional)',prev:company.standorte-23,curr:company.standorte,fmt:v=>v.toLocaleString('en-GB')},
{id:'mitarbeiter',label:'Employees (fictional)',prev:17620,curr:company.mitarbeiter,fmt:v=>v.toLocaleString('en-GB')}];''')
emit('vertraege-extras.ts',dict(pilotRatings=[dict(iso=c['iso'],stars=4+i%2,dimension=['Delivery time','Quality','Submission channel'][i%3],quote='Synthetic pilot feedback: the match was traceable; the pack unit required clarification.') for i,c in enumerate(countries[:6])],pilotRatingsContractId='ctr-novex'),'''import type {Contract,Training} from './platform';

import {countryByIso,trainingById} from './platform';

export const pilotRatingAvg=pilotRatings.reduce((sum,r)=>sum+r.stars,0)/pilotRatings.length;
export const trainingPackageFor=(contract:Contract):TrainingPackage=>{
const participants=contract.countries.reduce((sum,iso)=>sum+(countryByIso(iso)?.bodyShops??0),0)*4;
const rates:Record<Training['format'],number>={Video:75,Roleplay:125,'Video + Roleplay':165};
const items=contract.trainingCommitments.flatMap(c=>{const t=trainingById(c.trainingId);return t?[{trainingId:t.id,title:t.title,format:t.format,ratePerParticipantEUR:rates[t.format],volumeEUR:participants*rates[t.format]*contract.termYears}]:[]});
return {participants,termYears:contract.termYears,items,totalEUR:items.reduce((s,i)=>s+i.volumeEUR,0)};};''')
emit('ki-kontext.ts',dict(internalSupplyChain={h['id']:dict(country=h['country'],deliversTo=h['deliversTo'],surcharges=h['surchargeByTarget'],note=h['note']) for h in hubs}),'''import {contracts} from './platform';
import {produktSpecs} from './produkte';
import {nullmessungMeta,nullmessungInsights} from './nullmessung';

export function buildKiKontext():string{return 'WOLF MATERIALS LAB. All commercial data is synthetic. No real company records or manufacturer commitments. '+JSON.stringify({meta:nullmessungMeta,insights:nullmessungInsights,products:produktSpecs,contracts,network:internalSupplyChain});}''')
# New workflow: PDF-like invoice payloads, price versions, review events, and known quality defects.
invoices=[];events=[];issues=[]
for i,o in enumerate([o for o in offers if o['version']==3][:36]):
 qty=r.randint(8,140);case=i%6;agreed=o['priceEUR'];billed=money(agreed*(1.17 if case==1 else .94 if case==2 else 1));inv=f'INV-WLF-{i+1:04d}';iso=countries[i%len(countries)]['iso'];amount=money(qty*billed)
 invoices.append(dict(id=inv,iso=iso,supplierId=o['supplierId'],date=f'2026-09-{8+i%10:02d}',sourceFile='invoice-text/'+inv+'.txt',synthetic=True,currency='EUR',format='text_invoice',lines=[dict(lineNo=1,productCode=None if case==3 else o['productCode'],description=next(p['name'] for p in products if p['code']==o['productCode']),qty=qty,unit='pack' if case==4 else 'piece',packQuantity=None if case==4 else 1,unitPriceEUR=billed,netEUR=amount)],netEUR=amount,vatPct=20,vatEUR=money(amount*.2),grossEUR=money(amount*1.2),agreementId=None if case==5 else o['id'],expectedOutcome=['matched','overcharge_review','below_agreement_review','missing_article_review','unit_review','missing_agreement_review'][case],agreedUnitPriceEUR=None if case==5 else agreed,expectedVarianceEUR=money(qty*(billed-agreed)) if case in [0,1,2] else None))
 for j,event in enumerate(['received','extracted','matched' if case==0 else 'review_required']):events.append(dict(id=f'EVT-{i+1:04d}-{j}',invoiceId=inv,at=f'2026-09-{8+i%10:02d}T10:{j*4:02d}:00Z',event=event,actor='Synthetic intake agent' if j<2 else 'Synthetic review queue',note='Simulated workflow, no actual message.'))
 if case:issues.append(dict(id=f'ISS-{i+1:04d}',invoiceId=inv,kind=invoices[-1]['expectedOutcome'],severity='review',status='open',sourceFile='invoice-text/'+inv+'.txt',synthetic=True))
# Four ingestion update modes: no old private files are distributed.
lineage=[];raw_versions={}
for i,(iso,mode,description) in enumerate([('XK','replace_market','New supplier-sourced market delivery supersedes v1'),('IT','replace_market','Revised two-sheet market delivery supersedes v1'),('HU','add_supplier','New supplier delivery appends without deleting existing suppliers'),('FR','replace_supplier_subset','Repaired supplier subset supersedes invalid v1 rows')]):
 source=bycountry[iso][:24]
 if iso=='FR': source=[l for l in bycountry[iso] if l['supplierId']=='sup-aster'][:24]
 old=[];new=[]
 for j,l in enumerate(source):
  row=dict(l);row['iso']=iso;row['id']=f'{iso}-LATEST-{j+1:04d}';row['supplierId']='sup-orbit' if iso=='HU' else l['supplierId'];row['brand']=next(s['name'] for s in suppliers if s['id']==row['supplierId']);new.append(row)
  prior=dict(row);prior['id']=f'{iso}-PREVIOUS-{j+1:04d}';prior['unitPriceEUR']=money(r.uniform(4,80));prior['valueEUR']=money(prior['qty']*prior['unitPriceEUR']);prior['valueLocal']=money(prior['valueEUR']*fx[prior['currency']]);old.append(prior)
 if iso=='HU':
  for row in old:row['supplierId']='sup-aster';row['brand']='3M'
 unaffected=[]
 if iso=='FR':
  for j,l in enumerate([l for l in bycountry[iso] if l['supplierId']!='sup-aster'][:8]):
   row=dict(l);row['id']=f'FR-UNCHANGED-{j+1:04d}';unaffected.append(row)
  old+=unaffected
 if iso=='FR':
  for j,row in enumerate(new):
   if j%11==0:
    row['qty']=-row['qty'];row['valueEUR']=-row['valueEUR'];row['valueLocal']=-row['valueLocal']
 current=old+new if mode=='add_supplier' else (unaffected+new if mode=='replace_supplier_subset' else new)
 raw_versions[iso]=dict(v1=old,v2=new,current=current)
 lineage.append(dict(id=f'UPD-{iso}-002',market=iso,mode=mode,previous=f'{iso}-v1',incoming=f'{iso}-v2',effectiveDate='2026-09-01',sourceDate='2026-09-01',description='Synthetic scenario: '+description,scopeSupplierId='sup-orbit' if iso=='HU' else ('sup-aster' if iso=='FR' else None),previousRows=len(old),incomingRows=len(new),currentRows=len(raw_versions[iso]['current']),provenance='Newly generated fixtures, no original values or files.'))
for name,value in [('transactions',lines),('products',products),('suppliers',suppliers),('countries',countries),('offer-versions',offers),('synthetic-invoices',invoices),('workflow-events',events),('quality-issues',issues),('fx-rates',fx),('update-lineage',lineage),('ingestion-versions',raw_versions),('ui-exports',modules)]:dump(DATA/(name+'.json'),value)
dump(PUBLIC/'nullmessung-lines.json',public)
with (DATA/'transactions.csv').open('w',newline='') as f:
 writer=csv.DictWriter(f,fieldnames=list(lines[0]));writer.writeheader();writer.writerows(lines)
dump(DATA/'manifest.json',dict(synthetic=True,seed=9182029,generatedAsOf='2026-09-18',client='Wolf Automotive (fictional)',period='2026-01 through 2026-08',currencies=fx,counts=dict(countries=len(countries),suppliers=len(suppliers),products=len(products),transactions=len(lines),offerVersions=len(offers),invoices=len(invoices)),aggregateEUR=total(lines,'valueEUR'),source='kit/scripts/generate.py',limitations=['Commercial values and relationships are synthetic; supplier names and the technical reference catalogue are source-backed.','Ingestion version exercises are separate from the clean canonical UI ledger; do not sum them into transactions.','Invoice payloads are JSON representations; separate PDF fixtures may be added.','Reference part descriptions are translated into English; no real invoices, prices, agreements or validated supplier offers are included.']))
print(f'Generated {len(lines)} transactions, {len(products)} products, {len(invoices)} invoices, {len(modules)} UI modules; EUR {total(lines,"valueEUR"):,.2f}.')
# Row-major JSON preserves duplicate headers and grouped/blank rows without spreadsheet software.
raw_sheets={}
hu_headers=['Brand','Supplier Code','Manufacturer Code','Item description','Unit','Quantity','Selling Price/Unit (Ft)']
raw_sheets['HU-v2']={'Sheet1':[hu_headers]+[[l['brand'],f'ORB-{j+1:04d}',l['productCode'],l['description'],'PC',l['qty'],money(l['unitPriceEUR']*fx['HUF'])] for j,l in enumerate(raw_versions['HU']['v2'])]}
xk=[['']*21,['']*21,['','Wolf Kosovo 2026']+['']*19,['','','Date ','Quantity  ','Unit ','Price ','Total ','VAT','Total excl. VAT']+['']*12]
for j,l in enumerate(raw_versions['XK']['v2']):
 if j%8==0:xk.append([j+1,l['description'],'','','','','',.18,'']+['']*12)
 net=l['valueEUR'];vat=money(net*.18);xk.append([j+1,'',46023+j,l['qty'],'PC',money(l['unitPriceEUR']*1.18),money(net+vat),vat,net]+['']*12)
raw_sheets['XK-v2']={'Report':xk}
it1=['Company','Order no.','Sub','Order type','Order type','Position','PE','Code','Description','Gross position','Net position','PA','PV','Quantity',"Internal operation abbreviation",'Order category']
it2=['Company','Order no.','Sub','Order Type','Order Type','','','Product ID','Description','Gross position','Net position','Purchasing price','Sales price','Quantity','Internal operation abbreviation','Order Category']
raw_sheets['IT-v2']={}
for si,sheet in enumerate(['MA CARR','MA VERN']):
 raw_sheets['IT-v2'][sheet]=[it1,it2]+[[f'WOLF-{si+1}',f'ORD-IT-{j+1:05d}',1,'Order','Demo supply','RC','',l['productCode'],l['description'],money(l['valueEUR']*1.22),l['valueEUR'],l['unitPriceEUR'],money(l['unitPriceEUR']*1.1),l['qty'],sheet,'Demo purchase'] for j,l in enumerate(raw_versions['IT']['v2']) if j%2==si]
frh=['Site code','SITE','Invoice date','Invoice total','Currency','Invoice','Article','Description','Invoiced quantity','Quantity unit','Net value','Currency','Item','Invoice','Item','Product group code','Item type code','SA code','Sales document','Document date','Invoice type code',"Ordering party",'Payer','Created by','Commercial document type code','Billing category code','Commercial document type','Invoice category','Invoice type','Region','District',"Purchase order no.",'Order date','Payer']
fr=[frh]
fl=raw_versions['FR']['v2']
for j,l in enumerate(fl):
 group=j//3;group_lines=fl[group*3:group*3+3];signed=[x['valueEUR'] for x in group_lines];net=l['valueEUR'];fid=f'FAC-WOLF-{group+1:04d}'
 fr.append([f'SITE-{group+1:03d}',f'Wolf Atelier France {group+1}',46270+group,money(sum(signed)),'EUR',fid,l['productCode'],l['description'],l['qty'],'PC',net,'EUR',(j%3+1)*10,fid,j+1,'DEMO','NORM','LAB',f'VENTE-{group+1:04d}',46268+group,'CREDIT_NOTE' if net<0 else 'INVOICE','Wolf Automotive','Wolf France','Demo Agent','M','L','Invoice cancellation' if net<0 else 'Invoice','Synthetic delivery','Credit note' if net<0 else 'Standard invoice','FR-LAB','DIST-LAB',f'ACHAT-{group+1:04d}',46265+group,'WOLF-PAYEUR-001'])
raw_sheets['FR-v2']={'Sheet1':fr}
dump(DATA/'input-sheets.json',raw_sheets)
dump(DATA/'input-schema.json',dict(format='Row-major matrices preserve header positions, duplicate names and blank/group rows; all header text is translated into English.',files={'HU-v2':dict(columns=7,headerRow=1,notes='Add supplier; localized HUF unit prices.'),'XK-v2':dict(columns=21,headerRow=4,notes='Replace market; grouped product headers and Excel serial dates, gross/VAT/net.'),'IT-v2':dict(columns=16,headerRows=[1,2],notes='Replace market; two sheets, two English header rows, duplicate order-type columns.'),'FR-v2':dict(columns=34,headerRow=1,notes='Replace supplier subset; repeated invoice totals, negative cancellations, repeated payer/invoice fields. Sum line net, never repeated invoice totals.')},synthetic=True))
gold=[dict(invoiceId=i['id'],lineNo=1,productCode=i['lines'][0]['productCode'],netEUR=i['lines'][0]['netEUR'],agreementId=i['agreementId'],expectedOutcome=i['expectedOutcome'],expectedVarianceEUR=i['expectedVarianceEUR']) for i in invoices]
dump(DATA/'invoice-gold.json',gold)
(DATA/'invoice-text').mkdir(exist_ok=True)
for i in invoices:
 l=i['lines'][0];(DATA/'invoice-text'/f'{i["id"]}.txt').write_text(f'SYNTHETIC WOLF LAB INVOICE\nInvoice: {i["id"]}\nDate: {i["date"]}\nSupplier: {i["supplierId"]}\nCustomer: Wolf Automotive (fictional)\nCountry: {i["iso"]}\nArticle: {l["productCode"] or "MISSING"}\nDescription: {l["description"]}\nQuantity: {l["qty"]} {l["unit"]}\nUnit price EUR: {l["unitPriceEUR"]:.2f}\nNet EUR: {i["netEUR"]:.2f}\nVAT EUR: {i["vatEUR"]:.2f}\nGross EUR: {i["grossEUR"]:.2f}\nAgreement: {i["agreementId"] or "NOT PROVIDED"}\n')

# Portable CSV forms of raw sheets and actual files for each transaction source reference.
(DATA/'input-sheets').mkdir(exist_ok=True)
for book, sheets in raw_sheets.items():
 for name, rows in sheets.items():
  with (DATA/'input-sheets'/f'{book}--{name}.csv').open('w',newline='') as f:
   csv.writer(f).writerows(rows)
for iso, rows in bycountry.items():
 with (DATA/f'synthetic-spend-{iso}.csv').open('w',newline='') as f:
  w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
