export type MaturityLevel = 1 | 2 | 3 | 4 | 5;
export type Region = 'Austria' | 'Northern Europe' | 'Central and Eastern Europe' | 'Southwestern Europe' | 'Asia' | 'South America';
export interface Country {
    iso: string;
    name: string;
    region: Region;
    lat: number;
    lon: number;
    language: string;
    dealers: number;
    bodyShops: number;
    entryYear: number;
    revenueEUR: number;
    submissions: number;
    submissionTarget: number;
    maturity: MaturityLevel;
    intakeStatus: 'live' | 'in progress' | 'pending';
    topDemands: string[];
    supplyDependency: string;
}
export interface SortimentItem {
    nr: number;
    cluster: string;
    kategorie: string;
    artikel: string;
    spezifikation: string;
    einheit: string;
    prioritaet: 1 | 2 | 3;
    marken: string;
    anmerkung?: string;
}
export interface MaterialCluster {
    id: string;
    name: string;
    description: string;
    positions: number;
    spendEUR: number;
    savingPotentialPct: number;
    exampleItems: string[];
}
export interface Supplier {
    id: string;
    name: string;
    type: 'Manufacturer' | 'Distributor';
    countries: string[];
    clusters: string[];
    offers: number;
    matchScore: number;
    priceDeltaPct: number;
    logisticsSavingEUR: number;
    status: 'submitted' | 'under review' | 'shortlist';
}
export interface MaturityDimension {
    id: string;
    name: string;
    description: string;
}
export interface MaturityProfile {
    iso: string;
    scores: Record<string, number>;
    gaps: string[];
}
export interface Training {
    id: string;
    title: string;
    format: 'Video' | 'Roleplay' | 'Video + Roleplay';
    duration: string;
    cluster: string;
    dimension: string;
    languages: string[];
    description: string;
    completions: number;
    avgScore: number;
    autoGenerated: boolean;
}
export interface RoleplayScenario {
    id: string;
    trainingId: string;
    title: string;
    persona: string;
    goal: string;
    phases: string[];
    language: string;
}
export interface IntakeSubmission {
    id: string;
    iso: string;
    site: string;
    channel: 'Voice' | 'Photo' | 'Delivery note' | 'Voice + Photo';
    language: string;
    timestamp: string;
    items: {
        cluster: string;
        item: string;
        qtyPerMonth: string;
        note?: string;
    }[];
    painPoints: string[];
    status: 'structured' | 'processing';
}
export type ContractStage = 'Build' | 'Negotiate' | 'Agree';
export interface Contract {
    id: string;
    supplierId: string;
    title: string;
    clusters: string[];
    countries: string[];
    volumeEUR: number;
    termYears: number;
    stage: ContractStage;
    progressPct: number;
    negotiatedSavingPct: number;
    openPoints: string[];
    trainingCommitments: {
        trainingId: string;
        scope: string;
    }[];
    maturityGate: {
        dimension: string;
        target: number;
        note: string;
    };
    nextMilestone: string;
}
