'use client';

import type { RoleplayScenario } from 'src/data/platform';

import { useState, Suspense } from 'react';
import { varAlpha } from 'minimal-shared/utils';

import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import Chip from '@mui/material/Chip';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';

import { paths } from 'src/routes/paths';
import { RouterLink } from 'src/routes/components';
import { useRouter, useSearchParams } from 'src/routes/hooks';

import { DashboardContent } from 'src/layouts/dashboard';
import {
  company,
  contracts,
  countries,
  trainings,
  countryByIso,
  trainingById,
  maturityProfiles,
  roleplayScenarios,
  maturityDimensions,
} from 'src/data/platform';

import { Label } from 'src/components/label';
import { Iconify } from 'src/components/iconify';

import { VideoStudio } from './video-studio';
import { RoleplayDialog } from './roleplay-dialog';

// ----------------------------------------------------------------------


const MAX_GAP_CHIPS = 6;

const FORMAT_ICON: Record<string, React.ComponentProps<typeof Iconify>['icon']> = {
  Video: 'solar:videocamera-record-bold',
  Roleplay: 'solar:microphone-bold',
  'Video + Roleplay': 'solar:video-frame-play-horizontal-bold',
};

const SOURCE_STEPS = [
  {
    icon: 'solar:inbox-in-bold',
    module: 'Demand intake',
    title: 'Reveals gaps',
    text: 'Incorrect use and knowledge gaps become visible in workshop intake submissions.',
    href: paths.dashboard.erhebung,
    label: 'Open demand intake',
  },
  {
    icon: 'eva:trending-up-fill',
    module: 'Maturity',
    title: 'Prioritises',
    text: 'The five-dimension model shows which training has the greatest impact in each country.',
    href: paths.dashboard.reifegrad,
    label: 'View maturity',
  },
  {
    icon: 'solar:file-check-bold-duotone',
    module: 'Contracting',
    title: 'Makes training mandatory',
    text: 'Training commitments and maturity gates are part of each framework agreement.',
    href: paths.dashboard.vertraege,
    label: 'View contracts',
  },
] as const;


const STUDIO_VIDEO_TRAINING_IDS = new Set(['t-basis', 't-psa']);


const toStars = (score: number) => score / 20;

const formatStars = (stars: number) =>
  stars.toLocaleString('en-GB', { minimumFractionDigits: 1, maximumFractionDigits: 1 });

const dimensionName = (id: string) => maturityDimensions.find((d) => d.id === id)?.name ?? id;

// ----------------------------------------------------------------------

type StarRatingProps = {
  value: number; // 0..5
  size?: number;
};

function StarRating({ value, size = 16 }: StarRatingProps) {
  return (
    <Box component="span" sx={{ display: 'inline-flex', alignItems: 'center', gap: 0.25 }}>
      {[1, 2, 3, 4, 5].map((step) => {
        const filled = step <= Math.round(value);
        return (
          <Iconify
            key={step}
            width={size}
            icon={filled ? 'eva:star-fill' : 'eva:star-outline'}
            sx={{ color: filled ? 'warning.main' : 'text.disabled' }}
          />
        );
      })}
    </Box>
  );
}

// ----------------------------------------------------------------------

type SectionTitleProps = {
  title: string;
  subtitle?: string;
};


function SectionTitle({ title, subtitle }: SectionTitleProps) {
  return (
    <Box sx={{ mb: 3 }}>
      <Typography
        variant="h5"
        sx={{ color: 'primary.main', textTransform: 'uppercase', letterSpacing: 0.5 }}
      >
        {title}
      </Typography>
      <Box sx={{ mt: 1, height: 3, width: 1, bgcolor: 'primary.main' }} />
      {subtitle && (
        <Typography variant="body2" sx={{ mt: 1.5, color: 'text.secondary' }}>
          {subtitle}
        </Typography>
      )}
    </Box>
  );
}

// ----------------------------------------------------------------------


export function AcademyView() {
  return (
    <Suspense fallback={null}>
      <AcademyViewContent />
    </Suspense>
  );
}

function AcademyViewContent() {
  const [activeScenario, setActiveScenario] = useState<RoleplayScenario | null>(null);
  const [dialogOpen, setDialogOpen] = useState(false);

  const router = useRouter();
  const searchParams = useSearchParams();

  
  const marktParam = searchParams.get('markt');
  const filterCountry = marktParam ? countryByIso(marktParam.toUpperCase()) : undefined;
  const filterIso = filterCountry?.iso ?? null;

  const clearMarketFilter = () => {
    router.replace(paths.dashboard.academy);
  };

  
  const totalCompletions = trainings.reduce((s, t) => s + t.completions, 0);
  const avgScore = Math.round(trainings.reduce((s, t) => s + t.avgScore, 0) / trainings.length);
  const avgStars = toStars(avgScore);
  const autoGenerated = trainings.filter((t) => t.autoGenerated).length;

  
  const contractedTrainingIds = new Set(
    contracts.flatMap((c) => c.trainingCommitments.map((tc) => tc.trainingId))
  );

  
  
  const catalog = trainings
    .map((training) => ({
      training,
      gapMarkets: maturityProfiles
        .filter((profile) => profile.gaps.includes(training.id))
        .map((profile) => profile.iso),
    }))
    .sort((a, b) => b.gapMarkets.length - a.gapMarkets.length);

  
  const visibleCatalog = filterIso
    ? catalog.filter(({ gapMarkets }) => gapMarkets.includes(filterIso))
    : catalog;

  const kpis: {
    label: string;
    value: string;
    icon: React.ComponentProps<typeof Iconify>['icon'];
    hint: string;
    stars?: number;
  }[] = [
    { label: 'Active training', value: trainings.length.toLocaleString('en-GB'), icon: 'solar:video-frame-play-horizontal-bold', hint: 'Video & Voice-Roleplay' },
    { label: 'Completed sessions', value: totalCompletions.toLocaleString('en-GB'), icon: 'solar:check-circle-bold', hint: `across all ${countries.length.toLocaleString('en-GB')} Markets` },
    { label: 'Average rating', value: `${formatStars(avgStars)} / 5`, icon: 'solar:cup-star-bold', hint: 'Workshop ratings and knowledge checks', stars: avgStars },
    { label: 'Automatically generated', value: `${autoGenerated}/${trainings.length}`, icon: 'solar:atom-bold-duotone', hint: 'generated from tender data' },
  ];

  const startRoleplay = (scenario: RoleplayScenario) => {
    setActiveScenario(scenario);
    setDialogOpen(true);
  };

  const scrollToVideoStudio = () => {
    document.getElementById('video-studio')?.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    <DashboardContent maxWidth="xl">
      <Box sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
        
        <Card sx={{ p: { xs: 3, md: 5 } }}>
          <Typography variant="overline" sx={{ color: 'text.disabled' }}>
            Learning platform · Luxury car manufacturer (fictional)
          </Typography>
          <Typography
            variant="h3"
            sx={{ mt: 1, color: 'primary.main', textTransform: 'uppercase', letterSpacing: 0.5 }}
          >
            Academy: learn where the gap is
          </Typography>
          <Box sx={{ mt: 1.5, height: 4, width: 1, bgcolor: 'primary.main' }} />
          <Typography variant="body1" sx={{ mt: 2, maxWidth: 720, color: 'text.secondary' }}>
            Planned capability: generate videos and voice roleplay from tender data in the
            language of each market. Contractual training is directly
            linked.
          </Typography>
          <Typography variant="body2" sx={{ mt: 1, maxWidth: 720, color: 'text.secondary' }}>
            The academy connects to fictional staff development for technical and management careers,
            providing training for {company.mitarbeiter.toLocaleString('en-GB')} employees across{' '}
            {company.standorte.toLocaleString('en-GB')} locations.
          </Typography>
          <Box sx={{ mt: 3, display: 'flex', gap: 1.5, flexWrap: 'wrap' }}>
            <Button
              component={RouterLink}
              href={paths.dashboard.reifegrad}
              variant="contained"
              color="primary"
              sx={{ borderRadius: 5, px: 2.5 }}
              endIcon={<Iconify icon="eva:arrow-forward-fill" />}
            >
              Maturity per Country
            </Button>
            <Button
              component={RouterLink}
              href={paths.dashboard.vertraege}
              variant="outlined"
              color="inherit"
              sx={{ borderRadius: 5, px: 2.5 }}
              endIcon={<Iconify icon="eva:arrow-forward-fill" />}
            >
              Contractual training
            </Button>
          </Box>
        </Card>

        
        <Box
          sx={{
            gap: 3,
            display: 'grid',
            gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, 1fr)', md: 'repeat(4, 1fr)' },
          }}
        >
          {kpis.map((kpi) => (
            <Card key={kpi.label} sx={{ p: 3, display: 'flex', alignItems: 'flex-start', gap: 2 }}>
              <Box sx={{ flexGrow: 1 }}>
                <Typography variant="overline" sx={{ color: 'text.secondary' }}>
                  {kpi.label}
                </Typography>
                <Typography variant="h3">{kpi.value}</Typography>
                {kpi.stars != null && (
                  <Box sx={{ mb: 0.5 }}>
                    <StarRating value={kpi.stars} size={18} />
                  </Box>
                )}
                <Typography variant="caption" sx={{ color: 'text.disabled' }}>
                  {kpi.hint}
                </Typography>
              </Box>
              <Iconify icon={kpi.icon} width={28} sx={{ color: 'text.disabled', mt: 0.5 }} />
            </Card>
          ))}
        </Box>

        
        <VideoStudio />

        
        <Box>
          <SectionTitle
            title="Training catalogue"
            subtitle={`${trainings.length.toLocaleString('en-GB')} Training prioritised by maturity gaps across ${countries.length.toLocaleString('en-GB')} markets. Orange indicates contractual training.`}
          />

          
          {filterCountry && (
            <Box sx={{ mb: 3, display: 'flex', alignItems: 'center', gap: 1.5, flexWrap: 'wrap' }}>
              <Chip
                color="primary"
                variant="filled"
                icon={<Iconify icon="ic:round-filter-list" width={18} />}
                label={`Filtered: recommended for ${filterCountry.name}`}
                onDelete={clearMarketFilter}
              />
              <Typography variant="caption" sx={{ color: 'text.secondary' }}>
                {visibleCatalog.length.toLocaleString('en-GB')} from{' '}
                {catalog.length.toLocaleString('en-GB')} training courses derived from the
                market maturity gaps
              </Typography>
            </Box>
          )}

          {filterCountry && visibleCatalog.length === 0 && (
            <Card sx={{ p: 3, mb: 3, display: 'flex', alignItems: 'center', gap: 1.5 }}>
              <Iconify icon="solar:check-circle-bold" width={24} sx={{ color: 'success.main' }} />
              <Typography variant="body2" sx={{ color: 'text.secondary' }}>
                For {filterCountry.name} currently has no open training needs: all
                maturity dimensions exceed the threshold.
              </Typography>
            </Card>
          )}

          <Box
            sx={{
              gap: 3,
              display: 'grid',
              gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, 1fr)', md: 'repeat(3, 1fr)' },
            }}
          >
            {visibleCatalog.map(({ training, gapMarkets }) => {
              const contracted = contractedTrainingIds.has(training.id);
              const scenario = roleplayScenarios.find((s) => s.trainingId === training.id);
              const hasStudioVideo = STUDIO_VIDEO_TRAINING_IDS.has(training.id);

              return (
                <Card
                  key={training.id}
                  sx={{
                    p: 3,
                    display: 'flex',
                    flexDirection: 'column',
                    gap: 1.5,
                    ...(contracted && { borderTop: '3px solid', borderColor: 'primary.main' }),
                  }}
                >
                  <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, flexWrap: 'wrap' }}>
                    <Label
                      variant="soft"
                      color="secondary"
                      startIcon={<Iconify icon={FORMAT_ICON[training.format] ?? 'solar:play-circle-bold'} />}
                    >
                      {training.format}
                    </Label>
                    <Label variant="outlined" color="default">
                      {dimensionName(training.dimension)}
                    </Label>
                    <Box sx={{ flexGrow: 1 }} />
                    <Typography variant="caption" sx={{ color: 'text.secondary', display: 'inline-flex', alignItems: 'center', gap: 0.5 }}>
                      <Iconify icon="solar:clock-circle-outline" width={14} />
                      {training.duration}
                    </Typography>
                  </Box>

                  <Typography variant="subtitle1">{training.title}</Typography>
                  <Typography variant="body2" sx={{ color: 'text.secondary', flexGrow: 1 }}>
                    {training.description}
                  </Typography>

                  <Box sx={{ display: 'flex', gap: 0.5, flexWrap: 'wrap' }}>
                    {training.languages.map((lang) => (
                      <Label key={lang} variant="soft" color="default" sx={{ minWidth: 32 }}>
                        {lang}
                      </Label>
                    ))}
                  </Box>

                  
                  <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.75, flexWrap: 'wrap' }}>
                    {gapMarkets.length > 0 ? (
                      <>
                        <Typography variant="caption" sx={{ color: 'text.secondary' }}>
                          Recommended for:
                        </Typography>
                        {gapMarkets.slice(0, MAX_GAP_CHIPS).map((iso) => (
                          // ISO-Chip = Deep-Link auf denselben Marktfilter
                          <Box
                            key={iso}
                            component={RouterLink}
                            href={`${paths.dashboard.academy}?markt=${iso}`}
                            sx={{ textDecoration: 'none', display: 'inline-flex' }}
                          >
                            <Label
                              variant="soft"
                              color="primary"
                              sx={{ minWidth: 32, cursor: 'pointer' }}
                            >
                              {iso}
                            </Label>
                          </Box>
                        ))}
                        {gapMarkets.length > MAX_GAP_CHIPS && (
                          <Label variant="soft" color="default" sx={{ minWidth: 32 }}>
                            +{gapMarkets.length - MAX_GAP_CHIPS}
                          </Label>
                        )}
                      </>
                    ) : (
                      <Label
                        variant="soft"
                        color="success"
                        startIcon={<Iconify icon="solar:check-circle-bold" />}
                      >
                        No open gap
                      </Label>
                    )}
                  </Box>

                  <Box
                    sx={(theme) => ({
                      pt: 1.5,
                      gap: 1,
                      display: 'flex',
                      flexWrap: 'wrap',
                      alignItems: 'center',
                      borderTop: `1px dashed ${theme.vars.palette.divider}`,
                    })}
                  >
                    <Typography variant="caption" sx={{ color: 'text.secondary', display: 'inline-flex', alignItems: 'center', gap: 0.5 }}>
                      <Iconify icon="solar:users-group-rounded-bold" width={14} />
                      {training.completions.toLocaleString('en-GB')} Sessions
                    </Typography>
                    <Box sx={{ display: 'inline-flex', alignItems: 'center', gap: 0.5 }}>
                      <StarRating value={toStars(training.avgScore)} size={14} />
                      <Typography variant="caption" sx={{ fontWeight: 600 }}>
                        {formatStars(toStars(training.avgScore))}
                      </Typography>
                    </Box>
                    {training.autoGenerated && (
                      <Label variant="soft" color="info">
                        AI-generated
                      </Label>
                    )}
                    {contracted && (
                      <Box
                        component={RouterLink}
                        href={paths.dashboard.vertraege}
                        sx={{ textDecoration: 'none', display: 'inline-flex' }}
                      >
                        <Label
                          variant="soft"
                          color="primary"
                          startIcon={<Iconify icon="solar:verified-check-bold" />}
                          sx={{ cursor: 'pointer' }}
                        >
                          Contractually agreed
                        </Label>
                      </Box>
                    )}
                  </Box>

                  {(scenario || hasStudioVideo) && (
                    <Box sx={{ pt: 0.5, display: 'flex', gap: 1, flexWrap: 'wrap' }}>
                      {scenario ? (
                        <Button
                          size="small"
                          variant="outlined"
                          color="inherit"
                          sx={{ borderRadius: 5, px: 2 }}
                          startIcon={<Iconify icon="solar:microphone-bold" />}
                          onClick={() => startRoleplay(scenario)}
                        >
                          Start training
                        </Button>
                      ) : (
                        <Button
                          size="small"
                          variant="outlined"
                          color="inherit"
                          sx={{ borderRadius: 5, px: 2 }}
                          startIcon={<Iconify icon="solar:play-circle-bold" />}
                          onClick={scrollToVideoStudio}
                        >
                          Start training
                        </Button>
                      )}
                      {scenario && hasStudioVideo && (
                        <Button
                          size="small"
                          variant="outlined"
                          color="inherit"
                          sx={{ borderRadius: 5, px: 2 }}
                          startIcon={<Iconify icon="solar:play-circle-bold" />}
                          onClick={scrollToVideoStudio}
                        >
                          View video
                        </Button>
                      )}
                    </Box>
                  )}
                </Card>
              );
            })}
          </Box>
        </Box>

        
        <Box>
          <SectionTitle
            title="Voice roleplay scenarios"
            subtitle="The voice assistant plays a role so you can practise the conversation in English."
          />

          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
            {roleplayScenarios.map((scenario) => {
              const training = trainingById(scenario.trainingId);

              return (
                <Card
                  key={scenario.id}
                  sx={{
                    p: 3,
                    gap: 2,
                    display: 'flex',
                    flexDirection: { xs: 'column', md: 'row' },
                    alignItems: { md: 'center' },
                  }}
                >
                  <Box
                    sx={(theme) => ({
                      width: 48,
                      height: 48,
                      flexShrink: 0,
                      display: 'grid',
                      placeItems: 'center',
                      borderRadius: '50%',
                      color: 'primary.main',
                      bgcolor: varAlpha(theme.vars.palette.primary.mainChannel, 0.08),
                    })}
                  >
                    <Iconify icon="solar:microphone-bold" width={24} />
                  </Box>

                  <Box sx={{ flexGrow: 1, minWidth: 0 }}>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, flexWrap: 'wrap' }}>
                      <Typography variant="subtitle1">{scenario.title}</Typography>
                      <Label variant="soft" color="default">
                        {scenario.language}
                      </Label>
                      {training && (
                        <Typography variant="caption" sx={{ color: 'text.disabled' }}>
                          Training: {training.title}
                        </Typography>
                      )}
                    </Box>
                    <Typography variant="body2" sx={{ mt: 0.5, color: 'text.secondary' }}>
                      {scenario.persona} — Goal: {scenario.goal}
                    </Typography>
                    <Box sx={{ mt: 1, display: 'flex', gap: 0.75, flexWrap: 'wrap' }}>
                      {scenario.phases.map((phase, idx) => (
                        <Label key={phase} variant="outlined" color="default">
                          {idx + 1}. {phase}
                        </Label>
                      ))}
                    </Box>
                  </Box>

                  <Button
                    variant="outlined"
                    color="inherit"
                    sx={{ borderRadius: 5, px: 2.5, flexShrink: 0, alignSelf: { xs: 'flex-start', md: 'center' } }}
                    startIcon={<Iconify icon="solar:microphone-bold" />}
                    onClick={() => {
                      setActiveScenario(scenario);
                      setDialogOpen(true);
                    }}
                  >
                    Start scenario
                  </Button>
                </Card>
              );
            })}
          </Box>
        </Box>

        
        <Box>
          <SectionTitle title="How training is selected" />
          <Box
            sx={{
              gap: 3,
              display: 'grid',
              gridTemplateColumns: { xs: '1fr', md: 'repeat(3, 1fr)' },
            }}
          >
            {SOURCE_STEPS.map((step) => (
              <Card
                key={step.title}
                component={RouterLink}
                href={step.href}
                sx={{
                  p: 3,
                  display: 'flex',
                  flexDirection: 'column',
                  gap: 1,
                  textDecoration: 'none',
                  color: 'inherit',
                  transition: (theme) => theme.transitions.create('box-shadow'),
                  '&:hover': { boxShadow: (theme) => theme.customShadows?.z16 ?? theme.shadows[16] },
                }}
              >
                <Typography variant="overline" sx={{ color: 'text.disabled' }}>
                  {step.module}
                </Typography>
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
                  <Iconify icon={step.icon} width={24} sx={{ color: 'secondary.main' }} />
                  <Typography variant="subtitle1">{step.title}</Typography>
                </Box>
                <Typography variant="body2" sx={{ color: 'text.secondary', flexGrow: 1 }}>
                  {step.text}
                </Typography>
                <Typography
                  variant="caption"
                  sx={{ color: 'primary.main', fontWeight: 600, display: 'inline-flex', alignItems: 'center', gap: 0.5 }}
                >
                  {step.label}
                  <Iconify icon="eva:arrow-forward-fill" width={14} />
                </Typography>
              </Card>
            ))}
          </Box>
        </Box>

        
        <Box sx={{ mt: 2, display: 'flex', alignItems: 'center', gap: 1 }}>
          <Box sx={{ width: 10, height: 10, flexShrink: 0, bgcolor: 'primary.main' }} />
          <Typography variant="caption" sx={{ color: 'text.disabled' }}>
            Synthetic hackathon demo · Luxury car manufacturer (fictional) — Materials tender Body and paint
          </Typography>
        </Box>
      </Box>

      <RoleplayDialog
        open={dialogOpen}
        scenario={activeScenario}
        onClose={() => setDialogOpen(false)}
      />
    </DashboardContent>
  );
}
