// Synthetic Wolf Materials Lab data. Generated by kit/scripts/generate.py. No real commercial records.
export type MatrixCell = {
    supplier: string;
    route: 'direct' | 'indirect' | 'none';
    verbatim: string;
    current: string;
};
export type MatrixRow = {
    iso: string;
    name: string;
    cells: MatrixCell[];
};
export type ScoreRow = {
    name: string;
    legalName: string;
    warehouses: string;
    categoriesPct: number;
    categoriesN: number;
    coveragePct: number;
    coverageN: number;
    directPct: number;
    directN: number;
    pricePct: number;
    priceN: number;
    priceTotal: number;
    avgPct: number;
    caveatsN: number;
    plus: string[];
    minus: string[];
};

export const bewertungMeta = {
  "suppliers": [
    "3M",
    "Glasurit (BASF)",
    "Finixa",
    "Mirka",
    "SATA",
    "tesa",
    "PPG / Nexa",
    "Würth",
    "Kovax",
    "Starcke"
  ],
  "nMarkets": 29,
  "nCategories": 7,
  "nRefPrices": 21
};
export const matrixRows: MatrixRow[] = [
  {
    "iso": "AT",
    "name": "Austria",
    "cells": [
      {
        "supplier": "3M",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Distributor"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Würth",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      }
    ]
  },
  {
    "iso": "DE",
    "name": "Germany",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      }
    ]
  },
  {
    "iso": "SE",
    "name": "Sweden",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "tesa",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      }
    ]
  },
  {
    "iso": "FR",
    "name": "France",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "SATA",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      }
    ]
  },
  {
    "iso": "IT",
    "name": "Italy",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Mirka",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      }
    ]
  },
  {
    "iso": "ES",
    "name": "Spain",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Finixa",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Starcke",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      }
    ]
  },
  {
    "iso": "PT",
    "name": "Portugal",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Kovax",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      }
    ]
  },
  {
    "iso": "CH",
    "name": "Switzerland",
    "cells": [
      {
        "supplier": "3M",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Würth",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      }
    ]
  },
  {
    "iso": "PL",
    "name": "Poland",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      }
    ]
  },
  {
    "iso": "CZ",
    "name": "Czechia",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "tesa",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      }
    ]
  },
  {
    "iso": "SK",
    "name": "Slovakia",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "SATA",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      }
    ]
  },
  {
    "iso": "HU",
    "name": "Hungary",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Mirka",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      }
    ]
  },
  {
    "iso": "SI",
    "name": "Slovenia",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Finixa",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Starcke",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Distributor"
      }
    ]
  },
  {
    "iso": "HR",
    "name": "Croatia",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Kovax",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Distributor"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      }
    ]
  },
  {
    "iso": "RO",
    "name": "Romania",
    "cells": [
      {
        "supplier": "3M",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Würth",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Distributor"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      }
    ]
  },
  {
    "iso": "BG",
    "name": "Bulgaria",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Distributor"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      }
    ]
  },
  {
    "iso": "RS",
    "name": "Serbia",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "tesa",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Distributor"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      }
    ]
  },
  {
    "iso": "BA",
    "name": "Bosnia and Herzegovina",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "SATA",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Distributor"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      }
    ]
  },
  {
    "iso": "AL",
    "name": "Albania",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Mirka",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Distributor"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      }
    ]
  },
  {
    "iso": "MK",
    "name": "North Macedonia",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Finixa",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Distributor"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Starcke",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      }
    ]
  },
  {
    "iso": "ME",
    "name": "Montenegro",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Distributor"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Kovax",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      }
    ]
  },
  {
    "iso": "UA",
    "name": "Ukraine",
    "cells": [
      {
        "supplier": "3M",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Distributor"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Würth",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      }
    ]
  },
  {
    "iso": "CN",
    "name": "China",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      }
    ]
  },
  {
    "iso": "JP",
    "name": "Japan",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "tesa",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      }
    ]
  },
  {
    "iso": "MY",
    "name": "Malaysia",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "SATA",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      }
    ]
  },
  {
    "iso": "SG",
    "name": "Singapore",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Mirka",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      }
    ]
  },
  {
    "iso": "CL",
    "name": "Chile",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Finixa",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Starcke",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      }
    ]
  },
  {
    "iso": "CO",
    "name": "Colombia",
    "cells": [
      {
        "supplier": "3M",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Würth",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Kovax",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      }
    ]
  },
  {
    "iso": "XK",
    "name": "Kosovo",
    "cells": [
      {
        "supplier": "3M",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "Glasurit (BASF)",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Finixa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Mirka",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "SATA",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "tesa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "PPG / Nexa",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      },
      {
        "supplier": "Würth",
        "route": "indirect",
        "verbatim": "Synthetic RFI response: distributor required",
        "current": "Direct"
      },
      {
        "supplier": "Kovax",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Distributor"
      },
      {
        "supplier": "Starcke",
        "route": "direct",
        "verbatim": "Synthetic RFI response: direct model offered",
        "current": "Direct"
      }
    ]
  }
];
export const matrixSums: Record<string, number> = {
  "3M": 24,
  "Glasurit (BASF)": 25,
  "Finixa": 25,
  "Mirka": 25,
  "SATA": 25,
  "tesa": 25,
  "PPG / Nexa": 25,
  "Würth": 24,
  "Kovax": 25,
  "Starcke": 25
};
export const scoreRows: ScoreRow[] = [
  {
    "name": "Glasurit (BASF)",
    "legalName": "Glasurit (BASF) Demo Ltd.",
    "warehouses": "Fictional lab distribution",
    "categoriesPct": 71,
    "categoriesN": 5,
    "coveragePct": 100,
    "coverageN": 29,
    "directPct": 86,
    "directN": 25,
    "pricePct": 71,
    "priceN": 15,
    "priceTotal": 21,
    "avgPct": 82,
    "caveatsN": 1,
    "plus": [
      "Synthetic offer includes versioned prices"
    ],
    "minus": [
      "Performance not validated in real operations"
    ]
  },
  {
    "name": "Finixa",
    "legalName": "Finixa Demo Ltd.",
    "warehouses": "Fictional lab distribution",
    "categoriesPct": 71,
    "categoriesN": 5,
    "coveragePct": 100,
    "coverageN": 29,
    "directPct": 86,
    "directN": 25,
    "pricePct": 71,
    "priceN": 15,
    "priceTotal": 21,
    "avgPct": 82,
    "caveatsN": 1,
    "plus": [
      "Synthetic offer includes versioned prices"
    ],
    "minus": [
      "Performance not validated in real operations"
    ]
  },
  {
    "name": "SATA",
    "legalName": "SATA Demo Ltd.",
    "warehouses": "Fictional lab distribution",
    "categoriesPct": 71,
    "categoriesN": 5,
    "coveragePct": 100,
    "coverageN": 29,
    "directPct": 86,
    "directN": 25,
    "pricePct": 71,
    "priceN": 15,
    "priceTotal": 21,
    "avgPct": 82,
    "caveatsN": 1,
    "plus": [
      "Synthetic offer includes versioned prices"
    ],
    "minus": [
      "Performance not validated in real operations"
    ]
  },
  {
    "name": "tesa",
    "legalName": "tesa Demo Ltd.",
    "warehouses": "Fictional lab distribution",
    "categoriesPct": 71,
    "categoriesN": 5,
    "coveragePct": 100,
    "coverageN": 29,
    "directPct": 86,
    "directN": 25,
    "pricePct": 71,
    "priceN": 15,
    "priceTotal": 21,
    "avgPct": 82,
    "caveatsN": 1,
    "plus": [
      "Synthetic offer includes versioned prices"
    ],
    "minus": [
      "Performance not validated in real operations"
    ]
  },
  {
    "name": "Kovax",
    "legalName": "Kovax Demo Ltd.",
    "warehouses": "Fictional lab distribution",
    "categoriesPct": 71,
    "categoriesN": 5,
    "coveragePct": 100,
    "coverageN": 29,
    "directPct": 86,
    "directN": 25,
    "pricePct": 71,
    "priceN": 15,
    "priceTotal": 21,
    "avgPct": 82,
    "caveatsN": 1,
    "plus": [
      "Synthetic offer includes versioned prices"
    ],
    "minus": [
      "Performance not validated in real operations"
    ]
  },
  {
    "name": "Würth",
    "legalName": "Würth Demo Ltd.",
    "warehouses": "Fictional lab distribution",
    "categoriesPct": 71,
    "categoriesN": 5,
    "coveragePct": 100,
    "coverageN": 29,
    "directPct": 83,
    "directN": 24,
    "pricePct": 71,
    "priceN": 15,
    "priceTotal": 21,
    "avgPct": 81,
    "caveatsN": 1,
    "plus": [
      "Synthetic offer includes versioned prices"
    ],
    "minus": [
      "Performance not validated in real operations"
    ]
  },
  {
    "name": "Mirka",
    "legalName": "Mirka Demo Ltd.",
    "warehouses": "Fictional lab distribution",
    "categoriesPct": 57,
    "categoriesN": 4,
    "coveragePct": 100,
    "coverageN": 29,
    "directPct": 86,
    "directN": 25,
    "pricePct": 57,
    "priceN": 12,
    "priceTotal": 21,
    "avgPct": 75,
    "caveatsN": 1,
    "plus": [
      "Synthetic offer includes versioned prices"
    ],
    "minus": [
      "Performance not validated in real operations"
    ]
  },
  {
    "name": "PPG / Nexa",
    "legalName": "PPG / Nexa Demo Ltd.",
    "warehouses": "Fictional lab distribution",
    "categoriesPct": 57,
    "categoriesN": 4,
    "coveragePct": 100,
    "coverageN": 29,
    "directPct": 86,
    "directN": 25,
    "pricePct": 57,
    "priceN": 12,
    "priceTotal": 21,
    "avgPct": 75,
    "caveatsN": 1,
    "plus": [
      "Synthetic offer includes versioned prices"
    ],
    "minus": [
      "Performance not validated in real operations"
    ]
  },
  {
    "name": "Starcke",
    "legalName": "Starcke Demo Ltd.",
    "warehouses": "Fictional lab distribution",
    "categoriesPct": 57,
    "categoriesN": 4,
    "coveragePct": 100,
    "coverageN": 29,
    "directPct": 86,
    "directN": 25,
    "pricePct": 57,
    "priceN": 12,
    "priceTotal": 21,
    "avgPct": 75,
    "caveatsN": 1,
    "plus": [
      "Synthetic offer includes versioned prices"
    ],
    "minus": [
      "Performance not validated in real operations"
    ]
  },
  {
    "name": "3M",
    "legalName": "3M Demo Ltd.",
    "warehouses": "Fictional lab distribution",
    "categoriesPct": 57,
    "categoriesN": 4,
    "coveragePct": 100,
    "coverageN": 29,
    "directPct": 83,
    "directN": 24,
    "pricePct": 57,
    "priceN": 12,
    "priceTotal": 21,
    "avgPct": 74,
    "caveatsN": 1,
    "plus": [
      "Synthetic offer includes versioned prices"
    ],
    "minus": [
      "Performance not validated in real operations"
    ]
  }
];


