// Synthetic Wolf Materials Lab data. Generated by kit/scripts/generate.py. No real commercial records.
export interface CompanyKennzahl {
    id: string;
    label: string;
    prev: number;
    curr: number;
    fmt: (v: number) => string;
}

export const companyKennzahlenQuelle = "Synthetic Wolf company metrics, 18 September 2026";

import { company } from './platform';

export const companyKennzahlen:CompanyKennzahl[]=[
{id:'umsatz',label:'Revenue (fictional)',prev:16.3,curr:company.umsatzMrdEUR,fmt:v=>`${v.toLocaleString('en-GB')} billion EUR`},
{id:'neuwagen',label:'New vehicles (fictional)',prev:261400,curr:company.neuwagen2025,fmt:v=>v.toLocaleString('en-GB')},
{id:'standorte',label:'Sites (fictional)',prev:company.standorte-23,curr:company.standorte,fmt:v=>v.toLocaleString('en-GB')},
{id:'mitarbeiter',label:'Employees (fictional)',prev:17620,curr:company.mitarbeiter,fmt:v=>v.toLocaleString('en-GB')}];
