// Synthetic Wolf Materials Lab data. Generated by kit/scripts/generate.py. No real commercial records.


export const internalSupplyChain = {
  "HUB-N": {
    "country": "AT",
    "deliversTo": [
      "AT",
      "CZ",
      "SK",
      "SI",
      "HR"
    ],
    "surcharges": {
      "AT": 0.026,
      "CZ": 0.073,
      "SK": 0.061,
      "SI": 0.082,
      "HR": 0.095,
      "HUB-S": 0.057
    },
    "note": "Synthetic network model; surcharges are exercise parameters."
  },
  "HUB-S": {
    "country": "HU",
    "deliversTo": [
      "HU",
      "RO",
      "BG",
      "RS",
      "AL",
      "ME"
    ],
    "surcharges": {},
    "note": "Synthetic network model with a flat surcharge."
  }
};

import {contracts} from './platform';
import {produktSpecs} from './produkte';
import {nullmessungMeta,nullmessungInsights} from './nullmessung';

export function buildKiKontext():string{return 'WOLF MATERIALS LAB. All commercial data is synthetic. No real company records or manufacturer commitments. '+JSON.stringify({meta:nullmessungMeta,insights:nullmessungInsights,products:produktSpecs,contracts,network:internalSupplyChain});}
