// Synthetic Wolf Materials Lab data. Generated by kit/scripts/generate.py. No real commercial records.
export type ValueSource = 'synthetic_email' | 'rfi_protokoll' | 'nullmessung' | 'annahme';
export type Iso2 = string;
export type DomesticWarehouse = {
    country: Iso2;
    countryName: string;
    domesticOnly: true;
    source: ValueSource;
    note: string;
};
export type Hub = {
    id: 'HUB-N' | 'HUB-S';
    name: string;
    country: Iso2;
    countryName: string;
    deliversTo: Iso2[];
    surchargeByTarget: Record<string, number>;
    surchargeFlat?: number;
    source: ValueSource;
    note: string;
};
export type RangeParam = {
    min: number;
    max: number;
    default: number;
    rangeSource: ValueSource;
    defaultSource: ValueSource;
    label: string;
    note: string;
};
export type InCountryParams = {
    logistikpauschale: RangeParam;
    grosshandelsmarge: RangeParam;
};
export type SupplierG2M = {
    supplier: string;
    date: string;
    directMarkets: Iso2[];
    viaWarehouse: Iso2[];
    viaDistributor: Iso2[];
    logisticsContractOption: string;
    source: ValueSource;
    notes: string;
};
export type ReferenceArticle = {
    code: string;
    name: string;
    unit: string;
    prices: Record<Iso2, number>;
    bestSourceCountry: Iso2;
    priceSource: ValueSource;
};
export type PainPointHighlight = {
    title: string;
    detail: string;
    source: string;
};

export const COUNTRY_NAMES: Record<Iso2, string> = {
  "AT": "Austria",
  "DE": "Germany",
  "SE": "Sweden",
  "FR": "France",
  "IT": "Italy",
  "ES": "Spain",
  "PT": "Portugal",
  "CH": "Switzerland",
  "PL": "Poland",
  "CZ": "Czechia",
  "SK": "Slovakia",
  "HU": "Hungary",
  "SI": "Slovenia",
  "HR": "Croatia",
  "RO": "Romania",
  "BG": "Bulgaria",
  "RS": "Serbia",
  "BA": "Bosnia and Herzegovina",
  "AL": "Albania",
  "MK": "North Macedonia",
  "ME": "Montenegro",
  "UA": "Ukraine",
  "CN": "China",
  "JP": "Japan",
  "MY": "Malaysia",
  "SG": "Singapore",
  "CL": "Chile",
  "CO": "Colombia",
  "XK": "Kosovo"
};
export const domesticWarehouses: DomesticWarehouse[] = [
  {
    "country": "SE",
    "countryName": "Sweden",
    "domesticOnly": true,
    "source": "synthetic_email",
    "note": "Fictional domestic warehouse; check capacity in the pilot."
  },
  {
    "country": "FR",
    "countryName": "France",
    "domesticOnly": true,
    "source": "synthetic_email",
    "note": "Fictional domestic warehouse; check capacity in the pilot."
  },
  {
    "country": "IT",
    "countryName": "Italy",
    "domesticOnly": true,
    "source": "synthetic_email",
    "note": "Fictional domestic warehouse; check capacity in the pilot."
  },
  {
    "country": "PT",
    "countryName": "Portugal",
    "domesticOnly": true,
    "source": "synthetic_email",
    "note": "Fictional domestic warehouse; check capacity in the pilot."
  }
];
export const hubs: Hub[] = [
  {
    "id": "HUB-N",
    "name": "Wolf northern logistics hub",
    "country": "AT",
    "countryName": "Austria",
    "deliversTo": [
      "AT",
      "CZ",
      "SK",
      "SI",
      "HR"
    ],
    "surchargeByTarget": {
      "AT": 0.026,
      "CZ": 0.073,
      "SK": 0.061,
      "SI": 0.082,
      "HR": 0.095,
      "HUB-S": 0.057
    },
    "source": "synthetic_email",
    "note": "Synthetic network model; surcharges are exercise parameters."
  },
  {
    "id": "HUB-S",
    "name": "Wolf southern logistics hub",
    "country": "HU",
    "countryName": "Hungary",
    "deliversTo": [
      "HU",
      "RO",
      "BG",
      "RS",
      "AL",
      "ME"
    ],
    "surchargeByTarget": {},
    "surchargeFlat": 0.067,
    "source": "synthetic_email",
    "note": "Synthetic network model with a flat surcharge."
  }
];
export const inCountryParams: InCountryParams = {
  "logistikpauschale": {
    "min": 0.015,
    "max": 0.065,
    "default": 0.038,
    "rangeSource": "synthetic_email",
    "defaultSource": "annahme",
    "label": "Logistics fee",
    "note": "Synthetic scenario assumption."
  },
  "grosshandelsmarge": {
    "min": 0.07,
    "max": 0.21,
    "default": 0.14,
    "rangeSource": "synthetic_email",
    "defaultSource": "annahme",
    "label": "Distribution margin",
    "note": "Synthetic scenario assumption."
  }
};
export const supplierG2M: SupplierG2M[] = [
  {
    "supplier": "3M",
    "date": "2026-09-10",
    "directMarkets": [
      "DE",
      "SE",
      "FR",
      "IT",
      "ES",
      "PT",
      "PL",
      "CZ",
      "SK",
      "HU",
      "SI",
      "HR",
      "BG",
      "RS",
      "BA",
      "AL",
      "MK",
      "ME",
      "CN",
      "JP",
      "MY",
      "SG",
      "CL",
      "CO"
    ],
    "viaWarehouse": [
      "AT",
      "CH",
      "RO"
    ],
    "viaDistributor": [
      "UA",
      "XK"
    ],
    "logisticsContractOption": "Fictional option: document material and logistics prices separately.",
    "source": "rfi_protokoll",
    "notes": "Synthetic RFI response; no actual manufacturer commitment."
  },
  {
    "supplier": "Glasurit (BASF)",
    "date": "2026-09-10",
    "directMarkets": [
      "AT",
      "DE",
      "SE",
      "FR",
      "IT",
      "ES",
      "CH",
      "PL",
      "CZ",
      "SK",
      "HU",
      "SI",
      "RO",
      "BG",
      "RS",
      "BA",
      "AL",
      "MK",
      "UA",
      "CN",
      "JP",
      "MY",
      "SG",
      "CL",
      "XK"
    ],
    "viaWarehouse": [
      "PT",
      "HR",
      "ME"
    ],
    "viaDistributor": [
      "CO"
    ],
    "logisticsContractOption": "Fictional option: document material and logistics prices separately.",
    "source": "rfi_protokoll",
    "notes": "Synthetic RFI response; no actual manufacturer commitment."
  },
  {
    "supplier": "Finixa",
    "date": "2026-09-10",
    "directMarkets": [
      "AT",
      "DE",
      "SE",
      "FR",
      "IT",
      "PT",
      "CH",
      "PL",
      "CZ",
      "SK",
      "HU",
      "HR",
      "RO",
      "BG",
      "RS",
      "BA",
      "AL",
      "ME",
      "UA",
      "CN",
      "JP",
      "MY",
      "SG",
      "CO",
      "XK"
    ],
    "viaWarehouse": [
      "ES",
      "SI",
      "MK"
    ],
    "viaDistributor": [
      "CL"
    ],
    "logisticsContractOption": "Fictional option: document material and logistics prices separately.",
    "source": "rfi_protokoll",
    "notes": "Synthetic RFI response; no actual manufacturer commitment."
  },
  {
    "supplier": "Mirka",
    "date": "2026-09-10",
    "directMarkets": [
      "AT",
      "DE",
      "SE",
      "FR",
      "ES",
      "PT",
      "CH",
      "PL",
      "CZ",
      "SK",
      "SI",
      "HR",
      "RO",
      "BG",
      "RS",
      "BA",
      "MK",
      "ME",
      "UA",
      "CN",
      "JP",
      "MY",
      "CL",
      "CO",
      "XK"
    ],
    "viaWarehouse": [
      "IT",
      "HU",
      "AL"
    ],
    "viaDistributor": [
      "SG"
    ],
    "logisticsContractOption": "Fictional option: document material and logistics prices separately.",
    "source": "rfi_protokoll",
    "notes": "Synthetic RFI response; no actual manufacturer commitment."
  },
  {
    "supplier": "SATA",
    "date": "2026-09-10",
    "directMarkets": [
      "AT",
      "DE",
      "SE",
      "IT",
      "ES",
      "PT",
      "CH",
      "PL",
      "CZ",
      "HU",
      "SI",
      "HR",
      "RO",
      "BG",
      "RS",
      "AL",
      "MK",
      "ME",
      "UA",
      "CN",
      "JP",
      "SG",
      "CL",
      "CO",
      "XK"
    ],
    "viaWarehouse": [
      "FR",
      "SK",
      "BA"
    ],
    "viaDistributor": [
      "MY"
    ],
    "logisticsContractOption": "Fictional option: document material and logistics prices separately.",
    "source": "rfi_protokoll",
    "notes": "Synthetic RFI response; no actual manufacturer commitment."
  },
  {
    "supplier": "tesa",
    "date": "2026-09-10",
    "directMarkets": [
      "AT",
      "DE",
      "FR",
      "IT",
      "ES",
      "PT",
      "CH",
      "PL",
      "SK",
      "HU",
      "SI",
      "HR",
      "RO",
      "BG",
      "BA",
      "AL",
      "MK",
      "ME",
      "UA",
      "CN",
      "MY",
      "SG",
      "CL",
      "CO",
      "XK"
    ],
    "viaWarehouse": [
      "SE",
      "CZ",
      "RS"
    ],
    "viaDistributor": [
      "JP"
    ],
    "logisticsContractOption": "Fictional option: document material and logistics prices separately.",
    "source": "rfi_protokoll",
    "notes": "Synthetic RFI response; no actual manufacturer commitment."
  },
  {
    "supplier": "PPG / Nexa",
    "date": "2026-09-10",
    "directMarkets": [
      "AT",
      "SE",
      "FR",
      "IT",
      "ES",
      "PT",
      "CH",
      "CZ",
      "SK",
      "HU",
      "SI",
      "HR",
      "RO",
      "RS",
      "BA",
      "AL",
      "MK",
      "ME",
      "UA",
      "JP",
      "MY",
      "SG",
      "CL",
      "CO",
      "XK"
    ],
    "viaWarehouse": [
      "DE",
      "PL",
      "BG"
    ],
    "viaDistributor": [
      "CN"
    ],
    "logisticsContractOption": "Fictional option: document material and logistics prices separately.",
    "source": "rfi_protokoll",
    "notes": "Synthetic RFI response; no actual manufacturer commitment."
  },
  {
    "supplier": "Würth",
    "date": "2026-09-10",
    "directMarkets": [
      "DE",
      "SE",
      "FR",
      "IT",
      "ES",
      "PT",
      "PL",
      "CZ",
      "SK",
      "HU",
      "SI",
      "HR",
      "BG",
      "RS",
      "BA",
      "AL",
      "MK",
      "ME",
      "CN",
      "JP",
      "MY",
      "SG",
      "CL",
      "CO"
    ],
    "viaWarehouse": [
      "AT",
      "CH",
      "RO"
    ],
    "viaDistributor": [
      "UA",
      "XK"
    ],
    "logisticsContractOption": "Fictional option: document material and logistics prices separately.",
    "source": "rfi_protokoll",
    "notes": "Synthetic RFI response; no actual manufacturer commitment."
  },
  {
    "supplier": "Kovax",
    "date": "2026-09-10",
    "directMarkets": [
      "AT",
      "DE",
      "SE",
      "FR",
      "IT",
      "ES",
      "CH",
      "PL",
      "CZ",
      "SK",
      "HU",
      "SI",
      "RO",
      "BG",
      "RS",
      "BA",
      "AL",
      "MK",
      "UA",
      "CN",
      "JP",
      "MY",
      "SG",
      "CL",
      "XK"
    ],
    "viaWarehouse": [
      "PT",
      "HR",
      "ME"
    ],
    "viaDistributor": [
      "CO"
    ],
    "logisticsContractOption": "Fictional option: document material and logistics prices separately.",
    "source": "rfi_protokoll",
    "notes": "Synthetic RFI response; no actual manufacturer commitment."
  },
  {
    "supplier": "Starcke",
    "date": "2026-09-10",
    "directMarkets": [
      "AT",
      "DE",
      "SE",
      "FR",
      "IT",
      "PT",
      "CH",
      "PL",
      "CZ",
      "SK",
      "HU",
      "HR",
      "RO",
      "BG",
      "RS",
      "BA",
      "AL",
      "ME",
      "UA",
      "CN",
      "JP",
      "MY",
      "SG",
      "CO",
      "XK"
    ],
    "viaWarehouse": [
      "ES",
      "SI",
      "MK"
    ],
    "viaDistributor": [
      "CL"
    ],
    "logisticsContractOption": "Fictional option: document material and logistics prices separately.",
    "source": "rfi_protokoll",
    "notes": "Synthetic RFI response; no actual manufacturer commitment."
  }
];
export const referenceArticles: ReferenceArticle[] = [
  {
    "code": "WLF-1001",
    "name": "Graduated mixing cup",
    "unit": "piece",
    "prices": {
      "AT": 20.75,
      "DE": 21.63,
      "SE": 22.52,
      "FR": 20.98,
      "IT": 30.22,
      "ES": 37.26,
      "PT": 39.86,
      "CH": 22.79,
      "PL": 27.59,
      "CZ": 23.51,
      "SK": 38.79,
      "HU": 32.77,
      "SI": 19.33,
      "HR": 28.87,
      "RO": 37.82,
      "BG": 18.97,
      "RS": 32.09,
      "BA": 15.88,
      "AL": 17.6,
      "MK": 26.45,
      "ME": 20.41,
      "UA": 18.14,
      "CN": 17.09,
      "JP": 35.19,
      "MY": 35.83,
      "SG": 31.91,
      "CL": 27.02,
      "CO": 21.15,
      "XK": 30.19
    },
    "bestSourceCountry": "BA",
    "priceSource": "nullmessung"
  },
  {
    "code": "WLF-1002",
    "name": "Sanding discs 150 mm, coarse",
    "unit": "piece",
    "prices": {
      "AT": 67.76,
      "DE": 86.68,
      "SE": 48.07,
      "FR": 101.54,
      "IT": 94.58,
      "ES": 74.66,
      "PT": 66.59,
      "CH": 117.26,
      "PL": 106.71,
      "CZ": 62.47,
      "SK": 114.81,
      "HU": 73.23,
      "SI": 115.45,
      "HR": 81.63,
      "RO": 115.14,
      "BG": 76.22,
      "RS": 45.9,
      "BA": 68.07,
      "AL": 46.45,
      "MK": 45.99,
      "ME": 51.04,
      "UA": 55.82,
      "CN": 68.0,
      "JP": 71.15,
      "MY": 104.46,
      "SG": 66.41,
      "CL": 90.78,
      "CO": 51.44,
      "XK": 102.42
    },
    "bestSourceCountry": "RS",
    "priceSource": "nullmessung"
  },
  {
    "code": "WLF-1003",
    "name": "Standard masking tape",
    "unit": "piece",
    "prices": {
      "AT": 29.47,
      "DE": 16.22,
      "SE": 15.77,
      "FR": 13.52,
      "IT": 20.42,
      "ES": 22.37,
      "PT": 22.96,
      "CH": 13.64,
      "PL": 31.16,
      "CZ": 13.09,
      "SK": 27.57,
      "HU": 14.42,
      "SI": 20.91,
      "HR": 29.43,
      "RO": 28.34,
      "BG": 23.73,
      "RS": 27.84,
      "BA": 26.46,
      "AL": 19.51,
      "MK": 17.59,
      "ME": 19.33,
      "UA": 13.52,
      "CN": 25.56,
      "JP": 26.56,
      "MY": 30.76,
      "SG": 25.97,
      "CL": 30.9,
      "CO": 21.42,
      "XK": 14.55
    },
    "bestSourceCountry": "CZ",
    "priceSource": "nullmessung"
  },
  {
    "code": "WLF-1004",
    "name": "Cutting compound (coarse/medium)",
    "unit": "piece",
    "prices": {
      "AT": 43.07,
      "DE": 41.49,
      "SE": 36.18,
      "FR": 21.36,
      "IT": 43.07,
      "ES": 33.98,
      "PT": 28.14,
      "CH": 31.68,
      "PL": 33.32,
      "CZ": 28.82,
      "SK": 32.25,
      "HU": 34.99,
      "SI": 39.05,
      "HR": 33.25,
      "RO": 17.65,
      "BG": 32.37,
      "RS": 41.89,
      "BA": 18.43,
      "AL": 18.88,
      "MK": 32.55,
      "ME": 41.25,
      "UA": 21.54,
      "CN": 25.29,
      "JP": 22.41,
      "MY": 19.32,
      "SG": 40.26,
      "CL": 22.73,
      "CO": 31.92,
      "XK": 36.59
    },
    "bestSourceCountry": "RO",
    "priceSource": "nullmessung"
  },
  {
    "code": "WLF-1005",
    "name": "Solvent-based silicone remover",
    "unit": "piece",
    "prices": {
      "AT": 35.4,
      "DE": 61.85,
      "SE": 61.62,
      "FR": 41.84,
      "IT": 47.27,
      "ES": 26.69,
      "PT": 31.41,
      "CH": 49.54,
      "PL": 25.66,
      "CZ": 63.55,
      "SK": 40.66,
      "HU": 45.66,
      "SI": 38.47,
      "HR": 30.56,
      "RO": 39.41,
      "BG": 59.56,
      "RS": 32.51,
      "BA": 52.86,
      "AL": 55.3,
      "MK": 51.88,
      "ME": 49.01,
      "UA": 53.56,
      "CN": 53.96,
      "JP": 45.77,
      "MY": 59.29,
      "SG": 63.15,
      "CL": 60.06,
      "CO": 55.88,
      "XK": 25.85
    },
    "bestSourceCountry": "PL",
    "priceSource": "nullmessung"
  },
  {
    "code": "WLF-1006",
    "name": "Half mask / spray-painting respirator",
    "unit": "piece",
    "prices": {
      "AT": 22.78,
      "DE": 28.08,
      "SE": 22.14,
      "FR": 25.58,
      "IT": 18.22,
      "ES": 28.06,
      "PT": 43.13,
      "CH": 40.58,
      "PL": 35.85,
      "CZ": 22.14,
      "SK": 25.05,
      "HU": 44.3,
      "SI": 44.09,
      "HR": 27.44,
      "RO": 21.63,
      "BG": 39.1,
      "RS": 30.4,
      "BA": 24.01,
      "AL": 32.54,
      "MK": 23.43,
      "ME": 42.37,
      "UA": 24.32,
      "CN": 42.87,
      "JP": 20.38,
      "MY": 20.08,
      "SG": 33.4,
      "CL": 30.71,
      "CO": 31.3,
      "XK": 30.13
    },
    "bestSourceCountry": "IT",
    "priceSource": "nullmessung"
  },
  {
    "code": "WLF-1007",
    "name": "Random orbital sander 150 mm, 5 mm orbit",
    "unit": "piece",
    "prices": {
      "AT": 39.59,
      "DE": 50.47,
      "SE": 64.69,
      "FR": 40.91,
      "IT": 51.38,
      "ES": 33.57,
      "PT": 30.86,
      "CH": 26.72,
      "PL": 35.64,
      "CZ": 49.98,
      "SK": 31.94,
      "HU": 50.52,
      "SI": 28.45,
      "HR": 52.0,
      "RO": 59.28,
      "BG": 40.64,
      "RS": 53.14,
      "BA": 47.13,
      "AL": 35.36,
      "MK": 34.78,
      "ME": 41.08,
      "UA": 40.18,
      "CN": 52.62,
      "JP": 28.78,
      "MY": 60.19,
      "SG": 43.79,
      "CL": 61.8,
      "CO": 58.87,
      "XK": 64.87
    },
    "bestSourceCountry": "CH",
    "priceSource": "nullmessung"
  },
  {
    "code": "WLF-1008",
    "name": "Paint cup for compressed-air spray gun",
    "unit": "piece",
    "prices": {
      "AT": 100.16,
      "DE": 48.89,
      "SE": 61.68,
      "FR": 50.16,
      "IT": 94.64,
      "ES": 72.23,
      "PT": 112.79,
      "CH": 50.4,
      "PL": 78.74,
      "CZ": 74.19,
      "SK": 84.12,
      "HU": 51.53,
      "SI": 100.28,
      "HR": 100.96,
      "RO": 100.14,
      "BG": 111.5,
      "RS": 49.5,
      "BA": 95.55,
      "AL": 53.15,
      "MK": 82.17,
      "ME": 99.67,
      "UA": 101.93,
      "CN": 102.33,
      "JP": 63.2,
      "MY": 104.48,
      "SG": 65.1,
      "CL": 57.8,
      "CO": 53.47,
      "XK": 52.02
    },
    "bestSourceCountry": "DE",
    "priceSource": "nullmessung"
  },
  {
    "code": "WLF-1009",
    "name": "Sanding discs 150 mm, intermediate",
    "unit": "piece",
    "prices": {
      "AT": 56.01,
      "DE": 70.49,
      "SE": 53.79,
      "FR": 65.79,
      "IT": 79.6,
      "ES": 68.45,
      "PT": 89.15,
      "CH": 41.63,
      "PL": 71.15,
      "CZ": 48.53,
      "SK": 42.67,
      "HU": 74.49,
      "SI": 55.83,
      "HR": 56.82,
      "RO": 56.58,
      "BG": 36.08,
      "RS": 51.02,
      "BA": 37.08,
      "AL": 54.39,
      "MK": 80.73,
      "ME": 37.77,
      "UA": 78.83,
      "CN": 35.07,
      "JP": 52.95,
      "MY": 70.81,
      "SG": 66.55,
      "CL": 37.38,
      "CO": 49.93,
      "XK": 59.84
    },
    "bestSourceCountry": "CN",
    "priceSource": "nullmessung"
  },
  {
    "code": "WLF-1010",
    "name": "Fine-line tape",
    "unit": "piece",
    "prices": {
      "AT": 17.67,
      "DE": 19.26,
      "SE": 13.05,
      "FR": 24.42,
      "IT": 22.49,
      "ES": 20.55,
      "PT": 17.16,
      "CH": 24.41,
      "PL": 16.11,
      "CZ": 14.93,
      "SK": 11.18,
      "HU": 26.76,
      "SI": 19.62,
      "HR": 17.22,
      "RO": 13.02,
      "BG": 12.51,
      "RS": 20.27,
      "BA": 17.01,
      "AL": 14.8,
      "MK": 22.22,
      "ME": 15.99,
      "UA": 24.93,
      "CN": 21.57,
      "JP": 17.7,
      "MY": 23.0,
      "SG": 26.18,
      "CL": 13.2,
      "CO": 27.98,
      "XK": 22.05
    },
    "bestSourceCountry": "SK",
    "priceSource": "nullmessung"
  },
  {
    "code": "WLF-1011",
    "name": "Polish (fine / anti-hologram)",
    "unit": "piece",
    "prices": {
      "AT": 12.95,
      "DE": 14.52,
      "SE": 14.61,
      "FR": 12.95,
      "IT": 6.97,
      "ES": 11.84,
      "PT": 11.74,
      "CH": 14.43,
      "PL": 11.79,
      "CZ": 9.16,
      "SK": 7.96,
      "HU": 14.04,
      "SI": 8.39,
      "HR": 12.9,
      "RO": 8.7,
      "BG": 6.79,
      "RS": 15.54,
      "BA": 14.33,
      "AL": 13.72,
      "MK": 6.89,
      "ME": 16.17,
      "UA": 11.26,
      "CN": 11.13,
      "JP": 8.11,
      "MY": 14.08,
      "SG": 12.91,
      "CL": 11.59,
      "CO": 12.02,
      "XK": 10.97
    },
    "bestSourceCountry": "BG",
    "priceSource": "nullmessung"
  },
  {
    "code": "WLF-1012",
    "name": "Water-based silicone remover",
    "unit": "piece",
    "prices": {
      "AT": 47.34,
      "DE": 47.38,
      "SE": 48.09,
      "FR": 29.39,
      "IT": 39.1,
      "ES": 37.31,
      "PT": 31.57,
      "CH": 47.07,
      "PL": 37.59,
      "CZ": 38.55,
      "SK": 43.85,
      "HU": 40.53,
      "SI": 19.77,
      "HR": 30.98,
      "RO": 31.91,
      "BG": 38.99,
      "RS": 40.96,
      "BA": 33.49,
      "AL": 27.06,
      "MK": 38.95,
      "ME": 34.18,
      "UA": 20.33,
      "CN": 20.15,
      "JP": 44.49,
      "MY": 42.68,
      "SG": 24.57,
      "CL": 30.65,
      "CO": 39.67,
      "XK": 47.21
    },
    "bestSourceCountry": "SI",
    "priceSource": "nullmessung"
  }
];
export const painPointHighlights: PainPointHighlight[] = [
  {
    "title": "Record has no price version",
    "detail": "Reconciliation remains open without an effective date.",
    "source": "Synthetic invoice case INV-WLF-0006"
  },
  {
    "title": "Pack unit conflicts with the item master",
    "detail": "Normalize the unit before comparing prices.",
    "source": "Synthetic invoice case INV-WLF-0005"
  }
];

export const countryName=(iso:Iso2):string=>COUNTRY_NAMES[iso]??iso;
export const hubSurcharge=(hub:Hub,target:Iso2):number|undefined=>hub.surchargeByTarget[target]??hub.surchargeFlat;
