// Synthetic Wolf Materials Lab data. Generated by kit/scripts/generate.py. No real commercial records.
export interface LiveIntakeItem {
    cluster: string;
    item: string;
    qty: string;
}
export interface LiveIntakeEntry {
    id: string;
    iso: string;
    site: string;
    channel: 'Voice' | 'Photo' | 'Delivery note' | 'Voice + Photo';
    language: string;
    items: LiveIntakeItem[];
    delayMs: number;
}

export const liveIntakeQueue: LiveIntakeEntry[] = [
  {
    "id": "live-wolf-001",
    "iso": "AT",
    "site": "Wolf Atelier Austria 01",
    "channel": "Voice",
    "language": "German",
    "items": [
      {
        "cluster": "lack",
        "item": "Graduated mixing cup",
        "qty": "60 piece"
      }
    ],
    "delayMs": 7000
  },
  {
    "id": "live-wolf-002",
    "iso": "DE",
    "site": "Wolf Atelier Germany 02",
    "channel": "Photo",
    "language": "German",
    "items": [
      {
        "cluster": "schleif",
        "item": "Sanding discs 150 mm, coarse",
        "qty": "57 piece"
      }
    ],
    "delayMs": 7900
  },
  {
    "id": "live-wolf-003",
    "iso": "SE",
    "site": "Wolf Atelier Sweden 03",
    "channel": "Delivery note",
    "language": "Swedish",
    "items": [
      {
        "cluster": "kleb",
        "item": "Standard masking tape",
        "qty": "68 piece"
      }
    ],
    "delayMs": 8800
  },
  {
    "id": "live-wolf-004",
    "iso": "FR",
    "site": "Wolf Atelier France 04",
    "channel": "Voice + Photo",
    "language": "French",
    "items": [
      {
        "cluster": "polier",
        "item": "Cutting compound (coarse/medium)",
        "qty": "25 piece"
      }
    ],
    "delayMs": 9700
  },
  {
    "id": "live-wolf-005",
    "iso": "IT",
    "site": "Wolf Atelier Italy 05",
    "channel": "Voice",
    "language": "Italian",
    "items": [
      {
        "cluster": "kabine",
        "item": "Solvent-based silicone remover",
        "qty": "72 piece"
      }
    ],
    "delayMs": 10600
  },
  {
    "id": "live-wolf-006",
    "iso": "ES",
    "site": "Wolf Atelier Spain 06",
    "channel": "Photo",
    "language": "Spanish",
    "items": [
      {
        "cluster": "psa",
        "item": "Half mask / spray-painting respirator",
        "qty": "27 piece"
      }
    ],
    "delayMs": 11500
  },
  {
    "id": "live-wolf-007",
    "iso": "PT",
    "site": "Wolf Atelier Portugal 07",
    "channel": "Delivery note",
    "language": "Portuguese",
    "items": [
      {
        "cluster": "werkstatt",
        "item": "Random orbital sander 150 mm, 5 mm orbit",
        "qty": "90 piece"
      }
    ],
    "delayMs": 12400
  },
  {
    "id": "live-wolf-008",
    "iso": "CH",
    "site": "Wolf Atelier Switzerland 08",
    "channel": "Voice + Photo",
    "language": "German / French",
    "items": [
      {
        "cluster": "lack",
        "item": "Paint cup for compressed-air spray gun",
        "qty": "56 piece"
      }
    ],
    "delayMs": 13300
  },
  {
    "id": "live-wolf-009",
    "iso": "PL",
    "site": "Wolf Atelier Poland 09",
    "channel": "Voice",
    "language": "Polish",
    "items": [
      {
        "cluster": "schleif",
        "item": "Sanding discs 150 mm, intermediate",
        "qty": "23 piece"
      }
    ],
    "delayMs": 14200
  },
  {
    "id": "live-wolf-010",
    "iso": "CZ",
    "site": "Wolf Atelier Czechia 10",
    "channel": "Photo",
    "language": "Czech",
    "items": [
      {
        "cluster": "kleb",
        "item": "Fine-line tape",
        "qty": "62 piece"
      }
    ],
    "delayMs": 15100
  },
  {
    "id": "live-wolf-011",
    "iso": "SK",
    "site": "Wolf Atelier Slovakia 11",
    "channel": "Delivery note",
    "language": "Slovak",
    "items": [
      {
        "cluster": "polier",
        "item": "Polish (fine / anti-hologram)",
        "qty": "65 piece"
      }
    ],
    "delayMs": 16000
  },
  {
    "id": "live-wolf-012",
    "iso": "HU",
    "site": "Wolf Atelier Hungary 12",
    "channel": "Voice + Photo",
    "language": "Hungarian",
    "items": [
      {
        "cluster": "kabine",
        "item": "Water-based silicone remover",
        "qty": "39 piece"
      }
    ],
    "delayMs": 16900
  },
  {
    "id": "live-wolf-013",
    "iso": "SI",
    "site": "Wolf Atelier Slovenia 13",
    "channel": "Voice",
    "language": "Slovenian",
    "items": [
      {
        "cluster": "psa",
        "item": "A2 filter cartridges",
        "qty": "40 piece"
      }
    ],
    "delayMs": 17800
  },
  {
    "id": "live-wolf-014",
    "iso": "HR",
    "site": "Wolf Atelier Croatia 14",
    "channel": "Photo",
    "language": "Croatian",
    "items": [
      {
        "cluster": "werkstatt",
        "item": "Random orbital sander 77 mm",
        "qty": "42 piece"
      }
    ],
    "delayMs": 18700
  }
];


