// Synthetic Wolf Materials Lab data. Generated by kit/scripts/generate.py. No real commercial records.
export type MaturityLevel = 1 | 2 | 3 | 4 | 5;
export type Region = 'Austria' | 'Northern Europe' | 'Central and Eastern Europe' | 'Southwestern Europe' | 'Asia' | 'South America';
export interface Country {
    iso: string;
    name: string;
    region: Region;
    lat: number;
    lon: number;
    language: string;
    dealers: number;
    bodyShops: number;
    entryYear: number;
    revenueEUR: number;
    submissions: number;
    submissionTarget: number;
    maturity: MaturityLevel;
    intakeStatus: 'live' | 'in progress' | 'pending';
    topDemands: string[];
    supplyDependency: string;
}
export interface SortimentItem {
    nr: number;
    cluster: string;
    kategorie: string;
    artikel: string;
    spezifikation: string;
    einheit: string;
    prioritaet: 1 | 2 | 3;
    marken: string;
    anmerkung?: string;
}
export interface MaterialCluster {
    id: string;
    name: string;
    description: string;
    positions: number;
    spendEUR: number;
    savingPotentialPct: number;
    exampleItems: string[];
}
export interface Supplier {
    id: string;
    name: string;
    type: 'Manufacturer' | 'Distributor';
    countries: string[];
    clusters: string[];
    offers: number;
    matchScore: number;
    priceDeltaPct: number;
    logisticsSavingEUR: number;
    status: 'submitted' | 'under review' | 'shortlist';
}
export interface MaturityDimension {
    id: string;
    name: string;
    description: string;
}
export interface MaturityProfile {
    iso: string;
    scores: Record<string, number>;
    gaps: string[];
}
export interface Training {
    id: string;
    title: string;
    format: 'Video' | 'Roleplay' | 'Video + Roleplay';
    duration: string;
    cluster: string;
    dimension: string;
    languages: string[];
    description: string;
    completions: number;
    avgScore: number;
    autoGenerated: boolean;
}
export interface RoleplayScenario {
    id: string;
    trainingId: string;
    title: string;
    persona: string;
    goal: string;
    phases: string[];
    language: string;
}
export interface IntakeSubmission {
    id: string;
    iso: string;
    site: string;
    channel: 'Voice' | 'Photo' | 'Delivery note' | 'Voice + Photo';
    language: string;
    timestamp: string;
    items: {
        cluster: string;
        item: string;
        qtyPerMonth: string;
        note?: string;
    }[];
    painPoints: string[];
    status: 'structured' | 'processing';
}
export type ContractStage = 'Build' | 'Negotiate' | 'Agree';
export interface Contract {
    id: string;
    supplierId: string;
    title: string;
    clusters: string[];
    countries: string[];
    volumeEUR: number;
    termYears: number;
    stage: ContractStage;
    progressPct: number;
    negotiatedSavingPct: number;
    openPoints: string[];
    trainingCommitments: {
        trainingId: string;
        scope: string;
    }[];
    maturityGate: {
        dimension: string;
        target: number;
        note: string;
    };
    nextMilestone: string;
}

export const countries: Country[] = [
  {
    "iso": "AT",
    "name": "Austria",
    "region": "Austria",
    "lat": 47.6,
    "lon": 14.1,
    "language": "German",
    "dealers": 32,
    "bodyShops": 26,
    "entryYear": 2018,
    "revenueEUR": 1258131.25,
    "submissions": 24,
    "submissionTarget": 26,
    "maturity": 1,
    "intakeStatus": "in progress",
    "topDemands": [
      "schleif",
      "lack",
      "kabine"
    ],
    "supplyDependency": "Direct manufacturer supply"
  },
  {
    "iso": "DE",
    "name": "Germany",
    "region": "Northern Europe",
    "lat": 51.2,
    "lon": 10.4,
    "language": "German",
    "dealers": 22,
    "bodyShops": 16,
    "entryYear": 1993,
    "revenueEUR": 1184061.63,
    "submissions": 0,
    "submissionTarget": 16,
    "maturity": 4,
    "intakeStatus": "pending",
    "topDemands": [
      "psa",
      "kleb",
      "lack"
    ],
    "supplyDependency": "Distributor (two-tier)"
  },
  {
    "iso": "SE",
    "name": "Sweden",
    "region": "Northern Europe",
    "lat": 62,
    "lon": 15,
    "language": "Swedish",
    "dealers": 50,
    "bodyShops": 30,
    "entryYear": 1987,
    "revenueEUR": 1136765.45,
    "submissions": 5,
    "submissionTarget": 30,
    "maturity": 3,
    "intakeStatus": "in progress",
    "topDemands": [
      "kleb",
      "psa",
      "schleif"
    ],
    "supplyDependency": "Import via northern central warehouse"
  },
  {
    "iso": "FR",
    "name": "France",
    "region": "Southwestern Europe",
    "lat": 46.6,
    "lon": 2.4,
    "language": "French",
    "dealers": 54,
    "bodyShops": 37,
    "entryYear": 2002,
    "revenueEUR": 1076432.28,
    "submissions": 5,
    "submissionTarget": 37,
    "maturity": 4,
    "intakeStatus": "in progress",
    "topDemands": [
      "kabine",
      "schleif",
      "polier"
    ],
    "supplyDependency": "Direct manufacturer supply"
  },
  {
    "iso": "IT",
    "name": "Italy",
    "region": "Southwestern Europe",
    "lat": 42.8,
    "lon": 12.5,
    "language": "Italian",
    "dealers": 45,
    "bodyShops": 33,
    "entryYear": 1987,
    "revenueEUR": 1288274.81,
    "submissions": 6,
    "submissionTarget": 33,
    "maturity": 4,
    "intakeStatus": "in progress",
    "topDemands": [
      "kabine",
      "kleb",
      "psa"
    ],
    "supplyDependency": "Distributor (two-tier)"
  },
  {
    "iso": "ES",
    "name": "Spain",
    "region": "Southwestern Europe",
    "lat": 40.4,
    "lon": -3.7,
    "language": "Spanish",
    "dealers": 25,
    "bodyShops": 18,
    "entryYear": 2012,
    "revenueEUR": 1063867.79,
    "submissions": 2,
    "submissionTarget": 18,
    "maturity": 4,
    "intakeStatus": "in progress",
    "topDemands": [
      "kabine",
      "werkstatt",
      "psa"
    ],
    "supplyDependency": "Import via northern central warehouse"
  },
  {
    "iso": "PT",
    "name": "Portugal",
    "region": "Southwestern Europe",
    "lat": 39.6,
    "lon": -8,
    "language": "Portuguese",
    "dealers": 34,
    "bodyShops": 23,
    "entryYear": 2007,
    "revenueEUR": 1391118.34,
    "submissions": 16,
    "submissionTarget": 23,
    "maturity": 4,
    "intakeStatus": "in progress",
    "topDemands": [
      "psa",
      "lack",
      "polier"
    ],
    "supplyDependency": "Direct manufacturer supply"
  },
  {
    "iso": "CH",
    "name": "Switzerland",
    "region": "Southwestern Europe",
    "lat": 46.8,
    "lon": 8.2,
    "language": "German / French",
    "dealers": 31,
    "bodyShops": 24,
    "entryYear": 1983,
    "revenueEUR": 1167238.66,
    "submissions": 8,
    "submissionTarget": 24,
    "maturity": 2,
    "intakeStatus": "in progress",
    "topDemands": [
      "kleb",
      "polier",
      "kabine"
    ],
    "supplyDependency": "Distributor (two-tier)"
  },
  {
    "iso": "PL",
    "name": "Poland",
    "region": "Central and Eastern Europe",
    "lat": 52,
    "lon": 19.3,
    "language": "Polish",
    "dealers": 51,
    "bodyShops": 37,
    "entryYear": 2014,
    "revenueEUR": 1206154.52,
    "submissions": 21,
    "submissionTarget": 37,
    "maturity": 3,
    "intakeStatus": "in progress",
    "topDemands": [
      "werkstatt",
      "schleif",
      "kleb"
    ],
    "supplyDependency": "Import via northern central warehouse"
  },
  {
    "iso": "CZ",
    "name": "Czechia",
    "region": "Central and Eastern Europe",
    "lat": 49.8,
    "lon": 15.5,
    "language": "Czech",
    "dealers": 49,
    "bodyShops": 26,
    "entryYear": 2016,
    "revenueEUR": 1058325.94,
    "submissions": 13,
    "submissionTarget": 26,
    "maturity": 4,
    "intakeStatus": "in progress",
    "topDemands": [
      "kleb",
      "lack",
      "psa"
    ],
    "supplyDependency": "Direct manufacturer supply"
  },
  {
    "iso": "SK",
    "name": "Slovakia",
    "region": "Central and Eastern Europe",
    "lat": 48.7,
    "lon": 19.5,
    "language": "Slovak",
    "dealers": 35,
    "bodyShops": 20,
    "entryYear": 1993,
    "revenueEUR": 1198742.58,
    "submissions": 20,
    "submissionTarget": 20,
    "maturity": 1,
    "intakeStatus": "live",
    "topDemands": [
      "polier",
      "lack",
      "schleif"
    ],
    "supplyDependency": "Distributor (two-tier)"
  },
  {
    "iso": "HU",
    "name": "Hungary",
    "region": "Central and Eastern Europe",
    "lat": 47.2,
    "lon": 19.5,
    "language": "Hungarian",
    "dealers": 42,
    "bodyShops": 33,
    "entryYear": 2016,
    "revenueEUR": 1225180.44,
    "submissions": 9,
    "submissionTarget": 33,
    "maturity": 1,
    "intakeStatus": "in progress",
    "topDemands": [
      "kleb",
      "polier",
      "psa"
    ],
    "supplyDependency": "Import via northern central warehouse"
  },
  {
    "iso": "SI",
    "name": "Slovenia",
    "region": "Central and Eastern Europe",
    "lat": 46.1,
    "lon": 14.8,
    "language": "Slovenian",
    "dealers": 43,
    "bodyShops": 27,
    "entryYear": 1987,
    "revenueEUR": 1296414.55,
    "submissions": 27,
    "submissionTarget": 27,
    "maturity": 1,
    "intakeStatus": "live",
    "topDemands": [
      "psa",
      "schleif",
      "lack"
    ],
    "supplyDependency": "Direct manufacturer supply"
  },
  {
    "iso": "HR",
    "name": "Croatia",
    "region": "Central and Eastern Europe",
    "lat": 45.5,
    "lon": 16,
    "language": "Croatian",
    "dealers": 56,
    "bodyShops": 37,
    "entryYear": 2003,
    "revenueEUR": 1164222.98,
    "submissions": 34,
    "submissionTarget": 37,
    "maturity": 4,
    "intakeStatus": "in progress",
    "topDemands": [
      "werkstatt",
      "kleb",
      "polier"
    ],
    "supplyDependency": "Distributor (two-tier)"
  },
  {
    "iso": "RO",
    "name": "Romania",
    "region": "Central and Eastern Europe",
    "lat": 45.9,
    "lon": 25,
    "language": "Romanian",
    "dealers": 26,
    "bodyShops": 8,
    "entryYear": 2009,
    "revenueEUR": 1372390.51,
    "submissions": 1,
    "submissionTarget": 8,
    "maturity": 2,
    "intakeStatus": "in progress",
    "topDemands": [
      "psa",
      "polier",
      "lack"
    ],
    "supplyDependency": "Import via northern central warehouse"
  },
  {
    "iso": "BG",
    "name": "Bulgaria",
    "region": "Central and Eastern Europe",
    "lat": 42.8,
    "lon": 25.2,
    "language": "Bulgarian",
    "dealers": 18,
    "bodyShops": 11,
    "entryYear": 2011,
    "revenueEUR": 1075972.36,
    "submissions": 9,
    "submissionTarget": 11,
    "maturity": 3,
    "intakeStatus": "in progress",
    "topDemands": [
      "lack",
      "kabine",
      "kleb"
    ],
    "supplyDependency": "Direct manufacturer supply"
  },
  {
    "iso": "RS",
    "name": "Serbia",
    "region": "Central and Eastern Europe",
    "lat": 44.2,
    "lon": 20.9,
    "language": "Serbian",
    "dealers": 54,
    "bodyShops": 33,
    "entryYear": 1983,
    "revenueEUR": 993781.16,
    "submissions": 23,
    "submissionTarget": 33,
    "maturity": 5,
    "intakeStatus": "in progress",
    "topDemands": [
      "psa",
      "schleif",
      "lack"
    ],
    "supplyDependency": "Distributor (two-tier)"
  },
  {
    "iso": "BA",
    "name": "Bosnia and Herzegovina",
    "region": "Central and Eastern Europe",
    "lat": 44.2,
    "lon": 17.8,
    "language": "Bosnian",
    "dealers": 36,
    "bodyShops": 25,
    "entryYear": 2006,
    "revenueEUR": 1160474.0,
    "submissions": 8,
    "submissionTarget": 25,
    "maturity": 4,
    "intakeStatus": "in progress",
    "topDemands": [
      "kabine",
      "werkstatt",
      "kleb"
    ],
    "supplyDependency": "Import via northern central warehouse"
  },
  {
    "iso": "AL",
    "name": "Albania",
    "region": "Central and Eastern Europe",
    "lat": 41.1,
    "lon": 20.1,
    "language": "Albanian",
    "dealers": 49,
    "bodyShops": 34,
    "entryYear": 1990,
    "revenueEUR": 957464.62,
    "submissions": 3,
    "submissionTarget": 34,
    "maturity": 2,
    "intakeStatus": "in progress",
    "topDemands": [
      "kabine",
      "lack",
      "psa"
    ],
    "supplyDependency": "Direct manufacturer supply"
  },
  {
    "iso": "MK",
    "name": "North Macedonia",
    "region": "Central and Eastern Europe",
    "lat": 41.6,
    "lon": 21.7,
    "language": "Macedonian",
    "dealers": 22,
    "bodyShops": 11,
    "entryYear": 2023,
    "revenueEUR": 1272894.77,
    "submissions": 8,
    "submissionTarget": 11,
    "maturity": 2,
    "intakeStatus": "in progress",
    "topDemands": [
      "kleb",
      "polier",
      "werkstatt"
    ],
    "supplyDependency": "Distributor (two-tier)"
  },
  {
    "iso": "ME",
    "name": "Montenegro",
    "region": "Central and Eastern Europe",
    "lat": 42.7,
    "lon": 19.4,
    "language": "Montenegrin",
    "dealers": 39,
    "bodyShops": 19,
    "entryYear": 2008,
    "revenueEUR": 1003321.75,
    "submissions": 10,
    "submissionTarget": 19,
    "maturity": 3,
    "intakeStatus": "in progress",
    "topDemands": [
      "werkstatt",
      "kleb",
      "polier"
    ],
    "supplyDependency": "Import via northern central warehouse"
  },
  {
    "iso": "UA",
    "name": "Ukraine",
    "region": "Central and Eastern Europe",
    "lat": 49,
    "lon": 32,
    "language": "Ukrainian",
    "dealers": 16,
    "bodyShops": 12,
    "entryYear": 2021,
    "revenueEUR": 1222379.39,
    "submissions": 4,
    "submissionTarget": 12,
    "maturity": 1,
    "intakeStatus": "in progress",
    "topDemands": [
      "psa",
      "lack",
      "werkstatt"
    ],
    "supplyDependency": "Direct manufacturer supply"
  },
  {
    "iso": "CN",
    "name": "China",
    "region": "Asia",
    "lat": 35,
    "lon": 104,
    "language": "Mandarin",
    "dealers": 23,
    "bodyShops": 11,
    "entryYear": 1986,
    "revenueEUR": 1272781.0,
    "submissions": 3,
    "submissionTarget": 11,
    "maturity": 4,
    "intakeStatus": "in progress",
    "topDemands": [
      "werkstatt",
      "kabine",
      "lack"
    ],
    "supplyDependency": "Distributor (two-tier)"
  },
  {
    "iso": "JP",
    "name": "Japan",
    "region": "Asia",
    "lat": 36.2,
    "lon": 138.3,
    "language": "Japanese",
    "dealers": 33,
    "bodyShops": 10,
    "entryYear": 1987,
    "revenueEUR": 1134451.07,
    "submissions": 10,
    "submissionTarget": 10,
    "maturity": 2,
    "intakeStatus": "live",
    "topDemands": [
      "werkstatt",
      "kleb",
      "kabine"
    ],
    "supplyDependency": "Import via northern central warehouse"
  },
  {
    "iso": "MY",
    "name": "Malaysia",
    "region": "Asia",
    "lat": 3.9,
    "lon": 102,
    "language": "Malay / English",
    "dealers": 36,
    "bodyShops": 17,
    "entryYear": 1997,
    "revenueEUR": 1328153.02,
    "submissions": 15,
    "submissionTarget": 17,
    "maturity": 4,
    "intakeStatus": "in progress",
    "topDemands": [
      "psa",
      "schleif",
      "kleb"
    ],
    "supplyDependency": "Direct manufacturer supply"
  },
  {
    "iso": "SG",
    "name": "Singapore",
    "region": "Asia",
    "lat": 1.35,
    "lon": 103.8,
    "language": "English",
    "dealers": 43,
    "bodyShops": 22,
    "entryYear": 2017,
    "revenueEUR": 1218724.75,
    "submissions": 9,
    "submissionTarget": 22,
    "maturity": 5,
    "intakeStatus": "in progress",
    "topDemands": [
      "werkstatt",
      "schleif",
      "psa"
    ],
    "supplyDependency": "Distributor (two-tier)"
  },
  {
    "iso": "CL",
    "name": "Chile",
    "region": "South America",
    "lat": -33.5,
    "lon": -70.7,
    "language": "Spanish",
    "dealers": 54,
    "bodyShops": 33,
    "entryYear": 1991,
    "revenueEUR": 1032237.23,
    "submissions": 2,
    "submissionTarget": 33,
    "maturity": 5,
    "intakeStatus": "in progress",
    "topDemands": [
      "werkstatt",
      "kleb",
      "kabine"
    ],
    "supplyDependency": "Import via northern central warehouse"
  },
  {
    "iso": "CO",
    "name": "Colombia",
    "region": "South America",
    "lat": 4.6,
    "lon": -74,
    "language": "Spanish",
    "dealers": 40,
    "bodyShops": 27,
    "entryYear": 1986,
    "revenueEUR": 1075580.43,
    "submissions": 3,
    "submissionTarget": 27,
    "maturity": 5,
    "intakeStatus": "in progress",
    "topDemands": [
      "kleb",
      "polier",
      "kabine"
    ],
    "supplyDependency": "Direct manufacturer supply"
  },
  {
    "iso": "XK",
    "name": "Kosovo",
    "region": "Central and Eastern Europe",
    "lat": 42.6,
    "lon": 20.9,
    "language": "Albanian",
    "dealers": 44,
    "bodyShops": 23,
    "entryYear": 2005,
    "revenueEUR": 1172053.03,
    "submissions": 0,
    "submissionTarget": 23,
    "maturity": 3,
    "intakeStatus": "pending",
    "topDemands": [
      "psa",
      "polier",
      "kleb"
    ],
    "supplyDependency": "Distributor (two-tier)"
  }
];
export const company = {
  "claim": "Precision in every material step.",
  "vision": "Fictional luxury car manufacturer for the Wolf Challenge.",
  "standorte": 1102,
  "laender": 29,
  "mitarbeiter": 18740,
  "umsatzMrdEUR": 18.6,
  "neuwagen2025": 284700,
  "gebrauchtwagen2025": 68400,
  "informatik": {
    "loesungen": 84,
    "laender": 29
  }
};
export const standardsortiment: SortimentItem[] = [
  {
    "nr": 1,
    "cluster": "lack",
    "kategorie": "Mixing cups and paint cups",
    "artikel": "Graduated mixing cup",
    "spezifikation": "125 ml, 250 ml, 400 ml, 600 ml, 1,000 ml",
    "einheit": "piece",
    "prioritaet": 3,
    "marken": "Glasurit (BASF), Finixa, SATA, tesa, Würth, Kovax",
    "anmerkung": "Synthetic dataset"
  },
  {
    "nr": 2,
    "cluster": "schleif",
    "kategorie": "Sanding discs 150 mm",
    "artikel": "Sanding discs 150 mm, coarse",
    "spezifikation": "P40, P60, P80, P100",
    "einheit": "piece",
    "prioritaet": 3,
    "marken": "3M, Glasurit (BASF), Mirka, SATA, PPG / Nexa, Würth, Starcke",
    "anmerkung": "Synthetic dataset"
  },
  {
    "nr": 3,
    "cluster": "kleb",
    "kategorie": "Masking tapes",
    "artikel": "Standard masking tape",
    "spezifikation": "18 mm, 24 mm, 30 mm, 36 mm, 48 mm × 50 m",
    "einheit": "piece",
    "prioritaet": 3,
    "marken": "3M, Finixa, Mirka, tesa, PPG / Nexa, Kovax, Starcke",
    "anmerkung": "Synthetic dataset"
  },
  {
    "nr": 4,
    "cluster": "polier",
    "kategorie": "Cutting compounds and polishes",
    "artikel": "Cutting compound (coarse/medium)",
    "spezifikation": "1-step or 2-stage, 500 ml / 1 L",
    "einheit": "piece",
    "prioritaet": 3,
    "marken": "Glasurit (BASF), Finixa, SATA, tesa, Würth, Kovax",
    "anmerkung": "Synthetic dataset"
  },
  {
    "nr": 5,
    "cluster": "kabine",
    "kategorie": "Degreasers / cleaners",
    "artikel": "Solvent-based silicone remover",
    "spezifikation": "1 L, 5 L",
    "einheit": "piece",
    "prioritaet": 3,
    "marken": "3M, Glasurit (BASF), Mirka, SATA, PPG / Nexa, Würth, Starcke",
    "anmerkung": "Synthetic dataset"
  },
  {
    "nr": 6,
    "cluster": "psa",
    "kategorie": "Respiratory protection",
    "artikel": "Half mask / spray-painting respirator",
    "spezifikation": "Sizes S, M, L - A2/P3 filter",
    "einheit": "piece",
    "prioritaet": 3,
    "marken": "3M, Finixa, Mirka, tesa, PPG / Nexa, Kovax, Starcke",
    "anmerkung": "Synthetic dataset"
  },
  {
    "nr": 7,
    "cluster": "werkstatt",
    "kategorie": "Pneumatic random orbital sanders",
    "artikel": "Random orbital sander 150 mm, 5 mm orbit",
    "spezifikation": "Pneumatic, for bodywork sanding",
    "einheit": "piece",
    "prioritaet": 3,
    "marken": "Glasurit (BASF), Finixa, SATA, tesa, Würth, Kovax",
    "anmerkung": "Synthetic dataset"
  },
  {
    "nr": 8,
    "cluster": "lack",
    "kategorie": "Mixing cups and paint cups",
    "artikel": "Paint cup for compressed-air spray gun",
    "spezifikation": "PPS system or universal, 125 µ filter",
    "einheit": "piece",
    "prioritaet": 3,
    "marken": "Glasurit (BASF), Finixa, SATA, tesa, Würth, Kovax",
    "anmerkung": "Synthetic dataset"
  },
  {
    "nr": 9,
    "cluster": "schleif",
    "kategorie": "Sanding discs 150 mm",
    "artikel": "Sanding discs 150 mm, intermediate",
    "spezifikation": "P120, P150, P180, P220, P240",
    "einheit": "piece",
    "prioritaet": 3,
    "marken": "3M, Glasurit (BASF), Mirka, SATA, PPG / Nexa, Würth, Starcke",
    "anmerkung": "Synthetic dataset"
  },
  {
    "nr": 10,
    "cluster": "kleb",
    "kategorie": "Masking tapes",
    "artikel": "Fine-line tape",
    "spezifikation": "3 mm, 6 mm, 9 mm × 33 m transparent",
    "einheit": "piece",
    "prioritaet": 3,
    "marken": "3M, Finixa, Mirka, tesa, PPG / Nexa, Kovax, Starcke",
    "anmerkung": "Synthetic dataset"
  },
  {
    "nr": 11,
    "cluster": "polier",
    "kategorie": "Cutting compounds and polishes",
    "artikel": "Polish (fine / anti-hologram)",
    "spezifikation": "500 ml / 1 L",
    "einheit": "piece",
    "prioritaet": 3,
    "marken": "Glasurit (BASF), Finixa, SATA, tesa, Würth, Kovax",
    "anmerkung": "Synthetic dataset"
  },
  {
    "nr": 12,
    "cluster": "kabine",
    "kategorie": "Degreasers / cleaners",
    "artikel": "Water-based silicone remover",
    "spezifikation": "1 L, 5 L",
    "einheit": "piece",
    "prioritaet": 3,
    "marken": "3M, Glasurit (BASF), Mirka, SATA, PPG / Nexa, Würth, Starcke",
    "anmerkung": "Synthetic dataset"
  },
  {
    "nr": 13,
    "cluster": "psa",
    "kategorie": "Respiratory protection",
    "artikel": "A2 filter cartridges",
    "spezifikation": "Compatible with the mask in use",
    "einheit": "piece",
    "prioritaet": 3,
    "marken": "3M, Finixa, Mirka, tesa, PPG / Nexa, Kovax, Starcke",
    "anmerkung": "Synthetic dataset"
  },
  {
    "nr": 14,
    "cluster": "werkstatt",
    "kategorie": "Pneumatic random orbital sanders",
    "artikel": "Random orbital sander 77 mm",
    "spezifikation": "Pneumatic, for detail work",
    "einheit": "piece",
    "prioritaet": 3,
    "marken": "Glasurit (BASF), Finixa, SATA, tesa, Würth, Kovax",
    "anmerkung": "Synthetic dataset"
  },
  {
    "nr": 15,
    "cluster": "lack",
    "kategorie": "Mixing cups and paint cups",
    "artikel": "Paint strainers 125 µ / 200 µ",
    "spezifikation": "Compatible with the cup type",
    "einheit": "piece",
    "prioritaet": 3,
    "marken": "Glasurit (BASF), Finixa, SATA, tesa, Würth, Kovax",
    "anmerkung": "Synthetic dataset"
  },
  {
    "nr": 16,
    "cluster": "schleif",
    "kategorie": "Sanding discs 150 mm",
    "artikel": "Sanding discs 150 mm, fine",
    "spezifikation": "P280, P320, P400, P500, P600",
    "einheit": "piece",
    "prioritaet": 3,
    "marken": "3M, Glasurit (BASF), Mirka, SATA, PPG / Nexa, Würth, Starcke",
    "anmerkung": "Synthetic dataset"
  },
  {
    "nr": 17,
    "cluster": "kleb",
    "kategorie": "Masking tapes",
    "artikel": "Contour tape",
    "spezifikation": "3 mm, 6 mm, 9 mm, 12 mm, 19 mm",
    "einheit": "piece",
    "prioritaet": 2,
    "marken": "3M, Finixa, Mirka, tesa, PPG / Nexa, Kovax, Starcke",
    "anmerkung": "Synthetic dataset"
  },
  {
    "nr": 18,
    "cluster": "polier",
    "kategorie": "Cutting compounds and polishes",
    "artikel": "One-step cutting and polishing compound",
    "spezifikation": "500 ml / 1 L",
    "einheit": "piece",
    "prioritaet": 2,
    "marken": "Glasurit (BASF), Finixa, SATA, tesa, Würth, Kovax",
    "anmerkung": "Synthetic dataset"
  },
  {
    "nr": 19,
    "cluster": "kabine",
    "kategorie": "Degreasers / cleaners",
    "artikel": "Pre-saturated cleaning wipes",
    "spezifikation": "38×38 cm, box of 200 pieces",
    "einheit": "piece",
    "prioritaet": 2,
    "marken": "3M, Glasurit (BASF), Mirka, SATA, PPG / Nexa, Würth, Starcke",
    "anmerkung": "Synthetic dataset"
  },
  {
    "nr": 20,
    "cluster": "psa",
    "kategorie": "Respiratory protection",
    "artikel": "P3 particulate filters",
    "spezifikation": "Compatible with the mask in use",
    "einheit": "piece",
    "prioritaet": 2,
    "marken": "3M, Finixa, Mirka, tesa, PPG / Nexa, Kovax, Starcke",
    "anmerkung": "Synthetic dataset"
  },
  {
    "nr": 21,
    "cluster": "werkstatt",
    "kategorie": "Pneumatic random orbital sanders",
    "artikel": "Electric random orbital sander 150 mm",
    "spezifikation": "For locations without compressed air",
    "einheit": "piece",
    "prioritaet": 2,
    "marken": "Glasurit (BASF), Finixa, SATA, tesa, Würth, Kovax",
    "anmerkung": "Synthetic dataset"
  }
];
export const clusters: MaterialCluster[] = [
  {
    "id": "lack",
    "name": "Paint application and mixing",
    "description": "Synthetic material category: Paint application and mixing",
    "positions": 3,
    "spendEUR": 6928293.05,
    "savingPotentialPct": 18.19,
    "exampleItems": [
      "Graduated mixing cup",
      "Paint cup for compressed-air spray gun",
      "Paint strainers 125 µ / 200 µ"
    ]
  },
  {
    "id": "schleif",
    "name": "Sanding",
    "description": "Synthetic material category: Sanding",
    "positions": 3,
    "spendEUR": 8207604.48,
    "savingPotentialPct": 15.26,
    "exampleItems": [
      "Sanding discs 150 mm, coarse",
      "Sanding discs 150 mm, intermediate",
      "Sanding discs 150 mm, fine"
    ]
  },
  {
    "id": "kleb",
    "name": "Masking and covering",
    "description": "Synthetic material category: Masking and covering",
    "positions": 3,
    "spendEUR": 2459580.82,
    "savingPotentialPct": 13.1,
    "exampleItems": [
      "Standard masking tape",
      "Fine-line tape",
      "Contour tape"
    ]
  },
  {
    "id": "polier",
    "name": "Polishing and finishing",
    "description": "Synthetic material category: Polishing and finishing",
    "positions": 3,
    "spendEUR": 2996373.29,
    "savingPotentialPct": 8.9,
    "exampleItems": [
      "Cutting compound (coarse/medium)",
      "Polish (fine / anti-hologram)",
      "One-step cutting and polishing compound"
    ]
  },
  {
    "id": "kabine",
    "name": "Spray booth and cleaning",
    "description": "Synthetic material category: Spray booth and cleaning",
    "positions": 3,
    "spendEUR": 6911449.22,
    "savingPotentialPct": 18.31,
    "exampleItems": [
      "Solvent-based silicone remover",
      "Water-based silicone remover",
      "Pre-saturated cleaning wipes"
    ]
  },
  {
    "id": "psa",
    "name": "Personal protective equipment",
    "description": "Synthetic material category: Personal protective equipment",
    "positions": 3,
    "spendEUR": 2583618.77,
    "savingPotentialPct": 21.05,
    "exampleItems": [
      "Half mask / spray-painting respirator",
      "A2 filter cartridges",
      "P3 particulate filters"
    ]
  },
  {
    "id": "werkstatt",
    "name": "Workshop equipment",
    "description": "Synthetic material category: Workshop equipment",
    "positions": 3,
    "spendEUR": 3920670.68,
    "savingPotentialPct": 13.32,
    "exampleItems": [
      "Random orbital sander 150 mm, 5 mm orbit",
      "Random orbital sander 77 mm",
      "Electric random orbital sander 150 mm"
    ]
  }
];
export const suppliers: Supplier[] = [
  {
    "id": "sup-aster",
    "name": "3M",
    "type": "Manufacturer",
    "countries": [
      "DE",
      "SE",
      "FR",
      "IT",
      "ES",
      "PT",
      "PL",
      "CZ",
      "SK",
      "HU",
      "SI",
      "HR",
      "BG",
      "RS",
      "BA",
      "AL",
      "MK",
      "ME",
      "CN",
      "JP",
      "MY",
      "SG",
      "CL",
      "CO"
    ],
    "clusters": [
      "schleif",
      "kleb",
      "kabine",
      "psa"
    ],
    "offers": 12,
    "matchScore": 97,
    "priceDeltaPct": -18.58,
    "logisticsSavingEUR": 42000,
    "status": "shortlist"
  },
  {
    "id": "sup-velora",
    "name": "Glasurit (BASF)",
    "type": "Manufacturer",
    "countries": [
      "AT",
      "DE",
      "SE",
      "FR",
      "IT",
      "ES",
      "CH",
      "PL",
      "CZ",
      "SK",
      "HU",
      "SI",
      "RO",
      "BG",
      "RS",
      "BA",
      "AL",
      "MK",
      "UA",
      "CN",
      "JP",
      "MY",
      "SG",
      "CL",
      "XK"
    ],
    "clusters": [
      "lack",
      "schleif",
      "polier",
      "kabine",
      "werkstatt"
    ],
    "offers": 15,
    "matchScore": 83,
    "priceDeltaPct": -12.16,
    "logisticsSavingEUR": 32000,
    "status": "under review"
  },
  {
    "id": "sup-lumen",
    "name": "Finixa",
    "type": "Manufacturer",
    "countries": [
      "AT",
      "DE",
      "SE",
      "FR",
      "IT",
      "PT",
      "CH",
      "PL",
      "CZ",
      "SK",
      "HU",
      "HR",
      "RO",
      "BG",
      "RS",
      "BA",
      "AL",
      "ME",
      "UA",
      "CN",
      "JP",
      "MY",
      "SG",
      "CO",
      "XK"
    ],
    "clusters": [
      "lack",
      "kleb",
      "polier",
      "psa",
      "werkstatt"
    ],
    "offers": 15,
    "matchScore": 85,
    "priceDeltaPct": -9.55,
    "logisticsSavingEUR": 30000,
    "status": "submitted"
  },
  {
    "id": "sup-novex",
    "name": "Mirka",
    "type": "Manufacturer",
    "countries": [
      "AT",
      "DE",
      "SE",
      "FR",
      "ES",
      "PT",
      "CH",
      "PL",
      "CZ",
      "SK",
      "SI",
      "HR",
      "RO",
      "BG",
      "RS",
      "BA",
      "MK",
      "ME",
      "UA",
      "CN",
      "JP",
      "MY",
      "CL",
      "CO",
      "XK"
    ],
    "clusters": [
      "schleif",
      "kleb",
      "kabine",
      "psa"
    ],
    "offers": 12,
    "matchScore": 88,
    "priceDeltaPct": -21.16,
    "logisticsSavingEUR": 44000,
    "status": "shortlist"
  },
  {
    "id": "sup-arcus",
    "name": "SATA",
    "type": "Manufacturer",
    "countries": [
      "AT",
      "DE",
      "SE",
      "IT",
      "ES",
      "PT",
      "CH",
      "PL",
      "CZ",
      "HU",
      "SI",
      "HR",
      "RO",
      "BG",
      "RS",
      "AL",
      "MK",
      "ME",
      "UA",
      "CN",
      "JP",
      "SG",
      "CL",
      "CO",
      "XK"
    ],
    "clusters": [
      "lack",
      "schleif",
      "polier",
      "kabine",
      "werkstatt"
    ],
    "offers": 15,
    "matchScore": 86,
    "priceDeltaPct": -23.08,
    "logisticsSavingEUR": 44000,
    "status": "under review"
  },
  {
    "id": "sup-cobalt",
    "name": "tesa",
    "type": "Manufacturer",
    "countries": [
      "AT",
      "DE",
      "FR",
      "IT",
      "ES",
      "PT",
      "CH",
      "PL",
      "SK",
      "HU",
      "SI",
      "HR",
      "RO",
      "BG",
      "BA",
      "AL",
      "MK",
      "ME",
      "UA",
      "CN",
      "MY",
      "SG",
      "CL",
      "CO",
      "XK"
    ],
    "clusters": [
      "lack",
      "kleb",
      "polier",
      "psa",
      "werkstatt"
    ],
    "offers": 15,
    "matchScore": 84,
    "priceDeltaPct": -12.38,
    "logisticsSavingEUR": 18000,
    "status": "submitted"
  },
  {
    "id": "sup-solis",
    "name": "PPG / Nexa",
    "type": "Manufacturer",
    "countries": [
      "AT",
      "SE",
      "FR",
      "IT",
      "ES",
      "PT",
      "CH",
      "CZ",
      "SK",
      "HU",
      "SI",
      "HR",
      "RO",
      "RS",
      "BA",
      "AL",
      "MK",
      "ME",
      "UA",
      "JP",
      "MY",
      "SG",
      "CL",
      "CO",
      "XK"
    ],
    "clusters": [
      "schleif",
      "kleb",
      "kabine",
      "psa"
    ],
    "offers": 12,
    "matchScore": 74,
    "priceDeltaPct": -7.19,
    "logisticsSavingEUR": 10000,
    "status": "shortlist"
  },
  {
    "id": "sup-orbit",
    "name": "Würth",
    "type": "Distributor",
    "countries": [
      "DE",
      "SE",
      "FR",
      "IT",
      "ES",
      "PT",
      "PL",
      "CZ",
      "SK",
      "HU",
      "SI",
      "HR",
      "BG",
      "RS",
      "BA",
      "AL",
      "MK",
      "ME",
      "CN",
      "JP",
      "MY",
      "SG",
      "CL",
      "CO"
    ],
    "clusters": [
      "lack",
      "schleif",
      "polier",
      "kabine",
      "werkstatt"
    ],
    "offers": 15,
    "matchScore": 95,
    "priceDeltaPct": -9.19,
    "logisticsSavingEUR": 40000,
    "status": "under review"
  },
  {
    "id": "sup-helio",
    "name": "Kovax",
    "type": "Manufacturer",
    "countries": [
      "AT",
      "DE",
      "SE",
      "FR",
      "IT",
      "ES",
      "CH",
      "PL",
      "CZ",
      "SK",
      "HU",
      "SI",
      "RO",
      "BG",
      "RS",
      "BA",
      "AL",
      "MK",
      "UA",
      "CN",
      "JP",
      "MY",
      "SG",
      "CL",
      "XK"
    ],
    "clusters": [
      "lack",
      "kleb",
      "polier",
      "psa",
      "werkstatt"
    ],
    "offers": 15,
    "matchScore": 74,
    "priceDeltaPct": -13.83,
    "logisticsSavingEUR": 50000,
    "status": "submitted"
  },
  {
    "id": "sup-vanta",
    "name": "Starcke",
    "type": "Manufacturer",
    "countries": [
      "AT",
      "DE",
      "SE",
      "FR",
      "IT",
      "PT",
      "CH",
      "PL",
      "CZ",
      "SK",
      "HU",
      "HR",
      "RO",
      "BG",
      "RS",
      "BA",
      "AL",
      "ME",
      "UA",
      "CN",
      "JP",
      "MY",
      "SG",
      "CO",
      "XK"
    ],
    "clusters": [
      "schleif",
      "kleb",
      "kabine",
      "psa"
    ],
    "offers": 12,
    "matchScore": 75,
    "priceDeltaPct": -4.57,
    "logisticsSavingEUR": 49000,
    "status": "shortlist"
  }
];
export const maturityDimensions: MaturityDimension[] = [
  {
    "id": "material",
    "name": "Material expertise",
    "description": "Synthetic learning and quality dimension"
  },
  {
    "id": "prozess",
    "name": "Process quality",
    "description": "Synthetic learning and quality dimension"
  },
  {
    "id": "daten",
    "name": "Data maturity",
    "description": "Synthetic learning and quality dimension"
  },
  {
    "id": "digital",
    "name": "Digital adoption",
    "description": "Synthetic learning and quality dimension"
  },
  {
    "id": "nachhaltig",
    "name": "Resource efficiency",
    "description": "Synthetic learning and quality dimension"
  }
];
export const maturityProfiles: MaturityProfile[] = [
  {
    "iso": "AT",
    "scores": {
      "material": 3.9,
      "prozess": 4.8,
      "daten": 4.8,
      "digital": 1.5,
      "nachhaltig": 2.8
    },
    "gaps": [
      "t-daten",
      "t-digital"
    ]
  },
  {
    "iso": "DE",
    "scores": {
      "material": 1.0,
      "prozess": 2.5,
      "daten": 4.3,
      "digital": 4.4,
      "nachhaltig": 1.1
    },
    "gaps": []
  },
  {
    "iso": "SE",
    "scores": {
      "material": 1.8,
      "prozess": 4.4,
      "daten": 4.1,
      "digital": 4.6,
      "nachhaltig": 2.6
    },
    "gaps": []
  },
  {
    "iso": "FR",
    "scores": {
      "material": 3.0,
      "prozess": 3.5,
      "daten": 4.7,
      "digital": 2.2,
      "nachhaltig": 3.0
    },
    "gaps": []
  },
  {
    "iso": "IT",
    "scores": {
      "material": 3.1,
      "prozess": 3.0,
      "daten": 3.6,
      "digital": 2.0,
      "nachhaltig": 2.6
    },
    "gaps": []
  },
  {
    "iso": "ES",
    "scores": {
      "material": 4.2,
      "prozess": 1.2,
      "daten": 1.5,
      "digital": 3.1,
      "nachhaltig": 2.8
    },
    "gaps": []
  },
  {
    "iso": "PT",
    "scores": {
      "material": 3.0,
      "prozess": 1.8,
      "daten": 4.2,
      "digital": 4.3,
      "nachhaltig": 1.8
    },
    "gaps": []
  },
  {
    "iso": "CH",
    "scores": {
      "material": 2.7,
      "prozess": 4.0,
      "daten": 2.8,
      "digital": 4.8,
      "nachhaltig": 2.9
    },
    "gaps": [
      "t-daten",
      "t-digital"
    ]
  },
  {
    "iso": "PL",
    "scores": {
      "material": 1.5,
      "prozess": 3.8,
      "daten": 1.7,
      "digital": 1.7,
      "nachhaltig": 3.2
    },
    "gaps": []
  },
  {
    "iso": "CZ",
    "scores": {
      "material": 2.8,
      "prozess": 4.3,
      "daten": 2.9,
      "digital": 3.6,
      "nachhaltig": 4.4
    },
    "gaps": []
  },
  {
    "iso": "SK",
    "scores": {
      "material": 4.0,
      "prozess": 2.0,
      "daten": 1.5,
      "digital": 4.2,
      "nachhaltig": 2.5
    },
    "gaps": [
      "t-daten",
      "t-digital"
    ]
  },
  {
    "iso": "HU",
    "scores": {
      "material": 1.0,
      "prozess": 2.1,
      "daten": 2.4,
      "digital": 4.9,
      "nachhaltig": 4.4
    },
    "gaps": [
      "t-daten",
      "t-digital"
    ]
  },
  {
    "iso": "SI",
    "scores": {
      "material": 3.3,
      "prozess": 2.9,
      "daten": 2.4,
      "digital": 3.1,
      "nachhaltig": 3.2
    },
    "gaps": [
      "t-daten",
      "t-digital"
    ]
  },
  {
    "iso": "HR",
    "scores": {
      "material": 4.2,
      "prozess": 4.1,
      "daten": 1.4,
      "digital": 4.5,
      "nachhaltig": 3.4
    },
    "gaps": []
  },
  {
    "iso": "RO",
    "scores": {
      "material": 4.7,
      "prozess": 3.0,
      "daten": 4.5,
      "digital": 4.0,
      "nachhaltig": 2.9
    },
    "gaps": [
      "t-daten",
      "t-digital"
    ]
  },
  {
    "iso": "BG",
    "scores": {
      "material": 2.2,
      "prozess": 2.1,
      "daten": 1.8,
      "digital": 1.3,
      "nachhaltig": 4.8
    },
    "gaps": []
  },
  {
    "iso": "RS",
    "scores": {
      "material": 4.6,
      "prozess": 5.0,
      "daten": 1.3,
      "digital": 4.8,
      "nachhaltig": 3.1
    },
    "gaps": []
  },
  {
    "iso": "BA",
    "scores": {
      "material": 1.7,
      "prozess": 1.4,
      "daten": 1.7,
      "digital": 4.5,
      "nachhaltig": 3.0
    },
    "gaps": []
  },
  {
    "iso": "AL",
    "scores": {
      "material": 2.1,
      "prozess": 3.3,
      "daten": 4.5,
      "digital": 2.7,
      "nachhaltig": 4.9
    },
    "gaps": [
      "t-daten",
      "t-digital"
    ]
  },
  {
    "iso": "MK",
    "scores": {
      "material": 1.5,
      "prozess": 4.1,
      "daten": 4.8,
      "digital": 4.5,
      "nachhaltig": 4.5
    },
    "gaps": [
      "t-daten",
      "t-digital"
    ]
  },
  {
    "iso": "ME",
    "scores": {
      "material": 2.7,
      "prozess": 1.7,
      "daten": 3.4,
      "digital": 3.8,
      "nachhaltig": 3.3
    },
    "gaps": []
  },
  {
    "iso": "UA",
    "scores": {
      "material": 2.5,
      "prozess": 2.3,
      "daten": 2.3,
      "digital": 3.5,
      "nachhaltig": 4.9
    },
    "gaps": [
      "t-daten",
      "t-digital"
    ]
  },
  {
    "iso": "CN",
    "scores": {
      "material": 3.6,
      "prozess": 2.4,
      "daten": 5.0,
      "digital": 2.2,
      "nachhaltig": 4.1
    },
    "gaps": []
  },
  {
    "iso": "JP",
    "scores": {
      "material": 3.4,
      "prozess": 3.7,
      "daten": 4.7,
      "digital": 2.9,
      "nachhaltig": 2.8
    },
    "gaps": [
      "t-daten",
      "t-digital"
    ]
  },
  {
    "iso": "MY",
    "scores": {
      "material": 2.3,
      "prozess": 2.7,
      "daten": 3.8,
      "digital": 3.9,
      "nachhaltig": 3.6
    },
    "gaps": []
  },
  {
    "iso": "SG",
    "scores": {
      "material": 3.0,
      "prozess": 4.8,
      "daten": 3.4,
      "digital": 3.9,
      "nachhaltig": 4.3
    },
    "gaps": []
  },
  {
    "iso": "CL",
    "scores": {
      "material": 1.6,
      "prozess": 4.7,
      "daten": 4.8,
      "digital": 2.9,
      "nachhaltig": 4.0
    },
    "gaps": []
  },
  {
    "iso": "CO",
    "scores": {
      "material": 1.2,
      "prozess": 2.1,
      "daten": 4.7,
      "digital": 2.6,
      "nachhaltig": 2.1
    },
    "gaps": []
  },
  {
    "iso": "XK",
    "scores": {
      "material": 5.0,
      "prozess": 4.6,
      "daten": 4.0,
      "digital": 3.9,
      "nachhaltig": 2.4
    },
    "gaps": []
  }
];
export const trainings: Training[] = [
  {
    "id": "t-basis",
    "title": "Select materials for a repair",
    "format": "Video",
    "duration": "15 min",
    "cluster": "lack",
    "dimension": "material",
    "languages": [
      "EN"
    ],
    "description": "Exercise using fictional records and documented human review.",
    "completions": 54,
    "avgScore": 89,
    "autoGenerated": true
  },
  {
    "id": "t-prozess",
    "title": "Document the process sequence",
    "format": "Roleplay",
    "duration": "20 min",
    "cluster": "kabine",
    "dimension": "prozess",
    "languages": [
      "EN"
    ],
    "description": "Exercise using fictional records and documented human review.",
    "completions": 48,
    "avgScore": 89,
    "autoGenerated": false
  },
  {
    "id": "t-daten",
    "title": "Check invoices against price agreements",
    "format": "Video + Roleplay",
    "duration": "25 min",
    "cluster": "werkstatt",
    "dimension": "daten",
    "languages": [
      "EN"
    ],
    "description": "Exercise using fictional records and documented human review.",
    "completions": 172,
    "avgScore": 82,
    "autoGenerated": true
  },
  {
    "id": "t-voc",
    "title": "Reduce material consumption",
    "format": "Video",
    "duration": "30 min",
    "cluster": "lack",
    "dimension": "nachhaltig",
    "languages": [
      "EN"
    ],
    "description": "Exercise using fictional records and documented human review.",
    "completions": 78,
    "avgScore": 81,
    "autoGenerated": false
  },
  {
    "id": "t-psa",
    "title": "Select protective equipment",
    "format": "Roleplay",
    "duration": "35 min",
    "cluster": "psa",
    "dimension": "prozess",
    "languages": [
      "EN"
    ],
    "description": "Exercise using fictional records and documented human review.",
    "completions": 47,
    "avgScore": 75,
    "autoGenerated": true
  },
  {
    "id": "t-digital",
    "title": "Digital demand submission",
    "format": "Video + Roleplay",
    "duration": "40 min",
    "cluster": "werkstatt",
    "dimension": "digital",
    "languages": [
      "EN"
    ],
    "description": "Exercise using fictional records and documented human review.",
    "completions": 167,
    "avgScore": 69,
    "autoGenerated": false
  }
];
export const roleplayScenarios: RoleplayScenario[] = [
  {
    "id": "rp-bedarf",
    "trainingId": "t-daten",
    "title": "Capture structured demand",
    "persona": "Fictional Wolf training assistant",
    "goal": "Document record review with a clear audit trail",
    "phases": [
      "Read the record",
      "Check the match",
      "Confirm the decision"
    ],
    "language": "EN"
  },
  {
    "id": "rp-reklamation",
    "trainingId": "t-basis",
    "title": "Resolve a price variance",
    "persona": "Fictional Wolf training assistant",
    "goal": "Document record review with a clear audit trail",
    "phases": [
      "Read the record",
      "Check the match",
      "Confirm the decision"
    ],
    "language": "EN"
  },
  {
    "id": "rp-unterweisung",
    "trainingId": "t-psa",
    "title": "Practise safety instruction",
    "persona": "Fictional Wolf training assistant",
    "goal": "Document record review with a clear audit trail",
    "phases": [
      "Read the record",
      "Check the match",
      "Confirm the decision"
    ],
    "language": "EN"
  }
];
export const intakeSubmissions: IntakeSubmission[] = [
  {
    "id": "sub-wolf-001",
    "iso": "AT",
    "site": "Wolf Atelier Austria 01",
    "channel": "Voice",
    "language": "German",
    "timestamp": "2026-09-18T08:20:00Z",
    "items": [
      {
        "cluster": "lack",
        "item": "Graduated mixing cup",
        "qtyPerMonth": "63 piece"
      }
    ],
    "painPoints": [
      "Price agreement requires review"
    ],
    "status": "processing"
  },
  {
    "id": "sub-wolf-002",
    "iso": "DE",
    "site": "Wolf Atelier Germany 02",
    "channel": "Photo",
    "language": "German",
    "timestamp": "2026-09-18T09:20:00Z",
    "items": [
      {
        "cluster": "schleif",
        "item": "Sanding discs 150 mm, coarse",
        "qtyPerMonth": "69 piece"
      }
    ],
    "painPoints": [
      "Invoice pack unit missing"
    ],
    "status": "structured"
  },
  {
    "id": "sub-wolf-003",
    "iso": "SE",
    "site": "Wolf Atelier Sweden 03",
    "channel": "Delivery note",
    "language": "Swedish",
    "timestamp": "2026-09-18T10:20:00Z",
    "items": [
      {
        "cluster": "kleb",
        "item": "Standard masking tape",
        "qtyPerMonth": "25 piece"
      }
    ],
    "painPoints": [
      "Price agreement requires review"
    ],
    "status": "processing"
  },
  {
    "id": "sub-wolf-004",
    "iso": "FR",
    "site": "Wolf Atelier France 04",
    "channel": "Voice + Photo",
    "language": "French",
    "timestamp": "2026-09-18T11:20:00Z",
    "items": [
      {
        "cluster": "polier",
        "item": "Cutting compound (coarse/medium)",
        "qtyPerMonth": "63 piece"
      }
    ],
    "painPoints": [
      "Invoice pack unit missing"
    ],
    "status": "structured"
  },
  {
    "id": "sub-wolf-005",
    "iso": "IT",
    "site": "Wolf Atelier Italy 05",
    "channel": "Voice",
    "language": "Italian",
    "timestamp": "2026-09-18T12:20:00Z",
    "items": [
      {
        "cluster": "kabine",
        "item": "Solvent-based silicone remover",
        "qtyPerMonth": "69 piece"
      }
    ],
    "painPoints": [
      "Price agreement requires review"
    ],
    "status": "processing"
  }
];
export const totals = {
  "spendEUR": 34007590.31,
  "positions": 21,
  "sortimentArtikel": 21,
  "submissions": 298,
  "submissionTarget": 683,
  "offers": 138,
  "priceSavingEUR": 5433190.7,
  "logisticsSavingEUR": 359000,
  "avgMaturity": 3.217931034482759
};
export const contracts: Contract[] = [
  {
    "id": "ctr-velora",
    "supplierId": "sup-velora",
    "title": "Framework agreement: Glasurit (BASF)",
    "clusters": [
      "lack",
      "schleif",
      "polier",
      "kabine",
      "werkstatt"
    ],
    "countries": [
      "AT",
      "DE",
      "SE",
      "FR",
      "IT",
      "ES",
      "CH",
      "PL"
    ],
    "volumeEUR": 977522.44,
    "termYears": 2,
    "stage": "Negotiate",
    "progressPct": 55,
    "negotiatedSavingPct": 17.98,
    "openPoints": [
      "Confirm invoice reconciliation in the pilot"
    ],
    "trainingCommitments": [
      {
        "trainingId": "t-daten",
        "scope": "Fictional pilot: invoice review across all sites"
      }
    ],
    "maturityGate": {
      "dimension": "daten",
      "target": 3,
      "note": "Demo assumption: documented review step"
    },
    "nextMilestone": "2026-09-25: review the synthetic pilot case"
  },
  {
    "id": "ctr-aster",
    "supplierId": "sup-aster",
    "title": "Framework agreement: 3M",
    "clusters": [
      "schleif",
      "kleb",
      "kabine",
      "psa"
    ],
    "countries": [
      "DE",
      "SE",
      "FR",
      "IT",
      "ES",
      "PT",
      "PL",
      "CZ"
    ],
    "volumeEUR": 929764.21,
    "termYears": 3,
    "stage": "Build",
    "progressPct": 30,
    "negotiatedSavingPct": 11.2,
    "openPoints": [
      "Confirm invoice reconciliation in the pilot"
    ],
    "trainingCommitments": [
      {
        "trainingId": "t-daten",
        "scope": "Fictional pilot: invoice review across all sites"
      }
    ],
    "maturityGate": {
      "dimension": "daten",
      "target": 3,
      "note": "Demo assumption: documented review step"
    },
    "nextMilestone": "2026-09-25: review the synthetic pilot case"
  },
  {
    "id": "ctr-cobalt",
    "supplierId": "sup-cobalt",
    "title": "Framework agreement: tesa",
    "clusters": [
      "lack",
      "kleb",
      "polier",
      "psa",
      "werkstatt"
    ],
    "countries": [
      "AT",
      "DE",
      "FR",
      "IT",
      "ES",
      "PT",
      "CH",
      "PL"
    ],
    "volumeEUR": 993108.68,
    "termYears": 2,
    "stage": "Negotiate",
    "progressPct": 68,
    "negotiatedSavingPct": 14.35,
    "openPoints": [
      "Confirm invoice reconciliation in the pilot"
    ],
    "trainingCommitments": [
      {
        "trainingId": "t-daten",
        "scope": "Fictional pilot: invoice review across all sites"
      }
    ],
    "maturityGate": {
      "dimension": "daten",
      "target": 3,
      "note": "Demo assumption: documented review step"
    },
    "nextMilestone": "2026-09-25: review the synthetic pilot case"
  },
  {
    "id": "ctr-novex",
    "supplierId": "sup-novex",
    "title": "Framework agreement: Mirka",
    "clusters": [
      "schleif",
      "kleb",
      "kabine",
      "psa"
    ],
    "countries": [
      "AT",
      "DE",
      "SE",
      "FR",
      "ES",
      "PT",
      "CH",
      "PL"
    ],
    "volumeEUR": 986669.44,
    "termYears": 3,
    "stage": "Agree",
    "progressPct": 96,
    "negotiatedSavingPct": 16.24,
    "openPoints": [],
    "trainingCommitments": [
      {
        "trainingId": "t-daten",
        "scope": "Fictional pilot: invoice review across all sites"
      }
    ],
    "maturityGate": {
      "dimension": "daten",
      "target": 3,
      "note": "Demo assumption: documented review step"
    },
    "nextMilestone": "2026-09-25: review the synthetic pilot case"
  }
];
export const contractStages: ContractStage[] = [
  "Build",
  "Negotiate",
  "Agree"
];


export const fmtEUR = (v: number) => v >= 1000000 ? `${(v/1000000).toLocaleString('en-GB',{maximumFractionDigits:1})} million EUR` : `${(v/1000).toLocaleString('en-GB',{maximumFractionDigits:0})} thousand EUR`;
export const clusterById=(id:string)=>clusters.find(c=>c.id===id);
export const countryByIso=(iso:string)=>countries.find(c=>c.iso===iso);
export const trainingById=(id:string)=>trainings.find(t=>t.id===id);
export const maturityByIso=(iso:string)=>maturityProfiles.find(m=>m.iso===iso);
export const supplierById=(id:string)=>suppliers.find(s=>s.id===id);
export const contractById=(id:string)=>contracts.find(c=>c.id===id);

