// Synthetic Wolf Materials Lab data. Generated by kit/scripts/generate.py. No real commercial records.
export type TechFact = {
    text: string;
    source: 'web' | 'rfi';
    url?: string;
};
export type DossierEntry = {
    supplier: string;
    product: string;
    facts: TechFact[];
};
export type Dossier = {
    code: string;
    title: string;
    intro: string;
    introEn: string;
    entries: DossierEntry[];
};

export const dossiers: Dossier[] = [
  {
    "code": "WLF-1001",
    "title": "Graduated mixing cup",
    "intro": "Fictional offer characteristics for a technical review. No manufacturer research.",
    "introEn": "Fictional offer characteristics for a technical review. No manufacturer research.",
    "entries": [
      {
        "supplier": "Glasurit (BASF)",
        "product": "Glasurit (BASF) Graduated mixing cup",
        "facts": [
          {
            "text": "Synthetic RFI statement: sample testing required.",
            "source": "rfi"
          },
          {
            "text": "Confirm pack unit and approval for use before awarding the contract.",
            "source": "rfi"
          }
        ]
      },
      {
        "supplier": "Finixa",
        "product": "Finixa Graduated mixing cup",
        "facts": [
          {
            "text": "Synthetic RFI statement: sample testing required.",
            "source": "rfi"
          },
          {
            "text": "Confirm pack unit and approval for use before awarding the contract.",
            "source": "rfi"
          }
        ]
      },
      {
        "supplier": "SATA",
        "product": "SATA Graduated mixing cup",
        "facts": [
          {
            "text": "Synthetic RFI statement: sample testing required.",
            "source": "rfi"
          },
          {
            "text": "Confirm pack unit and approval for use before awarding the contract.",
            "source": "rfi"
          }
        ]
      },
      {
        "supplier": "tesa",
        "product": "tesa Graduated mixing cup",
        "facts": [
          {
            "text": "Synthetic RFI statement: sample testing required.",
            "source": "rfi"
          },
          {
            "text": "Confirm pack unit and approval for use before awarding the contract.",
            "source": "rfi"
          }
        ]
      },
      {
        "supplier": "Würth",
        "product": "Würth Graduated mixing cup",
        "facts": [
          {
            "text": "Synthetic RFI statement: sample testing required.",
            "source": "rfi"
          },
          {
            "text": "Confirm pack unit and approval for use before awarding the contract.",
            "source": "rfi"
          }
        ]
      },
      {
        "supplier": "Kovax",
        "product": "Kovax Graduated mixing cup",
        "facts": [
          {
            "text": "Synthetic RFI statement: sample testing required.",
            "source": "rfi"
          },
          {
            "text": "Confirm pack unit and approval for use before awarding the contract.",
            "source": "rfi"
          }
        ]
      }
    ]
  },
  {
    "code": "WLF-1002",
    "title": "Sanding discs 150 mm, coarse",
    "intro": "Fictional offer characteristics for a technical review. No manufacturer research.",
    "introEn": "Fictional offer characteristics for a technical review. No manufacturer research.",
    "entries": [
      {
        "supplier": "3M",
        "product": "3M Sanding discs 150 mm, coarse",
        "facts": [
          {
            "text": "Synthetic RFI statement: sample testing required.",
            "source": "rfi"
          },
          {
            "text": "Confirm pack unit and approval for use before awarding the contract.",
            "source": "rfi"
          }
        ]
      },
      {
        "supplier": "Glasurit (BASF)",
        "product": "Glasurit (BASF) Sanding discs 150 mm, coarse",
        "facts": [
          {
            "text": "Synthetic RFI statement: sample testing required.",
            "source": "rfi"
          },
          {
            "text": "Confirm pack unit and approval for use before awarding the contract.",
            "source": "rfi"
          }
        ]
      },
      {
        "supplier": "Mirka",
        "product": "Mirka Sanding discs 150 mm, coarse",
        "facts": [
          {
            "text": "Synthetic RFI statement: sample testing required.",
            "source": "rfi"
          },
          {
            "text": "Confirm pack unit and approval for use before awarding the contract.",
            "source": "rfi"
          }
        ]
      },
      {
        "supplier": "SATA",
        "product": "SATA Sanding discs 150 mm, coarse",
        "facts": [
          {
            "text": "Synthetic RFI statement: sample testing required.",
            "source": "rfi"
          },
          {
            "text": "Confirm pack unit and approval for use before awarding the contract.",
            "source": "rfi"
          }
        ]
      },
      {
        "supplier": "PPG / Nexa",
        "product": "PPG / Nexa Sanding discs 150 mm, coarse",
        "facts": [
          {
            "text": "Synthetic RFI statement: sample testing required.",
            "source": "rfi"
          },
          {
            "text": "Confirm pack unit and approval for use before awarding the contract.",
            "source": "rfi"
          }
        ]
      },
      {
        "supplier": "Würth",
        "product": "Würth Sanding discs 150 mm, coarse",
        "facts": [
          {
            "text": "Synthetic RFI statement: sample testing required.",
            "source": "rfi"
          },
          {
            "text": "Confirm pack unit and approval for use before awarding the contract.",
            "source": "rfi"
          }
        ]
      },
      {
        "supplier": "Starcke",
        "product": "Starcke Sanding discs 150 mm, coarse",
        "facts": [
          {
            "text": "Synthetic RFI statement: sample testing required.",
            "source": "rfi"
          },
          {
            "text": "Confirm pack unit and approval for use before awarding the contract.",
            "source": "rfi"
          }
        ]
      }
    ]
  },
  {
    "code": "WLF-1003",
    "title": "Standard masking tape",
    "intro": "Fictional offer characteristics for a technical review. No manufacturer research.",
    "introEn": "Fictional offer characteristics for a technical review. No manufacturer research.",
    "entries": [
      {
        "supplier": "3M",
        "product": "3M Standard masking tape",
        "facts": [
          {
            "text": "Synthetic RFI statement: sample testing required.",
            "source": "rfi"
          },
          {
            "text": "Confirm pack unit and approval for use before awarding the contract.",
            "source": "rfi"
          }
        ]
      },
      {
        "supplier": "Finixa",
        "product": "Finixa Standard masking tape",
        "facts": [
          {
            "text": "Synthetic RFI statement: sample testing required.",
            "source": "rfi"
          },
          {
            "text": "Confirm pack unit and approval for use before awarding the contract.",
            "source": "rfi"
          }
        ]
      },
      {
        "supplier": "Mirka",
        "product": "Mirka Standard masking tape",
        "facts": [
          {
            "text": "Synthetic RFI statement: sample testing required.",
            "source": "rfi"
          },
          {
            "text": "Confirm pack unit and approval for use before awarding the contract.",
            "source": "rfi"
          }
        ]
      },
      {
        "supplier": "tesa",
        "product": "tesa Standard masking tape",
        "facts": [
          {
            "text": "Synthetic RFI statement: sample testing required.",
            "source": "rfi"
          },
          {
            "text": "Confirm pack unit and approval for use before awarding the contract.",
            "source": "rfi"
          }
        ]
      },
      {
        "supplier": "PPG / Nexa",
        "product": "PPG / Nexa Standard masking tape",
        "facts": [
          {
            "text": "Synthetic RFI statement: sample testing required.",
            "source": "rfi"
          },
          {
            "text": "Confirm pack unit and approval for use before awarding the contract.",
            "source": "rfi"
          }
        ]
      },
      {
        "supplier": "Kovax",
        "product": "Kovax Standard masking tape",
        "facts": [
          {
            "text": "Synthetic RFI statement: sample testing required.",
            "source": "rfi"
          },
          {
            "text": "Confirm pack unit and approval for use before awarding the contract.",
            "source": "rfi"
          }
        ]
      },
      {
        "supplier": "Starcke",
        "product": "Starcke Standard masking tape",
        "facts": [
          {
            "text": "Synthetic RFI statement: sample testing required.",
            "source": "rfi"
          },
          {
            "text": "Confirm pack unit and approval for use before awarding the contract.",
            "source": "rfi"
          }
        ]
      }
    ]
  }
];
export const rechercheHinweis = "All statements are synthetic RFI scenarios, not web research.";


