// Synthetic Wolf Materials Lab data. Generated by kit/scripts/generate.py. No real commercial records.
export type ValueSource = 'nullmessung' | 'listenpreis_web' | 'hersteller_sop' | 'annahme';
export type PriceBasis = 'AT' | 'PT';
export type SystemStep = {
    grit: string;
    product: string;
    articleNo: string;
    consumption: number;
    unit: string;
    priceEUR: Record<PriceBasis, number>;
    priceSource: Record<PriceBasis, ValueSource>;
    timeMin: number;
};
export type SupplierSystem = {
    supplier: string;
    systemName: string;
    chainSource: ValueSource;
    prozessQuelle: string;
    setupMin: number;
    status: {
        anleitung: 'received' | 'promised' | 'requested';
        produkte: 'received' | 'promised' | 'requested';
        test: string;
    };
    steps: SystemStep[];
    note?: string;
};
export type RepairCase = {
    id: string;
    title: string;
    subtitle: string;
    defaultVolume: number;
    volumeMax: number;
    volumeNote: string;
    systems: SupplierSystem[];
};
export type SystemCosts = {
    materialEUR: number;
    timeMin: number;
    laborEUR: number;
    totalEUR: number;
};

export const DEFAULT_HOURLY_RATE = 74;
export const repairCases: RepairCase[] = [
  {
    "id": "ktl",
    "title": "Prepare a new part",
    "subtitle": "Synthetic standardized repair scenario",
    "defaultVolume": 24000,
    "volumeMax": 120000,
    "volumeNote": "Fictional annual volume for scenario comparison.",
    "systems": [
      {
        "supplier": "3M",
        "systemName": "3M demo process 1",
        "chainSource": "annahme",
        "prozessQuelle": "Synthetic process draft from Wolf Lab",
        "setupMin": 5,
        "status": {
          "anleitung": "received",
          "produkte": "promised",
          "test": "Synthetic pilot 09/2026"
        },
        "steps": [
          {
            "grit": "P180",
            "product": "Graduated mixing cup",
            "articleNo": "WLF-1001",
            "consumption": 0.54,
            "unit": "piece",
            "priceEUR": {
              "AT": 20.75,
              "PT": 39.86
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 4.2
          },
          {
            "grit": "P400",
            "product": "Paint cup for compressed-air spray gun",
            "articleNo": "WLF-1008",
            "consumption": 0.46,
            "unit": "piece",
            "priceEUR": {
              "AT": 100.16,
              "PT": 112.79
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 5.0
          },
          {
            "grit": "P800",
            "product": "Paint strainers 125 µ / 200 µ",
            "articleNo": "WLF-1015",
            "consumption": 1.09,
            "unit": "piece",
            "priceEUR": {
              "AT": 66.92,
              "PT": 70.66
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 6.9
          }
        ],
        "note": "Not a manufacturer instruction. Technically validate before real use."
      },
      {
        "supplier": "Glasurit (BASF)",
        "systemName": "Glasurit (BASF) demo process 1",
        "chainSource": "annahme",
        "prozessQuelle": "Synthetic process draft from Wolf Lab",
        "setupMin": 2,
        "status": {
          "anleitung": "promised",
          "produkte": "promised",
          "test": "Synthetic pilot 09/2026"
        },
        "steps": [
          {
            "grit": "P180",
            "product": "Graduated mixing cup",
            "articleNo": "WLF-1001",
            "consumption": 1.17,
            "unit": "piece",
            "priceEUR": {
              "AT": 20.75,
              "PT": 39.86
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 2.9
          },
          {
            "grit": "P400",
            "product": "Paint cup for compressed-air spray gun",
            "articleNo": "WLF-1008",
            "consumption": 1.12,
            "unit": "piece",
            "priceEUR": {
              "AT": 100.16,
              "PT": 112.79
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 3.8
          },
          {
            "grit": "P800",
            "product": "Paint strainers 125 µ / 200 µ",
            "articleNo": "WLF-1015",
            "consumption": 1.22,
            "unit": "piece",
            "priceEUR": {
              "AT": 66.92,
              "PT": 70.66
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 5.2
          }
        ],
        "note": "Not a manufacturer instruction. Technically validate before real use."
      },
      {
        "supplier": "Finixa",
        "systemName": "Finixa demo process 1",
        "chainSource": "annahme",
        "prozessQuelle": "Synthetic process draft from Wolf Lab",
        "setupMin": 3,
        "status": {
          "anleitung": "requested",
          "produkte": "promised",
          "test": "Synthetic pilot 09/2026"
        },
        "steps": [
          {
            "grit": "P180",
            "product": "Graduated mixing cup",
            "articleNo": "WLF-1001",
            "consumption": 1.12,
            "unit": "piece",
            "priceEUR": {
              "AT": 20.75,
              "PT": 39.86
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 4.8
          },
          {
            "grit": "P400",
            "product": "Paint cup for compressed-air spray gun",
            "articleNo": "WLF-1008",
            "consumption": 0.67,
            "unit": "piece",
            "priceEUR": {
              "AT": 100.16,
              "PT": 112.79
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 4.6
          },
          {
            "grit": "P800",
            "product": "Paint strainers 125 µ / 200 µ",
            "articleNo": "WLF-1015",
            "consumption": 0.29,
            "unit": "piece",
            "priceEUR": {
              "AT": 66.92,
              "PT": 70.66
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 5.4
          }
        ],
        "note": "Not a manufacturer instruction. Technically validate before real use."
      },
      {
        "supplier": "Mirka",
        "systemName": "Mirka demo process 1",
        "chainSource": "annahme",
        "prozessQuelle": "Synthetic process draft from Wolf Lab",
        "setupMin": 2,
        "status": {
          "anleitung": "received",
          "produkte": "promised",
          "test": "Synthetic pilot 09/2026"
        },
        "steps": [
          {
            "grit": "P180",
            "product": "Graduated mixing cup",
            "articleNo": "WLF-1001",
            "consumption": 0.56,
            "unit": "piece",
            "priceEUR": {
              "AT": 20.75,
              "PT": 39.86
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 4.2
          },
          {
            "grit": "P400",
            "product": "Paint cup for compressed-air spray gun",
            "articleNo": "WLF-1008",
            "consumption": 0.25,
            "unit": "piece",
            "priceEUR": {
              "AT": 100.16,
              "PT": 112.79
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 3.1
          },
          {
            "grit": "P800",
            "product": "Paint strainers 125 µ / 200 µ",
            "articleNo": "WLF-1015",
            "consumption": 0.41,
            "unit": "piece",
            "priceEUR": {
              "AT": 66.92,
              "PT": 70.66
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 3.5
          }
        ],
        "note": "Not a manufacturer instruction. Technically validate before real use."
      },
      {
        "supplier": "SATA",
        "systemName": "SATA demo process 1",
        "chainSource": "annahme",
        "prozessQuelle": "Synthetic process draft from Wolf Lab",
        "setupMin": 4,
        "status": {
          "anleitung": "promised",
          "produkte": "promised",
          "test": "Synthetic pilot 09/2026"
        },
        "steps": [
          {
            "grit": "P180",
            "product": "Graduated mixing cup",
            "articleNo": "WLF-1001",
            "consumption": 0.76,
            "unit": "piece",
            "priceEUR": {
              "AT": 20.75,
              "PT": 39.86
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 5.3
          },
          {
            "grit": "P400",
            "product": "Paint cup for compressed-air spray gun",
            "articleNo": "WLF-1008",
            "consumption": 0.2,
            "unit": "piece",
            "priceEUR": {
              "AT": 100.16,
              "PT": 112.79
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 2.5
          },
          {
            "grit": "P800",
            "product": "Paint strainers 125 µ / 200 µ",
            "articleNo": "WLF-1015",
            "consumption": 0.21,
            "unit": "piece",
            "priceEUR": {
              "AT": 66.92,
              "PT": 70.66
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 7.0
          }
        ],
        "note": "Not a manufacturer instruction. Technically validate before real use."
      }
    ]
  },
  {
    "id": "fueller",
    "title": "Sand a primed surface",
    "subtitle": "Synthetic standardized repair scenario",
    "defaultVolume": 31000,
    "volumeMax": 120000,
    "volumeNote": "Fictional annual volume for scenario comparison.",
    "systems": [
      {
        "supplier": "3M",
        "systemName": "3M demo process 2",
        "chainSource": "annahme",
        "prozessQuelle": "Synthetic process draft from Wolf Lab",
        "setupMin": 3,
        "status": {
          "anleitung": "received",
          "produkte": "promised",
          "test": "Synthetic pilot 09/2026"
        },
        "steps": [
          {
            "grit": "P180",
            "product": "Sanding discs 150 mm, coarse",
            "articleNo": "WLF-1002",
            "consumption": 1.14,
            "unit": "piece",
            "priceEUR": {
              "AT": 67.76,
              "PT": 66.59
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 5.6
          },
          {
            "grit": "P400",
            "product": "Sanding discs 150 mm, intermediate",
            "articleNo": "WLF-1009",
            "consumption": 0.58,
            "unit": "piece",
            "priceEUR": {
              "AT": 56.01,
              "PT": 89.15
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 4.5
          },
          {
            "grit": "P800",
            "product": "Sanding discs 150 mm, fine",
            "articleNo": "WLF-1016",
            "consumption": 1.25,
            "unit": "piece",
            "priceEUR": {
              "AT": 77.04,
              "PT": 53.78
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 3.9
          }
        ],
        "note": "Not a manufacturer instruction. Technically validate before real use."
      },
      {
        "supplier": "Glasurit (BASF)",
        "systemName": "Glasurit (BASF) demo process 2",
        "chainSource": "annahme",
        "prozessQuelle": "Synthetic process draft from Wolf Lab",
        "setupMin": 3,
        "status": {
          "anleitung": "promised",
          "produkte": "promised",
          "test": "Synthetic pilot 09/2026"
        },
        "steps": [
          {
            "grit": "P180",
            "product": "Sanding discs 150 mm, coarse",
            "articleNo": "WLF-1002",
            "consumption": 0.71,
            "unit": "piece",
            "priceEUR": {
              "AT": 67.76,
              "PT": 66.59
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 6.7
          },
          {
            "grit": "P400",
            "product": "Sanding discs 150 mm, intermediate",
            "articleNo": "WLF-1009",
            "consumption": 0.56,
            "unit": "piece",
            "priceEUR": {
              "AT": 56.01,
              "PT": 89.15
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 2.4
          },
          {
            "grit": "P800",
            "product": "Sanding discs 150 mm, fine",
            "articleNo": "WLF-1016",
            "consumption": 0.8,
            "unit": "piece",
            "priceEUR": {
              "AT": 77.04,
              "PT": 53.78
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 2.2
          }
        ],
        "note": "Not a manufacturer instruction. Technically validate before real use."
      },
      {
        "supplier": "Finixa",
        "systemName": "Finixa demo process 2",
        "chainSource": "annahme",
        "prozessQuelle": "Synthetic process draft from Wolf Lab",
        "setupMin": 5,
        "status": {
          "anleitung": "requested",
          "produkte": "promised",
          "test": "Synthetic pilot 09/2026"
        },
        "steps": [
          {
            "grit": "P180",
            "product": "Sanding discs 150 mm, coarse",
            "articleNo": "WLF-1002",
            "consumption": 0.51,
            "unit": "piece",
            "priceEUR": {
              "AT": 67.76,
              "PT": 66.59
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 6.7
          },
          {
            "grit": "P400",
            "product": "Sanding discs 150 mm, intermediate",
            "articleNo": "WLF-1009",
            "consumption": 0.42,
            "unit": "piece",
            "priceEUR": {
              "AT": 56.01,
              "PT": 89.15
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 6.9
          },
          {
            "grit": "P800",
            "product": "Sanding discs 150 mm, fine",
            "articleNo": "WLF-1016",
            "consumption": 1.09,
            "unit": "piece",
            "priceEUR": {
              "AT": 77.04,
              "PT": 53.78
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 3.4
          }
        ],
        "note": "Not a manufacturer instruction. Technically validate before real use."
      },
      {
        "supplier": "Mirka",
        "systemName": "Mirka demo process 2",
        "chainSource": "annahme",
        "prozessQuelle": "Synthetic process draft from Wolf Lab",
        "setupMin": 3,
        "status": {
          "anleitung": "received",
          "produkte": "promised",
          "test": "Synthetic pilot 09/2026"
        },
        "steps": [
          {
            "grit": "P180",
            "product": "Sanding discs 150 mm, coarse",
            "articleNo": "WLF-1002",
            "consumption": 1.17,
            "unit": "piece",
            "priceEUR": {
              "AT": 67.76,
              "PT": 66.59
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 3.3
          },
          {
            "grit": "P400",
            "product": "Sanding discs 150 mm, intermediate",
            "articleNo": "WLF-1009",
            "consumption": 1.14,
            "unit": "piece",
            "priceEUR": {
              "AT": 56.01,
              "PT": 89.15
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 4.0
          },
          {
            "grit": "P800",
            "product": "Sanding discs 150 mm, fine",
            "articleNo": "WLF-1016",
            "consumption": 0.8,
            "unit": "piece",
            "priceEUR": {
              "AT": 77.04,
              "PT": 53.78
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 2.3
          }
        ],
        "note": "Not a manufacturer instruction. Technically validate before real use."
      },
      {
        "supplier": "SATA",
        "systemName": "SATA demo process 2",
        "chainSource": "annahme",
        "prozessQuelle": "Synthetic process draft from Wolf Lab",
        "setupMin": 6,
        "status": {
          "anleitung": "promised",
          "produkte": "promised",
          "test": "Synthetic pilot 09/2026"
        },
        "steps": [
          {
            "grit": "P180",
            "product": "Sanding discs 150 mm, coarse",
            "articleNo": "WLF-1002",
            "consumption": 0.55,
            "unit": "piece",
            "priceEUR": {
              "AT": 67.76,
              "PT": 66.59
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 6.6
          },
          {
            "grit": "P400",
            "product": "Sanding discs 150 mm, intermediate",
            "articleNo": "WLF-1009",
            "consumption": 0.63,
            "unit": "piece",
            "priceEUR": {
              "AT": 56.01,
              "PT": 89.15
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 3.3
          },
          {
            "grit": "P800",
            "product": "Sanding discs 150 mm, fine",
            "articleNo": "WLF-1016",
            "consumption": 1.05,
            "unit": "piece",
            "priceEUR": {
              "AT": 77.04,
              "PT": 53.78
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 3.9
          }
        ],
        "note": "Not a manufacturer instruction. Technically validate before real use."
      }
    ]
  },
  {
    "id": "finish",
    "title": "Refinish a surface",
    "subtitle": "Synthetic standardized repair scenario",
    "defaultVolume": 38000,
    "volumeMax": 120000,
    "volumeNote": "Fictional annual volume for scenario comparison.",
    "systems": [
      {
        "supplier": "3M",
        "systemName": "3M demo process 3",
        "chainSource": "annahme",
        "prozessQuelle": "Synthetic process draft from Wolf Lab",
        "setupMin": 5,
        "status": {
          "anleitung": "received",
          "produkte": "promised",
          "test": "Synthetic pilot 09/2026"
        },
        "steps": [
          {
            "grit": "P180",
            "product": "Standard masking tape",
            "articleNo": "WLF-1003",
            "consumption": 0.57,
            "unit": "piece",
            "priceEUR": {
              "AT": 29.47,
              "PT": 22.96
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 4.6
          },
          {
            "grit": "P400",
            "product": "Fine-line tape",
            "articleNo": "WLF-1010",
            "consumption": 0.49,
            "unit": "piece",
            "priceEUR": {
              "AT": 17.67,
              "PT": 17.16
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 5.7
          },
          {
            "grit": "P800",
            "product": "Contour tape",
            "articleNo": "WLF-1017",
            "consumption": 0.93,
            "unit": "piece",
            "priceEUR": {
              "AT": 11.62,
              "PT": 23.87
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 6.3
          }
        ],
        "note": "Not a manufacturer instruction. Technically validate before real use."
      },
      {
        "supplier": "Glasurit (BASF)",
        "systemName": "Glasurit (BASF) demo process 3",
        "chainSource": "annahme",
        "prozessQuelle": "Synthetic process draft from Wolf Lab",
        "setupMin": 3,
        "status": {
          "anleitung": "promised",
          "produkte": "promised",
          "test": "Synthetic pilot 09/2026"
        },
        "steps": [
          {
            "grit": "P180",
            "product": "Standard masking tape",
            "articleNo": "WLF-1003",
            "consumption": 0.78,
            "unit": "piece",
            "priceEUR": {
              "AT": 29.47,
              "PT": 22.96
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 2.3
          },
          {
            "grit": "P400",
            "product": "Fine-line tape",
            "articleNo": "WLF-1010",
            "consumption": 0.5,
            "unit": "piece",
            "priceEUR": {
              "AT": 17.67,
              "PT": 17.16
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 6.8
          },
          {
            "grit": "P800",
            "product": "Contour tape",
            "articleNo": "WLF-1017",
            "consumption": 0.23,
            "unit": "piece",
            "priceEUR": {
              "AT": 11.62,
              "PT": 23.87
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 3.9
          }
        ],
        "note": "Not a manufacturer instruction. Technically validate before real use."
      },
      {
        "supplier": "Finixa",
        "systemName": "Finixa demo process 3",
        "chainSource": "annahme",
        "prozessQuelle": "Synthetic process draft from Wolf Lab",
        "setupMin": 4,
        "status": {
          "anleitung": "requested",
          "produkte": "promised",
          "test": "Synthetic pilot 09/2026"
        },
        "steps": [
          {
            "grit": "P180",
            "product": "Standard masking tape",
            "articleNo": "WLF-1003",
            "consumption": 1.0,
            "unit": "piece",
            "priceEUR": {
              "AT": 29.47,
              "PT": 22.96
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 3.2
          },
          {
            "grit": "P400",
            "product": "Fine-line tape",
            "articleNo": "WLF-1010",
            "consumption": 0.55,
            "unit": "piece",
            "priceEUR": {
              "AT": 17.67,
              "PT": 17.16
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 6.8
          },
          {
            "grit": "P800",
            "product": "Contour tape",
            "articleNo": "WLF-1017",
            "consumption": 1.08,
            "unit": "piece",
            "priceEUR": {
              "AT": 11.62,
              "PT": 23.87
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 4.5
          }
        ],
        "note": "Not a manufacturer instruction. Technically validate before real use."
      },
      {
        "supplier": "Mirka",
        "systemName": "Mirka demo process 3",
        "chainSource": "annahme",
        "prozessQuelle": "Synthetic process draft from Wolf Lab",
        "setupMin": 2,
        "status": {
          "anleitung": "received",
          "produkte": "promised",
          "test": "Synthetic pilot 09/2026"
        },
        "steps": [
          {
            "grit": "P180",
            "product": "Standard masking tape",
            "articleNo": "WLF-1003",
            "consumption": 0.57,
            "unit": "piece",
            "priceEUR": {
              "AT": 29.47,
              "PT": 22.96
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 6.6
          },
          {
            "grit": "P400",
            "product": "Fine-line tape",
            "articleNo": "WLF-1010",
            "consumption": 0.44,
            "unit": "piece",
            "priceEUR": {
              "AT": 17.67,
              "PT": 17.16
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 4.8
          },
          {
            "grit": "P800",
            "product": "Contour tape",
            "articleNo": "WLF-1017",
            "consumption": 0.52,
            "unit": "piece",
            "priceEUR": {
              "AT": 11.62,
              "PT": 23.87
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 6.0
          }
        ],
        "note": "Not a manufacturer instruction. Technically validate before real use."
      },
      {
        "supplier": "SATA",
        "systemName": "SATA demo process 3",
        "chainSource": "annahme",
        "prozessQuelle": "Synthetic process draft from Wolf Lab",
        "setupMin": 6,
        "status": {
          "anleitung": "promised",
          "produkte": "promised",
          "test": "Synthetic pilot 09/2026"
        },
        "steps": [
          {
            "grit": "P180",
            "product": "Standard masking tape",
            "articleNo": "WLF-1003",
            "consumption": 1.03,
            "unit": "piece",
            "priceEUR": {
              "AT": 29.47,
              "PT": 22.96
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 3.2
          },
          {
            "grit": "P400",
            "product": "Fine-line tape",
            "articleNo": "WLF-1010",
            "consumption": 1.21,
            "unit": "piece",
            "priceEUR": {
              "AT": 17.67,
              "PT": 17.16
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 6.5
          },
          {
            "grit": "P800",
            "product": "Contour tape",
            "articleNo": "WLF-1017",
            "consumption": 0.21,
            "unit": "piece",
            "priceEUR": {
              "AT": 11.62,
              "PT": 23.87
            },
            "priceSource": {
              "AT": "nullmessung",
              "PT": "nullmessung"
            },
            "timeMin": 5.3
          }
        ],
        "note": "Not a manufacturer instruction. Technically validate before real use."
      }
    ]
  }
];
export const SOURCE_LABEL: Record<ValueSource, string> = {
  "nullmessung": "Synthetic procurement",
  "listenpreis_web": "Synthetic reference price",
  "hersteller_sop": "Synthetic process draft",
  "annahme": "Demo assumption"
};

export function systemCosts(system:SupplierSystem,basis:PriceBasis,hourlyRate:number):SystemCosts {
const materialEUR=system.steps.reduce((s,st)=>s+st.consumption*st.priceEUR[basis],0);
const timeMin=system.steps.reduce((s,st)=>s+st.timeMin,0);const laborEUR=timeMin/60*hourlyRate;
return {materialEUR,timeMin,laborEUR,totalEUR:materialEUR+laborEUR};}
