// Synthetic Wolf Materials Lab data. Generated by kit/scripts/generate.py. No real commercial records.
export type BasketRow = {
    iso: string;
    name: string;
    totalEUR: number;
    matchedEUR: number;
    matchedLines: number;
    sharePct: number;
};
export type ParetoRow = {
    iso: string;
    name: string;
    nCodes: number;
    n80: number;
    top10Pct: number;
};
export type RouteRow = {
    iso: string;
    name: string;
    totalEUR: number;
    directEUR: number;
    directPct: number;
    directBrands: string[];
    topDistributors: {
        name: string;
        valueEUR: number;
    }[];
};
export type MonthPoint = {
    month: string;
    valueEUR: number;
};
export type MonthRow = {
    iso: string;
    name: string;
    points: MonthPoint[];
    medianEUR: number;
    peakMonth: string;
    peakFactor: number;
};
export type Kernzahl = {
    value: string;
    label: string;
    note: string;
};
export type Regel = {
    wenn: string;
    dann: string;
    kind: 'lever' | 'gap';
};
export type MonitorRow = {
    alarm: string;
    metrik: string;
    quelle: string;
    sofort: boolean;
};
export type SichtRow = {
    iso: string;
    name: string;
    suppliersVisible: number;
    files: number;
};

export const taMeta = {
  "stand": "18 September 2026",
  "basis": "Synthetic data: 4872 lines, 21 items, 10 suppliers",
  "totalEUR": 34007590.31,
  "matchedEUR": 26865922.91,
  "matchedSharePct": 79.0,
  "gtinFilled": 21,
  "offerArticles": 21
};
export const kernzahlen: Kernzahl[] = [
  {
    "value": "4872",
    "label": "Synthetic purchase lines",
    "note": "Entirely generated from the documented random seed."
  },
  {
    "value": "79 %",
    "label": "Matched basket",
    "note": "Matched using the synthetic product key."
  },
  {
    "value": "414",
    "label": "Offer versions",
    "note": "Three successive versions per offered item."
  }
];
export const basketRows: BasketRow[] = [
  {
    "iso": "AT",
    "name": "Austria",
    "totalEUR": 1258131.25,
    "matchedEUR": 996164.47,
    "matchedLines": 128,
    "sharePct": 79.2
  },
  {
    "iso": "DE",
    "name": "Germany",
    "totalEUR": 1184061.63,
    "matchedEUR": 885763.1,
    "matchedLines": 128,
    "sharePct": 74.8
  },
  {
    "iso": "SE",
    "name": "Sweden",
    "totalEUR": 1136765.45,
    "matchedEUR": 897432.33,
    "matchedLines": 128,
    "sharePct": 78.9
  },
  {
    "iso": "FR",
    "name": "France",
    "totalEUR": 1076432.28,
    "matchedEUR": 837975.97,
    "matchedLines": 128,
    "sharePct": 77.8
  },
  {
    "iso": "IT",
    "name": "Italy",
    "totalEUR": 1288274.81,
    "matchedEUR": 1080599.75,
    "matchedLines": 128,
    "sharePct": 83.9
  },
  {
    "iso": "ES",
    "name": "Spain",
    "totalEUR": 1063867.79,
    "matchedEUR": 834121.73,
    "matchedLines": 128,
    "sharePct": 78.4
  },
  {
    "iso": "PT",
    "name": "Portugal",
    "totalEUR": 1391118.34,
    "matchedEUR": 1043696.08,
    "matchedLines": 128,
    "sharePct": 75.0
  },
  {
    "iso": "CH",
    "name": "Switzerland",
    "totalEUR": 1167238.66,
    "matchedEUR": 890313.78,
    "matchedLines": 128,
    "sharePct": 76.3
  },
  {
    "iso": "PL",
    "name": "Poland",
    "totalEUR": 1206154.52,
    "matchedEUR": 930863.69,
    "matchedLines": 128,
    "sharePct": 77.2
  },
  {
    "iso": "CZ",
    "name": "Czechia",
    "totalEUR": 1058325.94,
    "matchedEUR": 840655.94,
    "matchedLines": 128,
    "sharePct": 79.4
  },
  {
    "iso": "SK",
    "name": "Slovakia",
    "totalEUR": 1198742.58,
    "matchedEUR": 952337.65,
    "matchedLines": 128,
    "sharePct": 79.4
  },
  {
    "iso": "HU",
    "name": "Hungary",
    "totalEUR": 1225180.44,
    "matchedEUR": 944370.56,
    "matchedLines": 128,
    "sharePct": 77.1
  },
  {
    "iso": "SI",
    "name": "Slovenia",
    "totalEUR": 1296414.55,
    "matchedEUR": 1036267.79,
    "matchedLines": 128,
    "sharePct": 79.9
  },
  {
    "iso": "HR",
    "name": "Croatia",
    "totalEUR": 1164222.98,
    "matchedEUR": 993812.25,
    "matchedLines": 128,
    "sharePct": 85.4
  },
  {
    "iso": "RO",
    "name": "Romania",
    "totalEUR": 1372390.51,
    "matchedEUR": 1092625.45,
    "matchedLines": 128,
    "sharePct": 79.6
  },
  {
    "iso": "BG",
    "name": "Bulgaria",
    "totalEUR": 1075972.36,
    "matchedEUR": 880842.95,
    "matchedLines": 128,
    "sharePct": 81.9
  },
  {
    "iso": "RS",
    "name": "Serbia",
    "totalEUR": 993781.16,
    "matchedEUR": 819269.29,
    "matchedLines": 128,
    "sharePct": 82.4
  },
  {
    "iso": "BA",
    "name": "Bosnia and Herzegovina",
    "totalEUR": 1160474.0,
    "matchedEUR": 878073.18,
    "matchedLines": 128,
    "sharePct": 75.7
  },
  {
    "iso": "AL",
    "name": "Albania",
    "totalEUR": 957464.62,
    "matchedEUR": 708365.19,
    "matchedLines": 128,
    "sharePct": 74.0
  },
  {
    "iso": "MK",
    "name": "North Macedonia",
    "totalEUR": 1272894.77,
    "matchedEUR": 1001079.18,
    "matchedLines": 128,
    "sharePct": 78.6
  },
  {
    "iso": "ME",
    "name": "Montenegro",
    "totalEUR": 1003321.75,
    "matchedEUR": 863322.9,
    "matchedLines": 128,
    "sharePct": 86.0
  },
  {
    "iso": "UA",
    "name": "Ukraine",
    "totalEUR": 1222379.39,
    "matchedEUR": 928997.71,
    "matchedLines": 128,
    "sharePct": 76.0
  },
  {
    "iso": "CN",
    "name": "China",
    "totalEUR": 1272781.0,
    "matchedEUR": 969622.53,
    "matchedLines": 128,
    "sharePct": 76.2
  },
  {
    "iso": "JP",
    "name": "Japan",
    "totalEUR": 1134451.07,
    "matchedEUR": 903434.4,
    "matchedLines": 128,
    "sharePct": 79.6
  },
  {
    "iso": "MY",
    "name": "Malaysia",
    "totalEUR": 1328153.02,
    "matchedEUR": 1098578.91,
    "matchedLines": 128,
    "sharePct": 82.7
  },
  {
    "iso": "SG",
    "name": "Singapore",
    "totalEUR": 1218724.75,
    "matchedEUR": 939504.36,
    "matchedLines": 128,
    "sharePct": 77.1
  },
  {
    "iso": "CL",
    "name": "Chile",
    "totalEUR": 1032237.23,
    "matchedEUR": 830549.41,
    "matchedLines": 128,
    "sharePct": 80.5
  },
  {
    "iso": "CO",
    "name": "Colombia",
    "totalEUR": 1075580.43,
    "matchedEUR": 873556.85,
    "matchedLines": 128,
    "sharePct": 81.2
  },
  {
    "iso": "XK",
    "name": "Kosovo",
    "totalEUR": 1172053.03,
    "matchedEUR": 913725.51,
    "matchedLines": 128,
    "sharePct": 78.0
  }
];
export const paretoRows: ParetoRow[] = [
  {
    "iso": "AT",
    "name": "Austria",
    "nCodes": 21,
    "n80": 12,
    "top10Pct": 74.6
  },
  {
    "iso": "DE",
    "name": "Germany",
    "nCodes": 21,
    "n80": 12,
    "top10Pct": 74.8
  },
  {
    "iso": "SE",
    "name": "Sweden",
    "nCodes": 21,
    "n80": 11,
    "top10Pct": 77.1
  },
  {
    "iso": "FR",
    "name": "France",
    "nCodes": 21,
    "n80": 12,
    "top10Pct": 73.4
  },
  {
    "iso": "IT",
    "name": "Italy",
    "nCodes": 21,
    "n80": 11,
    "top10Pct": 76.0
  },
  {
    "iso": "ES",
    "name": "Spain",
    "nCodes": 21,
    "n80": 13,
    "top10Pct": 70.6
  },
  {
    "iso": "PT",
    "name": "Portugal",
    "nCodes": 21,
    "n80": 12,
    "top10Pct": 74.7
  },
  {
    "iso": "CH",
    "name": "Switzerland",
    "nCodes": 21,
    "n80": 12,
    "top10Pct": 72.8
  },
  {
    "iso": "PL",
    "name": "Poland",
    "nCodes": 21,
    "n80": 11,
    "top10Pct": 76.6
  },
  {
    "iso": "CZ",
    "name": "Czechia",
    "nCodes": 21,
    "n80": 12,
    "top10Pct": 75.2
  },
  {
    "iso": "SK",
    "name": "Slovakia",
    "nCodes": 21,
    "n80": 12,
    "top10Pct": 73.9
  },
  {
    "iso": "HU",
    "name": "Hungary",
    "nCodes": 21,
    "n80": 12,
    "top10Pct": 76.0
  },
  {
    "iso": "SI",
    "name": "Slovenia",
    "nCodes": 21,
    "n80": 13,
    "top10Pct": 72.5
  },
  {
    "iso": "HR",
    "name": "Croatia",
    "nCodes": 21,
    "n80": 12,
    "top10Pct": 72.9
  },
  {
    "iso": "RO",
    "name": "Romania",
    "nCodes": 21,
    "n80": 12,
    "top10Pct": 74.9
  },
  {
    "iso": "BG",
    "name": "Bulgaria",
    "nCodes": 21,
    "n80": 12,
    "top10Pct": 72.2
  },
  {
    "iso": "RS",
    "name": "Serbia",
    "nCodes": 21,
    "n80": 14,
    "top10Pct": 63.9
  },
  {
    "iso": "BA",
    "name": "Bosnia and Herzegovina",
    "nCodes": 21,
    "n80": 12,
    "top10Pct": 72.9
  },
  {
    "iso": "AL",
    "name": "Albania",
    "nCodes": 21,
    "n80": 13,
    "top10Pct": 72.1
  },
  {
    "iso": "MK",
    "name": "North Macedonia",
    "nCodes": 21,
    "n80": 11,
    "top10Pct": 77.5
  },
  {
    "iso": "ME",
    "name": "Montenegro",
    "nCodes": 21,
    "n80": 12,
    "top10Pct": 70.5
  },
  {
    "iso": "UA",
    "name": "Ukraine",
    "nCodes": 21,
    "n80": 12,
    "top10Pct": 75.9
  },
  {
    "iso": "CN",
    "name": "China",
    "nCodes": 21,
    "n80": 12,
    "top10Pct": 74.5
  },
  {
    "iso": "JP",
    "name": "Japan",
    "nCodes": 21,
    "n80": 12,
    "top10Pct": 73.8
  },
  {
    "iso": "MY",
    "name": "Malaysia",
    "nCodes": 21,
    "n80": 13,
    "top10Pct": 72.1
  },
  {
    "iso": "SG",
    "name": "Singapore",
    "nCodes": 21,
    "n80": 13,
    "top10Pct": 69.4
  },
  {
    "iso": "CL",
    "name": "Chile",
    "nCodes": 21,
    "n80": 12,
    "top10Pct": 73.3
  },
  {
    "iso": "CO",
    "name": "Colombia",
    "nCodes": 21,
    "n80": 13,
    "top10Pct": 71.3
  },
  {
    "iso": "XK",
    "name": "Kosovo",
    "nCodes": 21,
    "n80": 13,
    "top10Pct": 72.5
  }
];
export const routeRows: RouteRow[] = [
  {
    "iso": "AT",
    "name": "Austria",
    "totalEUR": 1258131.25,
    "directEUR": 845707.15,
    "directPct": 67.2,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 412424.1
      }
    ]
  },
  {
    "iso": "DE",
    "name": "Germany",
    "totalEUR": 1184061.63,
    "directEUR": 857569.32,
    "directPct": 72.4,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 326492.31
      }
    ]
  },
  {
    "iso": "SE",
    "name": "Sweden",
    "totalEUR": 1136765.45,
    "directEUR": 860644.41,
    "directPct": 75.7,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 276121.04
      }
    ]
  },
  {
    "iso": "FR",
    "name": "France",
    "totalEUR": 1076432.28,
    "directEUR": 751629.12,
    "directPct": 69.8,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 324803.16
      }
    ]
  },
  {
    "iso": "IT",
    "name": "Italy",
    "totalEUR": 1288274.81,
    "directEUR": 860807.32,
    "directPct": 66.8,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 427467.49
      }
    ]
  },
  {
    "iso": "ES",
    "name": "Spain",
    "totalEUR": 1063867.79,
    "directEUR": 723222.16,
    "directPct": 68.0,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 340645.63
      }
    ]
  },
  {
    "iso": "PT",
    "name": "Portugal",
    "totalEUR": 1391118.34,
    "directEUR": 904669.0,
    "directPct": 65.0,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 486449.34
      }
    ]
  },
  {
    "iso": "CH",
    "name": "Switzerland",
    "totalEUR": 1167238.66,
    "directEUR": 843293.97,
    "directPct": 72.2,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 323944.69
      }
    ]
  },
  {
    "iso": "PL",
    "name": "Poland",
    "totalEUR": 1206154.52,
    "directEUR": 788041.03,
    "directPct": 65.3,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 418113.49
      }
    ]
  },
  {
    "iso": "CZ",
    "name": "Czechia",
    "totalEUR": 1058325.94,
    "directEUR": 731755.1,
    "directPct": 69.1,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 326570.84
      }
    ]
  },
  {
    "iso": "SK",
    "name": "Slovakia",
    "totalEUR": 1198742.58,
    "directEUR": 814985.54,
    "directPct": 68.0,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 383757.04
      }
    ]
  },
  {
    "iso": "HU",
    "name": "Hungary",
    "totalEUR": 1225180.44,
    "directEUR": 829736.31,
    "directPct": 67.7,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 395444.13
      }
    ]
  },
  {
    "iso": "SI",
    "name": "Slovenia",
    "totalEUR": 1296414.55,
    "directEUR": 936701.4,
    "directPct": 72.3,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 359713.15
      }
    ]
  },
  {
    "iso": "HR",
    "name": "Croatia",
    "totalEUR": 1164222.98,
    "directEUR": 808120.79,
    "directPct": 69.4,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 356102.19
      }
    ]
  },
  {
    "iso": "RO",
    "name": "Romania",
    "totalEUR": 1372390.51,
    "directEUR": 797139.0,
    "directPct": 58.1,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 575251.51
      }
    ]
  },
  {
    "iso": "BG",
    "name": "Bulgaria",
    "totalEUR": 1075972.36,
    "directEUR": 779621.92,
    "directPct": 72.5,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 296350.44
      }
    ]
  },
  {
    "iso": "RS",
    "name": "Serbia",
    "totalEUR": 993781.16,
    "directEUR": 676261.23,
    "directPct": 68.0,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 317519.93
      }
    ]
  },
  {
    "iso": "BA",
    "name": "Bosnia and Herzegovina",
    "totalEUR": 1160474.0,
    "directEUR": 668225.69,
    "directPct": 57.6,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 492248.31
      }
    ]
  },
  {
    "iso": "AL",
    "name": "Albania",
    "totalEUR": 957464.62,
    "directEUR": 635657.86,
    "directPct": 66.4,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 321806.76
      }
    ]
  },
  {
    "iso": "MK",
    "name": "North Macedonia",
    "totalEUR": 1272894.77,
    "directEUR": 841292.89,
    "directPct": 66.1,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 431601.88
      }
    ]
  },
  {
    "iso": "ME",
    "name": "Montenegro",
    "totalEUR": 1003321.75,
    "directEUR": 608166.44,
    "directPct": 60.6,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 395155.31
      }
    ]
  },
  {
    "iso": "UA",
    "name": "Ukraine",
    "totalEUR": 1222379.39,
    "directEUR": 805991.56,
    "directPct": 65.9,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 416387.83
      }
    ]
  },
  {
    "iso": "CN",
    "name": "China",
    "totalEUR": 1272781.0,
    "directEUR": 899523.59,
    "directPct": 70.7,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 373257.41
      }
    ]
  },
  {
    "iso": "JP",
    "name": "Japan",
    "totalEUR": 1134451.07,
    "directEUR": 742307.99,
    "directPct": 65.4,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 392143.08
      }
    ]
  },
  {
    "iso": "MY",
    "name": "Malaysia",
    "totalEUR": 1328153.02,
    "directEUR": 973958.69,
    "directPct": 73.3,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 354194.33
      }
    ]
  },
  {
    "iso": "SG",
    "name": "Singapore",
    "totalEUR": 1218724.75,
    "directEUR": 831275.5,
    "directPct": 68.2,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 387449.25
      }
    ]
  },
  {
    "iso": "CL",
    "name": "Chile",
    "totalEUR": 1032237.23,
    "directEUR": 646041.16,
    "directPct": 62.6,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 386196.07
      }
    ]
  },
  {
    "iso": "CO",
    "name": "Colombia",
    "totalEUR": 1075580.43,
    "directEUR": 692750.85,
    "directPct": 64.4,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 382829.58
      }
    ]
  },
  {
    "iso": "XK",
    "name": "Kosovo",
    "totalEUR": 1172053.03,
    "directEUR": 813933.14,
    "directPct": 69.4,
    "directBrands": [
      "3M",
      "Finixa",
      "Glasurit (BASF)",
      "Kovax",
      "Mirka",
      "PPG / Nexa",
      "SATA",
      "Starcke",
      "Würth",
      "tesa"
    ],
    "topDistributors": [
      {
        "name": "Würth",
        "valueEUR": 358119.89
      }
    ]
  }
];
export const monthRows: MonthRow[] = [
  {
    "iso": "AT",
    "name": "Austria",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 172568.87
      },
      {
        "month": "2026-02",
        "valueEUR": 124111.25
      },
      {
        "month": "2026-03",
        "valueEUR": 159991.23
      },
      {
        "month": "2026-04",
        "valueEUR": 163474.85
      },
      {
        "month": "2026-05",
        "valueEUR": 159800.34
      },
      {
        "month": "2026-06",
        "valueEUR": 154051.62
      },
      {
        "month": "2026-07",
        "valueEUR": 130477.99
      },
      {
        "month": "2026-08",
        "valueEUR": 193655.1
      }
    ],
    "medianEUR": 159895.785,
    "peakMonth": "2026-08",
    "peakFactor": 1.21
  },
  {
    "iso": "DE",
    "name": "Germany",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 142970.49
      },
      {
        "month": "2026-02",
        "valueEUR": 128336.38
      },
      {
        "month": "2026-03",
        "valueEUR": 134269.12
      },
      {
        "month": "2026-04",
        "valueEUR": 173802.72
      },
      {
        "month": "2026-05",
        "valueEUR": 156872.99
      },
      {
        "month": "2026-06",
        "valueEUR": 124929.06
      },
      {
        "month": "2026-07",
        "valueEUR": 169723.6
      },
      {
        "month": "2026-08",
        "valueEUR": 153157.27
      }
    ],
    "medianEUR": 148063.88,
    "peakMonth": "2026-04",
    "peakFactor": 1.17
  },
  {
    "iso": "SE",
    "name": "Sweden",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 130831.97
      },
      {
        "month": "2026-02",
        "valueEUR": 143758.08
      },
      {
        "month": "2026-03",
        "valueEUR": 132895.8
      },
      {
        "month": "2026-04",
        "valueEUR": 137455.66
      },
      {
        "month": "2026-05",
        "valueEUR": 137625.25
      },
      {
        "month": "2026-06",
        "valueEUR": 131764.76
      },
      {
        "month": "2026-07",
        "valueEUR": 169078.46
      },
      {
        "month": "2026-08",
        "valueEUR": 153355.47
      }
    ],
    "medianEUR": 137540.45500000002,
    "peakMonth": "2026-07",
    "peakFactor": 1.23
  },
  {
    "iso": "FR",
    "name": "France",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 120955.87
      },
      {
        "month": "2026-02",
        "valueEUR": 107628.26
      },
      {
        "month": "2026-03",
        "valueEUR": 99972.67
      },
      {
        "month": "2026-04",
        "valueEUR": 163759.48
      },
      {
        "month": "2026-05",
        "valueEUR": 129841.51
      },
      {
        "month": "2026-06",
        "valueEUR": 138302.15
      },
      {
        "month": "2026-07",
        "valueEUR": 161742.9
      },
      {
        "month": "2026-08",
        "valueEUR": 154229.44
      }
    ],
    "medianEUR": 134071.83,
    "peakMonth": "2026-04",
    "peakFactor": 1.22
  },
  {
    "iso": "IT",
    "name": "Italy",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 184451.17
      },
      {
        "month": "2026-02",
        "valueEUR": 157115.82
      },
      {
        "month": "2026-03",
        "valueEUR": 164742.1
      },
      {
        "month": "2026-04",
        "valueEUR": 173626.0
      },
      {
        "month": "2026-05",
        "valueEUR": 158853.75
      },
      {
        "month": "2026-06",
        "valueEUR": 158669.65
      },
      {
        "month": "2026-07",
        "valueEUR": 148743.55
      },
      {
        "month": "2026-08",
        "valueEUR": 142072.77
      }
    ],
    "medianEUR": 158761.7,
    "peakMonth": "2026-01",
    "peakFactor": 1.16
  },
  {
    "iso": "ES",
    "name": "Spain",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 171567.39
      },
      {
        "month": "2026-02",
        "valueEUR": 116735.8
      },
      {
        "month": "2026-03",
        "valueEUR": 120188.88
      },
      {
        "month": "2026-04",
        "valueEUR": 135807.98
      },
      {
        "month": "2026-05",
        "valueEUR": 110711.85
      },
      {
        "month": "2026-06",
        "valueEUR": 128215.2
      },
      {
        "month": "2026-07",
        "valueEUR": 132243.21
      },
      {
        "month": "2026-08",
        "valueEUR": 148397.48
      }
    ],
    "medianEUR": 130229.20499999999,
    "peakMonth": "2026-01",
    "peakFactor": 1.32
  },
  {
    "iso": "PT",
    "name": "Portugal",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 175839.65
      },
      {
        "month": "2026-02",
        "valueEUR": 208132.86
      },
      {
        "month": "2026-03",
        "valueEUR": 191180.09
      },
      {
        "month": "2026-04",
        "valueEUR": 166990.68
      },
      {
        "month": "2026-05",
        "valueEUR": 143230.34
      },
      {
        "month": "2026-06",
        "valueEUR": 188051.93
      },
      {
        "month": "2026-07",
        "valueEUR": 165007.0
      },
      {
        "month": "2026-08",
        "valueEUR": 152685.79
      }
    ],
    "medianEUR": 171415.16499999998,
    "peakMonth": "2026-02",
    "peakFactor": 1.21
  },
  {
    "iso": "CH",
    "name": "Switzerland",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 127478.68
      },
      {
        "month": "2026-02",
        "valueEUR": 171202.48
      },
      {
        "month": "2026-03",
        "valueEUR": 135878.09
      },
      {
        "month": "2026-04",
        "valueEUR": 173038.51
      },
      {
        "month": "2026-05",
        "valueEUR": 142682.72
      },
      {
        "month": "2026-06",
        "valueEUR": 119482.67
      },
      {
        "month": "2026-07",
        "valueEUR": 127847.96
      },
      {
        "month": "2026-08",
        "valueEUR": 169627.55
      }
    ],
    "medianEUR": 139280.405,
    "peakMonth": "2026-04",
    "peakFactor": 1.24
  },
  {
    "iso": "PL",
    "name": "Poland",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 164563.57
      },
      {
        "month": "2026-02",
        "valueEUR": 127481.11
      },
      {
        "month": "2026-03",
        "valueEUR": 163107.92
      },
      {
        "month": "2026-04",
        "valueEUR": 170801.74
      },
      {
        "month": "2026-05",
        "valueEUR": 163583.68
      },
      {
        "month": "2026-06",
        "valueEUR": 138383.92
      },
      {
        "month": "2026-07",
        "valueEUR": 152265.14
      },
      {
        "month": "2026-08",
        "valueEUR": 125967.44
      }
    ],
    "medianEUR": 157686.53000000003,
    "peakMonth": "2026-04",
    "peakFactor": 1.08
  },
  {
    "iso": "CZ",
    "name": "Czechia",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 113847.66
      },
      {
        "month": "2026-02",
        "valueEUR": 118748.24
      },
      {
        "month": "2026-03",
        "valueEUR": 129552.22
      },
      {
        "month": "2026-04",
        "valueEUR": 159973.01
      },
      {
        "month": "2026-05",
        "valueEUR": 105486.26
      },
      {
        "month": "2026-06",
        "valueEUR": 134707.7
      },
      {
        "month": "2026-07",
        "valueEUR": 145929.09
      },
      {
        "month": "2026-08",
        "valueEUR": 150081.76
      }
    ],
    "medianEUR": 132129.96000000002,
    "peakMonth": "2026-04",
    "peakFactor": 1.21
  },
  {
    "iso": "SK",
    "name": "Slovakia",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 142733.11
      },
      {
        "month": "2026-02",
        "valueEUR": 151478.52
      },
      {
        "month": "2026-03",
        "valueEUR": 162574.15
      },
      {
        "month": "2026-04",
        "valueEUR": 176174.47
      },
      {
        "month": "2026-05",
        "valueEUR": 122230.84
      },
      {
        "month": "2026-06",
        "valueEUR": 179264.43
      },
      {
        "month": "2026-07",
        "valueEUR": 154607.84
      },
      {
        "month": "2026-08",
        "valueEUR": 109679.22
      }
    ],
    "medianEUR": 153043.18,
    "peakMonth": "2026-06",
    "peakFactor": 1.17
  },
  {
    "iso": "HU",
    "name": "Hungary",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 156874.82
      },
      {
        "month": "2026-02",
        "valueEUR": 121869.33
      },
      {
        "month": "2026-03",
        "valueEUR": 146862.64
      },
      {
        "month": "2026-04",
        "valueEUR": 170864.27
      },
      {
        "month": "2026-05",
        "valueEUR": 162907.04
      },
      {
        "month": "2026-06",
        "valueEUR": 160368.56
      },
      {
        "month": "2026-07",
        "valueEUR": 131697.57
      },
      {
        "month": "2026-08",
        "valueEUR": 173736.21
      }
    ],
    "medianEUR": 158621.69,
    "peakMonth": "2026-08",
    "peakFactor": 1.1
  },
  {
    "iso": "SI",
    "name": "Slovenia",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 151298.19
      },
      {
        "month": "2026-02",
        "valueEUR": 152999.67
      },
      {
        "month": "2026-03",
        "valueEUR": 190632.67
      },
      {
        "month": "2026-04",
        "valueEUR": 146772.41
      },
      {
        "month": "2026-05",
        "valueEUR": 164499.09
      },
      {
        "month": "2026-06",
        "valueEUR": 153686.4
      },
      {
        "month": "2026-07",
        "valueEUR": 159901.05
      },
      {
        "month": "2026-08",
        "valueEUR": 176625.07
      }
    ],
    "medianEUR": 156793.72499999998,
    "peakMonth": "2026-03",
    "peakFactor": 1.22
  },
  {
    "iso": "HR",
    "name": "Croatia",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 140973.01
      },
      {
        "month": "2026-02",
        "valueEUR": 164516.19
      },
      {
        "month": "2026-03",
        "valueEUR": 149851.69
      },
      {
        "month": "2026-04",
        "valueEUR": 117280.78
      },
      {
        "month": "2026-05",
        "valueEUR": 154725.04
      },
      {
        "month": "2026-06",
        "valueEUR": 140185.82
      },
      {
        "month": "2026-07",
        "valueEUR": 149656.48
      },
      {
        "month": "2026-08",
        "valueEUR": 147033.97
      }
    ],
    "medianEUR": 148345.225,
    "peakMonth": "2026-02",
    "peakFactor": 1.11
  },
  {
    "iso": "RO",
    "name": "Romania",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 179468.05
      },
      {
        "month": "2026-02",
        "valueEUR": 167664.81
      },
      {
        "month": "2026-03",
        "valueEUR": 187445.82
      },
      {
        "month": "2026-04",
        "valueEUR": 182188.61
      },
      {
        "month": "2026-05",
        "valueEUR": 194721.03
      },
      {
        "month": "2026-06",
        "valueEUR": 126842.78
      },
      {
        "month": "2026-07",
        "valueEUR": 159932.02
      },
      {
        "month": "2026-08",
        "valueEUR": 174127.39
      }
    ],
    "medianEUR": 176797.72,
    "peakMonth": "2026-05",
    "peakFactor": 1.1
  },
  {
    "iso": "BG",
    "name": "Bulgaria",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 157808.19
      },
      {
        "month": "2026-02",
        "valueEUR": 136443.18
      },
      {
        "month": "2026-03",
        "valueEUR": 128815.16
      },
      {
        "month": "2026-04",
        "valueEUR": 108083.25
      },
      {
        "month": "2026-05",
        "valueEUR": 112984.71
      },
      {
        "month": "2026-06",
        "valueEUR": 121940.25
      },
      {
        "month": "2026-07",
        "valueEUR": 145944.31
      },
      {
        "month": "2026-08",
        "valueEUR": 163953.31
      }
    ],
    "medianEUR": 132629.16999999998,
    "peakMonth": "2026-08",
    "peakFactor": 1.24
  },
  {
    "iso": "RS",
    "name": "Serbia",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 108250.01
      },
      {
        "month": "2026-02",
        "valueEUR": 131508.1
      },
      {
        "month": "2026-03",
        "valueEUR": 121697.5
      },
      {
        "month": "2026-04",
        "valueEUR": 125171.68
      },
      {
        "month": "2026-05",
        "valueEUR": 143328.59
      },
      {
        "month": "2026-06",
        "valueEUR": 114902.99
      },
      {
        "month": "2026-07",
        "valueEUR": 127763.24
      },
      {
        "month": "2026-08",
        "valueEUR": 121159.05
      }
    ],
    "medianEUR": 123434.59,
    "peakMonth": "2026-05",
    "peakFactor": 1.16
  },
  {
    "iso": "BA",
    "name": "Bosnia and Herzegovina",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 171490.56
      },
      {
        "month": "2026-02",
        "valueEUR": 152789.47
      },
      {
        "month": "2026-03",
        "valueEUR": 125156.61
      },
      {
        "month": "2026-04",
        "valueEUR": 130974.66
      },
      {
        "month": "2026-05",
        "valueEUR": 135306.45
      },
      {
        "month": "2026-06",
        "valueEUR": 141948.14
      },
      {
        "month": "2026-07",
        "valueEUR": 151547.77
      },
      {
        "month": "2026-08",
        "valueEUR": 151260.34
      }
    ],
    "medianEUR": 146604.24,
    "peakMonth": "2026-01",
    "peakFactor": 1.17
  },
  {
    "iso": "AL",
    "name": "Albania",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 116985.61
      },
      {
        "month": "2026-02",
        "valueEUR": 127525.78
      },
      {
        "month": "2026-03",
        "valueEUR": 146998.56
      },
      {
        "month": "2026-04",
        "valueEUR": 101830.96
      },
      {
        "month": "2026-05",
        "valueEUR": 131212.68
      },
      {
        "month": "2026-06",
        "valueEUR": 116078.36
      },
      {
        "month": "2026-07",
        "valueEUR": 119228.41
      },
      {
        "month": "2026-08",
        "valueEUR": 97604.26
      }
    ],
    "medianEUR": 118107.01000000001,
    "peakMonth": "2026-03",
    "peakFactor": 1.24
  },
  {
    "iso": "MK",
    "name": "North Macedonia",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 150082.6
      },
      {
        "month": "2026-02",
        "valueEUR": 175667.93
      },
      {
        "month": "2026-03",
        "valueEUR": 165445.95
      },
      {
        "month": "2026-04",
        "valueEUR": 156994.79
      },
      {
        "month": "2026-05",
        "valueEUR": 144313.59
      },
      {
        "month": "2026-06",
        "valueEUR": 183457.41
      },
      {
        "month": "2026-07",
        "valueEUR": 150670.53
      },
      {
        "month": "2026-08",
        "valueEUR": 146261.97
      }
    ],
    "medianEUR": 153832.66,
    "peakMonth": "2026-06",
    "peakFactor": 1.19
  },
  {
    "iso": "ME",
    "name": "Montenegro",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 123521.49
      },
      {
        "month": "2026-02",
        "valueEUR": 123062.87
      },
      {
        "month": "2026-03",
        "valueEUR": 122238.01
      },
      {
        "month": "2026-04",
        "valueEUR": 129877.96
      },
      {
        "month": "2026-05",
        "valueEUR": 141199.39
      },
      {
        "month": "2026-06",
        "valueEUR": 142427.85
      },
      {
        "month": "2026-07",
        "valueEUR": 125020.62
      },
      {
        "month": "2026-08",
        "valueEUR": 95973.56
      }
    ],
    "medianEUR": 124271.055,
    "peakMonth": "2026-06",
    "peakFactor": 1.15
  },
  {
    "iso": "UA",
    "name": "Ukraine",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 142983.31
      },
      {
        "month": "2026-02",
        "valueEUR": 175854.23
      },
      {
        "month": "2026-03",
        "valueEUR": 141548.5
      },
      {
        "month": "2026-04",
        "valueEUR": 116704.88
      },
      {
        "month": "2026-05",
        "valueEUR": 160911.21
      },
      {
        "month": "2026-06",
        "valueEUR": 123069.49
      },
      {
        "month": "2026-07",
        "valueEUR": 201899.79
      },
      {
        "month": "2026-08",
        "valueEUR": 159407.98
      }
    ],
    "medianEUR": 151195.64500000002,
    "peakMonth": "2026-07",
    "peakFactor": 1.34
  },
  {
    "iso": "CN",
    "name": "China",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 142320.11
      },
      {
        "month": "2026-02",
        "valueEUR": 167385.41
      },
      {
        "month": "2026-03",
        "valueEUR": 147225.74
      },
      {
        "month": "2026-04",
        "valueEUR": 171295.27
      },
      {
        "month": "2026-05",
        "valueEUR": 165134.41
      },
      {
        "month": "2026-06",
        "valueEUR": 152170.68
      },
      {
        "month": "2026-07",
        "valueEUR": 171824.0
      },
      {
        "month": "2026-08",
        "valueEUR": 155425.38
      }
    ],
    "medianEUR": 160279.89500000002,
    "peakMonth": "2026-07",
    "peakFactor": 1.07
  },
  {
    "iso": "JP",
    "name": "Japan",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 143029.22
      },
      {
        "month": "2026-02",
        "valueEUR": 121236.93
      },
      {
        "month": "2026-03",
        "valueEUR": 136387.3
      },
      {
        "month": "2026-04",
        "valueEUR": 123380.47
      },
      {
        "month": "2026-05",
        "valueEUR": 152289.89
      },
      {
        "month": "2026-06",
        "valueEUR": 161920.0
      },
      {
        "month": "2026-07",
        "valueEUR": 148161.01
      },
      {
        "month": "2026-08",
        "valueEUR": 148046.25
      }
    ],
    "medianEUR": 145537.735,
    "peakMonth": "2026-06",
    "peakFactor": 1.11
  },
  {
    "iso": "MY",
    "name": "Malaysia",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 176228.11
      },
      {
        "month": "2026-02",
        "valueEUR": 175770.26
      },
      {
        "month": "2026-03",
        "valueEUR": 126675.06
      },
      {
        "month": "2026-04",
        "valueEUR": 167532.03
      },
      {
        "month": "2026-05",
        "valueEUR": 197350.94
      },
      {
        "month": "2026-06",
        "valueEUR": 183962.05
      },
      {
        "month": "2026-07",
        "valueEUR": 166849.21
      },
      {
        "month": "2026-08",
        "valueEUR": 133785.36
      }
    ],
    "medianEUR": 171651.14500000002,
    "peakMonth": "2026-05",
    "peakFactor": 1.15
  },
  {
    "iso": "SG",
    "name": "Singapore",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 149899.56
      },
      {
        "month": "2026-02",
        "valueEUR": 128933.11
      },
      {
        "month": "2026-03",
        "valueEUR": 160585.03
      },
      {
        "month": "2026-04",
        "valueEUR": 142675.43
      },
      {
        "month": "2026-05",
        "valueEUR": 174748.54
      },
      {
        "month": "2026-06",
        "valueEUR": 133448.19
      },
      {
        "month": "2026-07",
        "valueEUR": 177482.5
      },
      {
        "month": "2026-08",
        "valueEUR": 150952.39
      }
    ],
    "medianEUR": 150425.975,
    "peakMonth": "2026-07",
    "peakFactor": 1.18
  },
  {
    "iso": "CL",
    "name": "Chile",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 121054.44
      },
      {
        "month": "2026-02",
        "valueEUR": 130894.11
      },
      {
        "month": "2026-03",
        "valueEUR": 126063.78
      },
      {
        "month": "2026-04",
        "valueEUR": 110978.74
      },
      {
        "month": "2026-05",
        "valueEUR": 112409.89
      },
      {
        "month": "2026-06",
        "valueEUR": 143752.7
      },
      {
        "month": "2026-07",
        "valueEUR": 154321.33
      },
      {
        "month": "2026-08",
        "valueEUR": 132762.24
      }
    ],
    "medianEUR": 128478.945,
    "peakMonth": "2026-07",
    "peakFactor": 1.2
  },
  {
    "iso": "CO",
    "name": "Colombia",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 134993.25
      },
      {
        "month": "2026-02",
        "valueEUR": 116740.61
      },
      {
        "month": "2026-03",
        "valueEUR": 102700.29
      },
      {
        "month": "2026-04",
        "valueEUR": 151269.06
      },
      {
        "month": "2026-05",
        "valueEUR": 123113.54
      },
      {
        "month": "2026-06",
        "valueEUR": 152848.92
      },
      {
        "month": "2026-07",
        "valueEUR": 168788.46
      },
      {
        "month": "2026-08",
        "valueEUR": 125126.3
      }
    ],
    "medianEUR": 130059.775,
    "peakMonth": "2026-07",
    "peakFactor": 1.3
  },
  {
    "iso": "XK",
    "name": "Kosovo",
    "points": [
      {
        "month": "2026-01",
        "valueEUR": 145584.8
      },
      {
        "month": "2026-02",
        "valueEUR": 156475.16
      },
      {
        "month": "2026-03",
        "valueEUR": 123008.91
      },
      {
        "month": "2026-04",
        "valueEUR": 164906.4
      },
      {
        "month": "2026-05",
        "valueEUR": 141829.76
      },
      {
        "month": "2026-06",
        "valueEUR": 131302.89
      },
      {
        "month": "2026-07",
        "valueEUR": 136895.8
      },
      {
        "month": "2026-08",
        "valueEUR": 172049.31
      }
    ],
    "medianEUR": 143707.28,
    "peakMonth": "2026-08",
    "peakFactor": 1.2
  }
];
export const monthCoverageNotes: Record<string, string> = {
  "AT": "January-August 2026, entirely synthetic.",
  "DE": "January-August 2026, entirely synthetic.",
  "SE": "January-August 2026, entirely synthetic.",
  "FR": "January-August 2026, entirely synthetic.",
  "IT": "January-August 2026, entirely synthetic.",
  "ES": "January-August 2026, entirely synthetic.",
  "PT": "January-August 2026, entirely synthetic.",
  "CH": "January-August 2026, entirely synthetic.",
  "PL": "January-August 2026, entirely synthetic.",
  "CZ": "January-August 2026, entirely synthetic.",
  "SK": "January-August 2026, entirely synthetic.",
  "HU": "January-August 2026, entirely synthetic.",
  "SI": "January-August 2026, entirely synthetic.",
  "HR": "January-August 2026, entirely synthetic.",
  "RO": "January-August 2026, entirely synthetic.",
  "BG": "January-August 2026, entirely synthetic.",
  "RS": "January-August 2026, entirely synthetic.",
  "BA": "January-August 2026, entirely synthetic.",
  "AL": "January-August 2026, entirely synthetic.",
  "MK": "January-August 2026, entirely synthetic.",
  "ME": "January-August 2026, entirely synthetic.",
  "UA": "January-August 2026, entirely synthetic.",
  "CN": "January-August 2026, entirely synthetic.",
  "JP": "January-August 2026, entirely synthetic.",
  "MY": "January-August 2026, entirely synthetic.",
  "SG": "January-August 2026, entirely synthetic.",
  "CL": "January-August 2026, entirely synthetic.",
  "CO": "January-August 2026, entirely synthetic.",
  "XK": "January-August 2026, entirely synthetic."
};
export const regeln: Regel[] = [
  {
    "wenn": "Invoice price differs from the effective agreement",
    "dann": "Check price version and pack unit; document the decision.",
    "kind": "lever"
  },
  {
    "wenn": "Item code or agreed price missing",
    "dann": "Request human review; do not report savings.",
    "kind": "gap"
  }
];
export const monitorRows: MonitorRow[] = [
  {
    "alarm": "Price variance",
    "metrik": "Net price per normalized piece",
    "quelle": "synthetic-invoices.json / offer-versions.json",
    "sofort": true
  },
  {
    "alarm": "Record quality",
    "metrik": "Missing or conflicting fields",
    "quelle": "quality-issues.json",
    "sofort": false
  }
];
export const sichtRows: SichtRow[] = [
  {
    "iso": "AT",
    "name": "Austria",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "DE",
    "name": "Germany",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "SE",
    "name": "Sweden",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "FR",
    "name": "France",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "IT",
    "name": "Italy",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "ES",
    "name": "Spain",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "PT",
    "name": "Portugal",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "CH",
    "name": "Switzerland",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "PL",
    "name": "Poland",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "CZ",
    "name": "Czechia",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "SK",
    "name": "Slovakia",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "HU",
    "name": "Hungary",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "SI",
    "name": "Slovenia",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "HR",
    "name": "Croatia",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "RO",
    "name": "Romania",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "BG",
    "name": "Bulgaria",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "RS",
    "name": "Serbia",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "BA",
    "name": "Bosnia and Herzegovina",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "AL",
    "name": "Albania",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "MK",
    "name": "North Macedonia",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "ME",
    "name": "Montenegro",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "UA",
    "name": "Ukraine",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "CN",
    "name": "China",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "JP",
    "name": "Japan",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "MY",
    "name": "Malaysia",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "SG",
    "name": "Singapore",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "CL",
    "name": "Chile",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "CO",
    "name": "Colombia",
    "suppliersVisible": 10,
    "files": 1
  },
  {
    "iso": "XK",
    "name": "Kosovo",
    "suppliersVisible": 10,
    "files": 1
  }
];
export const grenzen: string[] = [
  "Commercial values, supplier relationships and records are synthetic; supplier names are real references.",
  "No real supplier assessment or price recommendation.",
  "Raw-record defects must be checked before aggregation."
];


