// Synthetic Wolf Materials Lab data. Generated by kit/scripts/generate.py. No real commercial records.
export interface TrainingPackageItem {
    trainingId: string;
    title: string;
    format: Training['format'];
    ratePerParticipantEUR: number;
    volumeEUR: number;
}
export interface TrainingPackage {
    participants: number;
    termYears: number;
    items: TrainingPackageItem[];
    totalEUR: number;
}
export type RatingDimension = 'Delivery time' | 'Quality' | 'Submission channel';
export interface PilotRating {
    iso: string;
    stars: 4 | 5;
    dimension: RatingDimension;
    quote: string;
    translation?: string;
}

export const pilotRatings: PilotRating[] = [
  {
    "iso": "AT",
    "stars": 4,
    "dimension": "Delivery time",
    "quote": "Synthetic pilot feedback: the match was traceable; the pack unit required clarification."
  },
  {
    "iso": "DE",
    "stars": 5,
    "dimension": "Quality",
    "quote": "Synthetic pilot feedback: the match was traceable; the pack unit required clarification."
  },
  {
    "iso": "SE",
    "stars": 4,
    "dimension": "Submission channel",
    "quote": "Synthetic pilot feedback: the match was traceable; the pack unit required clarification."
  },
  {
    "iso": "FR",
    "stars": 5,
    "dimension": "Delivery time",
    "quote": "Synthetic pilot feedback: the match was traceable; the pack unit required clarification."
  },
  {
    "iso": "IT",
    "stars": 4,
    "dimension": "Quality",
    "quote": "Synthetic pilot feedback: the match was traceable; the pack unit required clarification."
  },
  {
    "iso": "ES",
    "stars": 5,
    "dimension": "Submission channel",
    "quote": "Synthetic pilot feedback: the match was traceable; the pack unit required clarification."
  }
];
export const pilotRatingsContractId = "ctr-novex";

import type {Contract,Training} from './platform';

import {countryByIso,trainingById} from './platform';

export const pilotRatingAvg=pilotRatings.reduce((sum,r)=>sum+r.stars,0)/pilotRatings.length;
export const trainingPackageFor=(contract:Contract):TrainingPackage=>{
const participants=contract.countries.reduce((sum,iso)=>sum+(countryByIso(iso)?.bodyShops??0),0)*4;
const rates:Record<Training['format'],number>={Video:75,Roleplay:125,'Video + Roleplay':165};
const items=contract.trainingCommitments.flatMap(c=>{const t=trainingById(c.trainingId);return t?[{trainingId:t.id,title:t.title,format:t.format,ratePerParticipantEUR:rates[t.format],volumeEUR:participants*rates[t.format]*contract.termYears}]:[]});
return {participants,termYears:contract.termYears,items,totalEUR:items.reduce((s,i)=>s+i.volumeEUR,0)};};
